instill-ai/console

src/components/forms/ConfigureDestinationForm/ConfigureDestinationForm.tsx, src/components/forms/ConfigureSourceForm/ConfigureSourceForm.tsx, src/components/forms/CreateDestinationForm/CreateDestinationForm.tsx, src/components/forms/CreateSourceForm/CreateSourceForm.tsx, src/components/forms/OnboardingForm/OnboardingForm.tsx, src/components/modals/DeleteResourceModal/DeleteResourceModal.tsx, src/components/modals/ModalBase/ModalBase.tsx, src/components/ui/Buttons/ButtonBase/ButtonBase.tsx, src/components/ui/PageTitle/PageTitle.tsx, src/components/ui/Sidebar/Sidebar.tsx, src/components/ui/TablePlaceholders/TablePlaceholderBase/TablePlaceholderBase.tsx
Because
- ButtonBase is still using undefined props design
This commit
- Refactor ButtonBase to use Nullable props design
=> refactor: refactor ButtonBase to use nullable props design

.github/workflows/images.yml, .github/workflows/release.yml
Because
- Console need to upload its built docker image to docker hub
This commit
- Add related github action file
=> feat: add GitHub action related to docker hub

package.json, src/components/forms/TestModelInstanceForm/TestModelInstanceForm.tsx, src/components/forms/TestModelInstanceForm/index.ts, src/components/ui/TestModelInstanceResultBlock/TestModelInstanceResultBlock.tsx, src/components/ui/TestModelInstanceResultBlock/index.ts, src/lib/amplitude.ts, src/lib/instill/model/actions.ts, src/lib/instill/model/mutations.ts, src/pages/models/[id].tsx, src/services/model/index.ts, src/services/model/useTestModelInstance.ts, yarn.lock
Because
- We need a way to let user test model instance in console UI
This commit
- add test model instance service
=> feat: add test model instance service

.github/workflows/unit-test.yml, package.json
Because
- We need ci-unit-test to ensure code quality
This commit
- Implement unit test action
=> feat: add unit-test action

package.json, src/components/forms/MockData.tsx, src/components/ui/ModelDefinitionIcon/ModelDefinitionIcon.tsx, src/components/ui/ModelDefinitionLabel/ModelDefinitionLabel.tsx, src/components/ui/TableCells/ModelDefinitionCell/ModelDefinitionCell.tsx, yarn.lock
Because
- We have new model definition
This commit
- Add ArtiVC icon 
co-author: @xiaofei-du
=> feat: add ArtiVC Icon for model definition

.github/workflows/release.yml, release-please/config.json
Because
- Keep trying to make release-please work
This commit
- move config into config file
=> feat: move package name to manifest

e2e/connector/destination.spec.ts, e2e/connector/source.spec.ts, src/components/forms/CreateDestinationForm/CreateDestinationForm.tsx, src/components/forms/CreateSourceForm/CreateSourceForm.tsx
Because
- We need e2e test for ensuring code quality
This commit
- Implement e2e test for source connector
=> feat: add destination e2e test

Dockerfile, docker-compose.app.yml, src/pages/_app.tsx
Because
- We need a way to let user opt out the usage collection 
This commit
- Use docker-compose args to specify this behavior
=> feat: add DISABLE_USAGE_COLLECTION args config in docker-compose

src/pages/models/[id].tsx
Because
- There are some issues related to hook deps
This commit
- fix related issue
=> fix: fix hooks deps issue

src/components/forms/CreateDestinationForm/CreateDestinationForm.tsx, src/components/forms/CreateModelForm/CreateModelForm.tsx, src/components/forms/CreatePipelineForm/SetupDestinationStep/CreateNewDestinationFlow.tsx, src/components/forms/CreatePipelineForm/SetupModelStep/CreateNewModelInstanceFlow.tsx, src/components/forms/CreatePipelineForm/SetupModelStep/SetupModelStep.tsx, src/components/forms/CreatePipelineForm/SetupModelStep/UseExistingModeInstancelFlow.tsx, src/components/forms/CreatePipelineForm/SetupPipelineDetailsStep/SetupPipelineDetailsStep.tsx, src/components/forms/CreatePipelineForm/SetupSourceStep/CreateNewSourceFlow.tsx, src/components/forms/CreateSourceForm/CreateSourceForm.tsx, src/components/forms/OnboardingForm/OnboardingForm.tsx, src/pages/onboarding.tsx
Because
- There are multiple typo related to form.
This commit
- Fix typo
- close #37
=> fix: fix various UI issue related to form

src/components/forms/CreateModelForm/CreateModelForm.tsx
Because
- When create local model, there is a bug related to form validation
This commit
- fix above bug
=> fix: fix create model form error

src/components/ui/Sidebar/Sidebar.tsx, src/components/ui/Sidebar/Tab.tsx
Because
- Sidebar will shift when collapse
This commit
- Implement new style to solve this issue
=> fix: fix sidebar shifting issue

src/components/forms/OnboardingForm/OnboardingForm.tsx, src/components/modals/DeleteResourceModal/DeleteResourceModal.tsx, src/components/ui/Buttons/ButtonBase/ButtonBase.tsx, src/components/ui/Buttons/CollapseSidebarButton/CollapseSidebarButton.tsx, src/components/ui/Buttons/OutlineButton/OutlineButton.tsx, src/components/ui/Buttons/PrimaryButton/PrimaryButton.tsx, src/components/ui/Sidebar/Sidebar.tsx, src/components/ui/Sidebar/Tab.tsx, tailwind.config.js
Because
- Sidebar style is not correct
This commit
- Fix sidebar style and add multiple hovered color
=> fix: fix sidebar style

src/components/ui/ModelInstanceTaskLabel/ModelInstanceTaskLabel.tsx
Because
- #71 
This commit
- Fix model instance task parsing issue
- close #71
=> fix: fix model instance task parsing issue

.github/workflows/images.yml, .github/workflows/playwright.yml
Because
- Release action has error
This commit
- fix this issue
=> fix: fix release github action error

.github/workflows/images.yml
Because
- Checkout version is wrong
This commit
- Fix version
=> fix: fix checkout action version

.github/workflows/images.yml, .github/workflows/unit-test.yml
Because
- There has issue when installing deps at image action
This commit
=> fix: fix condition issue when installing deps at image action

src/components/forms/pipeline/ConfigurePipelineForm/ConfigurePipelineForm.tsx
Because
- We need a place to teach user how to trigger their pipeline
This commit
- add trigger section at configure pipeline form
=> feat: add trigger section at configure pipeline form

src/components/forms/model/TestModelInstanceForm/TestModelInstanceForm.tsx, src/pages/models/[id].tsx
Because
- User can't test model instance if it is offline
This commit
- Stop user from testing model instance if it is offline
- Fix typo
- close #72
=> feat: stop user from testing model instance if it is offline

package.json, src/components/formik/FormikField/StatefulToggleField/StatefulToggleField.tsx, src/components/formik/FormikField/ToggleField/ToggleField.tsx, src/components/forms/mgmt/OnboardingForm/OnboardingForm.tsx, src/components/forms/pipeline/ConfigurePipelineForm/ConfigurePipelineForm.tsx, src/components/forms/pipeline/CreatePipelineForm/SetupPipelineDetailsStep/SetupPipelineDetailsStep.tsx, src/pages/models/[id].tsx, yarn.lock
Because
- Toggle field can't use value prop and defaultChecked prop at the same time
This commit
- Fix the above issue
=> fix: fix toggle field

src/components/forms/connector/source/CreateSourceForm/CreateSourceForm.tsx, src/components/forms/model/CreateModelForm/CreateModelForm.tsx, src/components/forms/pipeline/CreatePipelineForm/SetupDestinationStep/CreateNewDestinationFlow.tsx, src/components/forms/pipeline/CreatePipelineForm/SetupModelStep/CreateNewModelInstanceFlow.tsx, src/components/forms/pipeline/CreatePipelineForm/SetupPipelineDetailsStep/SetupPipelineDetailsStep.tsx, src/components/forms/pipeline/CreatePipelineForm/SetupSourceStep/CreateNewSourceFlow.tsx
Because
- Id field's label should be ID
This commit
- Refactor all id field label from Id to ID
- close #37
=> refactor: refactor all id field label from Id to ID

package.json, src/components/formik/FormikField/SingleSelect/SingleSelect.tsx, src/components/forms/connector/destination/ConfigureDestinationForm/ConfigureDestinationForm.tsx, src/components/forms/connector/source/ConfigureSourceForm/ConfigureSourceForm.tsx, src/components/forms/connector/source/CreateSourceForm/CreateSourceForm.tsx, src/components/forms/mgmt/OnboardingForm/OnboardingForm.tsx, src/components/forms/model/CreateModelForm/CreateModelForm.tsx, src/components/forms/pipeline/CreatePipelineForm/SetupDestinationStep/CreateNewDestinationFlow.tsx, src/components/forms/pipeline/CreatePipelineForm/SetupDestinationStep/SetupDestinationStep.tsx, src/components/forms/pipeline/CreatePipelineForm/SetupDestinationStep/UseExistingDestinationFlow.tsx, src/components/forms/pipeline/CreatePipelineForm/SetupModelStep/CreateNewModelInstanceFlow.tsx, src/components/forms/pipeline/CreatePipelineForm/SetupModelStep/UseExistingModeInstancelFlow.tsx, src/components/forms/pipeline/CreatePipelineForm/SetupPipelineModeStep/SetupPipelineModeStep.tsx, src/components/forms/pipeline/CreatePipelineForm/SetupSourceStep/CreateNewSourceFlow.tsx, src/components/forms/pipeline/CreatePipelineForm/SetupSourceStep/UseExistingSourceFlow.tsx, yarn.lock
Because
- design-system is refactoring its types
- https://github.com/instill-ai/design-system/issues/27
This commit
- Refactor SingelSelect types
=> refactor: refactor SingleSelect types

src/components/formik/FormikField/TextArea/TextArea.tsx, src/components/forms/connector/destination/CreateDestinationForm/CreateDestinationForm.tsx, src/components/forms/model/ConfigureModelForm/ConfigureModelForm.tsx, src/components/forms/model/CreateModelForm/CreateModelForm.tsx, src/components/forms/pipeline/ConfigurePipelineForm/ConfigurePipelineForm.tsx, src/components/forms/pipeline/CreatePipelineForm/SetupModelStep/CreateNewModelInstanceFlow.tsx, src/components/forms/pipeline/CreatePipelineForm/SetupPipelineDetailsStep/SetupPipelineDetailsStep.tsx, src/lib/airbytes/hooks/useBuildAirbyteFields.tsx
Because
- design-system is refactoring its types
- https://github.com/instill-ai/design-system/issues/27
This commit
- Refactor Textarea types
=> refactor: refactor text area types

package.json, src/components/ui/Sidebar/ButtonTab.tsx, src/components/ui/Sidebar/LinkTab.tsx, src/components/ui/Sidebar/Sidebar.tsx, yarn.lock
Because
- We need to the resource tabs to display our external links
This commit
- Implement resource tabs
- close #113 
- close #114
=> feat: Implement resource tab

src/components/forms/model/ConfigureModelInstanceForm/ConfigureModelInstanceForm.tsx, src/components/forms/model/CreateModelForm/CreateModelForm.tsx, src/components/forms/pipeline/CreatePipelineForm/SetupModelStep/CreateNewModelInstanceFlow.tsx, src/lib/instill/model/mutations.ts, src/lib/instill/model/types.ts
Because
- #132 
This commit
- Adapt new model json configuration design
- close #132
=> refactor: adapt model json backend

src/components/forms/connector/destination/ConfigureDestinationForm/ConfigureDestinationForm.tsx, src/components/forms/connector/source/ConfigureSourceForm/ConfigureSourceForm.tsx, src/components/forms/model/ConfigureModelForm/ConfigureModelForm.tsx, src/components/forms/pipeline/ConfigurePipelineForm/ConfigurePipelineForm.tsx
Because
- #148
This commit
- Disable delete button on demo website
- close #148
=> feat: stop user delete resource on demo website

src/components/layouts/PageHead/PageHead.tsx, src/pages/_document.tsx
Because
- GA code not injected into console
This commit
- Fix this issue by moving injection to PageHead
=> fix: fix GA tracking code not injected issue

package.json, src/components/formik/FormikField/TextField/TextField.tsx, src/components/forms/connector/destination/CreateDestinationForm/CreateDestinationForm.tsx, src/components/forms/mgmt/OnboardingForm/OnboardingForm.tsx, src/components/forms/model/ConfigureModelInstanceForm/ConfigureModelInstanceForm.tsx, src/components/forms/model/CreateModelForm/CreateModelForm.tsx, src/components/forms/pipeline/CreatePipelineForm/SetupDestinationStep/CreateNewDestinationFlow.tsx, src/components/forms/pipeline/CreatePipelineForm/SetupModelStep/CreateNewModelInstanceFlow.tsx, src/components/forms/pipeline/CreatePipelineForm/SetupPipelineDetailsStep/SetupPipelineDetailsStep.tsx, src/components/forms/pipeline/CreatePipelineForm/SetupSourceStep/CreateNewSourceFlow.tsx, src/components/modals/DeleteResourceModal/DeleteResourceModal.tsx, yarn.lock
Because
- Design system is under refactoring of input field's default value
- Once a prop has default value, we could remove it when use the component if there is no need to change that
- https://github.com/instill-ai/design-system/issues/27
This commit
- Update TextField TextField props
=> feat: update TextField props and remove props that have default

src/components/forms/mgmt/OnboardingForm/OnboardingForm.tsx, src/lib/instill/mgmt/mutations.ts
Because
- #168 
This commit
- Make email field required at onboarding form
- close #168
=> feat: make email field required at onboarding form

.github/workflows/add-pr-to-prj.yml
Because
- #170 
This commit
- Fix ci issue
- close #170
=> fix: fix action issue

src/pages/models/[id].tsx
Because
- #173 
This commit
- Fix get pipeline bug on model page
=> fix: fix get pipeline bug on model page

src/components/forms/connector/destination/ConfigureDestinationForm/ConfigureDestinationForm.tsx, src/components/forms/connector/source/ConfigureSourceForm/ConfigureSourceForm.tsx, src/components/forms/model/ConfigureModelForm/ConfigureModelForm.tsx, src/components/forms/model/CreateModelForm/CreateModelForm.tsx, src/components/ui/Sidebar/Sidebar.tsx, src/lib/instill/model/mutations.ts, src/lib/instill/types.ts
Because
- #177
- When create ArtiVC model, console didn't use parsed JSON
This commit
- Use parsed JSON as payload
- Update Sidebar name
- close #177
=> fix: fix ArtiVC model creation issue

src/components/forms/mgmt/OnboardingForm/OnboardingForm.tsx, src/lib/cookie.ts, src/pages/api/set-user-cookie.ts
Because
- Onboarding form subscription is not working 
- Api route is failed at docker but working at when development
This commit
- Fix subscription issue
- Examine api route issue
=> fix: fix onboarding form

src/components/forms/connector/destination/CreateDestinationForm/CreateDestinationForm.tsx, src/services/connector/destination/mutations/useDeleteDestination.ts
Because
- #180 
- #181 
This commit
- Fix destination cache not remove
- Fix can't correctly create http and grpc issue
- close #180
- close #181
=> fix: fix destination cache not remove and create http & grpc issue

package.json, src/components/forms/connector/destination/CreateDestinationForm/CreateDestinationForm.tsx, src/components/forms/model/ConfigureModelInstanceForm/ConfigureModelInstanceForm.tsx, src/components/forms/model/CreateModelForm/CreateModelForm.tsx, src/components/forms/pipeline/CreatePipelineForm/SetupModelStep/CreateNewModelInstanceFlow.tsx, src/components/forms/pipeline/CreatePipelineForm/SetupModelStep/UseExistingModeInstancelFlow.tsx, src/lib/airbytes/airbyteSchemaToYup.ts, src/lib/airbytes/hooks/useBuildAirbyteFields.tsx, src/lib/dot/index.test.ts, src/services/transformation.ts, yarn.lock
Because
- The schema validation is not correct
- HTML input element value is not correct
This commit
- Fix above issue, now console can correctly create Airbyte destination
=> fix: fix can't correctly create Airbyte destination

src/components/ui/TableCells/InstanceCell/InstanceCell.tsx
Because
- #195 
This commit
- Fix model table's instance icon
=> fix: fix model table's instance icon

src/components/ui/CreatePipelineProgress/CreatePipelineProgress.tsx
Because
- #194 
This commit
- Refactor CreatePipelineProgress step name
- close #194
=> refactor: refactor CreatePipelineProgress step name

src/components/ui/StateLabel/StateLabel.tsx, src/components/ui/TableCells/ConnectionTypeCell/ConnectionTypeCell.tsx, src/components/ui/TableCells/InstanceCell/InstanceCell.tsx, src/components/ui/Tables/DestinationsTable/DestinationsTable.tsx, src/hooks/useStateOverviewCounts.ts, src/lib/instill/connector/types.ts, src/lib/instill/model/types.ts, src/pages/destinations/[id].tsx
Because
- #190 
- #191
This commit
- Fix wrong connector state
- Fix wrong connector display definition name
- close #190
- close #191
=> fix: fix wrong connector state

package.json, src/components/formik/FormikField/SingleSelect/SingleSelect.tsx, src/components/formik/FormikField/StatefulToggleField/StatefulToggleField.tsx, src/components/formik/FormikField/TextArea/TextArea.tsx, src/components/formik/FormikField/TextField/TextField.tsx, src/components/formik/FormikField/ToggleField/ToggleField.tsx, src/components/formik/FormikField/UploadFileField/UploadFileField.tsx, src/components/forms/connector/destination/CreateDestinationForm/CreateDestinationForm.tsx, src/components/forms/model/ConfigureModelInstanceForm/ConfigureModelInstanceForm.tsx, src/components/modals/DeleteResourceModal/DeleteResourceModal.tsx, src/components/sections/ChagneResourceStateSection/ChangeResourceStateSection.tsx, src/components/sections/TestModelInstanceSection/TestModelInstanceSection.tsx, src/lib/airbytes/components/OneOfConditionSection/OneOfConditionSection.tsx, src/lib/airbytes/hooks/useBuildAirbyteFields.tsx, src/pages/models/[id].tsx, yarn.lock
Because
- #189
This commit
- Update design-system version to 0.0.103
- Remove default scroll behavior of number input field
- Remove redundant input props
- close #189
=> fix: remove default scroll behavior of number input field

src/pages/api/set-user-cookie.ts
- #187
- Hostname is not correctly setup during setting cookie
- close #187
=> fix: fix hostname not correctly set

src/components/formik/FormikField/UploadFileField/UploadFileField.tsx, src/components/forms/connector/destination/CreateDestinationForm/CreateDestinationForm.tsx, src/components/forms/model/CreateModelForm/CreateModelForm.tsx, src/components/forms/pipeline/CreatePipelineForm/CreatePipelineForm.tsx, src/components/sections/TestModelInstanceSection/TestModelInstanceSection.tsx, src/lib/airbytes/hooks/useAirbyteFieldValues.ts, src/lib/airbytes/hooks/useBuildAirbyteFields.tsx, src/lib/instill/model/actions.ts, src/lib/instill/model/mutations.ts
- ToggleField not working
- UploadField not working
=> fix: fix toggle field issue

src/components/forms/commons/FormBase/FormBase.tsx, src/components/forms/connector/destination/CreateDestinationForm/CreateDestinationForm.tsx, src/components/forms/model/ConfigureModelInstanceForm/ConfigureModelInstanceForm.tsx, src/components/forms/pipeline/CreatePipelineForm/SetupDestinationStep/CreateNewDestinationFlow.tsx, src/components/forms/pipeline/CreatePipelineForm/SetupDestinationStep/SetupDestinationStep.tsx, src/components/forms/pipeline/CreatePipelineForm/SetupDestinationStep/UseExistingDestinationFlow.tsx, src/components/forms/pipeline/CreatePipelineForm/SetupPipelineModeStep/SetupPipelineModeStep.tsx, src/pages/destinations/create.tsx
Because
- #193 
This commit
- Support create Airbyte destination under pipeline flow
- close #193
=> feat: support create Async pipeline

src/components/forms/pipeline/CreatePipelineForm/SetupPipelineDetailsStep/SetupPipelineDetailsStep.tsx
Because
- #204
This commit
- Remove pipeline state toggle button
- close #204
=> fix: remove pipeline state toggle button

src/components/ui/Sidebar/Sidebar.tsx
Because
- Docs has new URL
This commit
- update docs link at Sidebar
=> feat: update sidebar docs link

package.json, pnpm-lock.yaml, src/components/ui/ModelInstanceTaskLabel/ModelInstanceTaskLabel.tsx
Because
- #225
- #212
- https://github.com/instill-ai/design-system/pull/59
This commit
- Update object-detection icon (close #212)
- Add OCR icon (close #225)
=> feat: update object-detection icon and add ocr icon

package.json, pnpm-lock.yaml
Because
- #214 
- https://github.com/instill-ai/design-system/pull/61
This commit
- Fix the secret field trigger submission issue
=> feat: update design system to fix secret field trigger submission issue

src/components/forms/model/CreateModelForm/CreateModelForm.tsx, src/components/forms/pipeline/CreatePipelineForm/SetupModelStep/CreateNewModelInstanceFlow.tsx, src/pages/destinations/[id].tsx, src/pages/sources/[id].tsx
Because
- #215
- #210
This commit
- Lift model description field at connector creation flow and create pipeline flow (close #215)
- Rename pipeline table's title at connector details page (close #210)
=> refactor: refactor UI

src/components/ui/ErrorBoundary.tsx, src/components/ui/index.ts, src/pages/_app.tsx
Because
- #120
This commit
- Add catch-all error boundary
=> feat: add error boundary

src/components/ui/TableCells/NameCell/NameCell.tsx, src/utils/timeUtils.ts
Because
- Last updated time (second) doesn't get rounded 
This commit
- Fix the calculation of last updated time
=> fix: fix the calculation of last updated time

src/components/forms/model/CreateModelForm/CreateModelForm.tsx, src/components/ui/StateLabel.tsx, src/lib/instill/mgmt/mocks.ts
Because
- #247 
- #246
- #245
This commit
- Fix state label typo (close #245)
- Fix typo on onboarding form (close #246)
=> fix: fix various typo

src/components/destination/ConfigureDestinationForm.tsx, src/components/pipeline/CreatePipelineForm/SetupDestinationStep/UseExistingDestinationFlow.tsx, src/components/ui/TableCells/ConnectionTypeCell/ConnectionTypeCell.tsx, src/components/ui/Tables/DestinationsTable/DestinationsTable.tsx, src/components/ui/Tables/PipelineTable/PipelineTable.tsx, src/components/ui/Tables/PipelinesTable/PipelinesTable.tsx, src/components/ui/Tables/SourcesTable/SourcesTable.tsx
Because
- #260
- #258
- #257
This commit
- Fix ConnectorTypeCell not showing correct connector icon (close #260)
- Display the destination icon when the user selects the existing destination (close #258)
- Fix destination configuration display wrong destination definition title (close #257)
=> fix: fix various issues related to destination icons and displayed title

src/components/destination/ConfigureDestinationForm.tsx, src/components/source/ConfigureSourceForm.tsx, src/components/ui/Modals/DeleteResourceModal/DeleteResourceModal.tsx
Because
- #263 
This commit
- fix the missing destination deletion (close #263)
=> fix: fix the missing destination deletion

src/components/ui/TableCells/InstanceCell/InstanceInnerList.tsx
Because
- #261
This commit
- Add buffer into calculation of instance cell more item button
=> fix: add buffer into calculation of instance cell more item button

src/components/onboarding/OnboardingForm/OnboardingForm.tsx, src/pages/api/set-user-cookie.ts
Because
- #262
This commit
- fix cookie_token wrongly set issue, cause onboarding is not working (close #262)
=> fix: fix cookie_token wrongly set issue, cause onboarding is not working

integration-test/README.md, integration-test/onboarding.spec.ts, integration-test/source.spec.ts, src/components/ui/Modals/DeleteResourceModal/DeleteResourceModal.tsx, src/components/ui/Modals/ModalBase/ModalBase.tsx, src/components/ui/StateLabel.tsx
Because
- #270 
This commit
- Implement source integration test
=> feat: Implement source integration test

integration-test/model.spec.ts, integration-test/onboarding.spec.ts, integration-test/source.spec.ts, playwright.config.ts, src/components/model/ConfigureModelForm.tsx, src/components/model/CreateModelForm.tsx, src/components/ui/Modals/ModalBase/ModalBase.tsx, src/components/ui/ModelInstanceTaskLabel.tsx, src/pages/models/[id].tsx
Because
- #270
- We are improving the coverage of the integration test
This commit
- Implement huggingface, github, local's integration test
=> feat: add model integration test - huggingface, github, local

src/components/destination/ConfigureDestinationForm.tsx, src/components/ui/TableCells/InstanceCell/InstanceInnerList.tsx
Because
- #261
This commit
- Fix instance cell not refresh issue (close #261 )
=> fix: fix instance cell not refresh issue

integration-test/destination.spec.ts, integration-test/model.spec.ts
Because
- #270
This commit
- Add the destination integration test
=> feat: add the destination integration test

.eslintrc.js, .gitignore, integration-test/README.md, integration-test/common/connector.ts, integration-test/common/mgmt.ts, integration-test/common/model.ts, integration-test/destination.spec.ts, integration-test/helper/global-setup.ts, integration-test/helper/index.ts, integration-test/model.spec.ts, integration-test/pipeline.spec.ts, integration-test/source.spec.ts, package.json, playwright.config.ts, pnpm-lock.yaml, src/components/model/CreateModelForm.tsx, src/components/pipeline/CreatePipelineForm/CreatePipelineForm.tsx, src/components/pipeline/CreatePipelineForm/SetupModelStep/CreateNewModelInstanceFlow.tsx, src/components/pipeline/CreatePipelineForm/SetupModelStep/UseExistingModeInstancelFlow.tsx, src/components/pipeline/CreatePipelineForm/SetupPipelineDetailsStep/SetupPipelineDetailsStep.tsx, src/components/ui/TableCells/InstanceCell/InstanceInnerList.tsx, src/services/mgmt/useTrackingToken.ts
Because
- #270 
This commit
- Finish integration-test and make it stable
=> feat: Finish integration test and make it stable

integration-test/onboarding.spec.ts, src/lib/cookie.ts, src/pages/_app.tsx, src/pages/api/set-user-cookie.ts
Because
- #283 
This commit
- fix set-cookie API route issue due to the wrong domain name (close #283)
=> fix: fix set-cookie api route issue due to wrong domain name

integration-test/pipeline.spec.ts, src/lib/instill/model/actions.ts, src/lib/instill/model/mutations.ts, src/lib/instill/pipeline/actions.ts
Because
- #286
This commit
- Update console request URL according to new protobuf (close #286)
=> feat: update console request URL according to new protobuf

src/components/ui/TableCells/ConnectionTypeCell/ConnectionTypeCell.tsx, src/components/ui/TableCells/InstanceCell/InstanceCell.tsx, src/components/ui/TableCells/ModeCell/ModeCell.tsx, src/components/ui/TableCells/ModelDefinitionCell/ModelDefinitionCell.tsx, src/components/ui/TableCells/ModelsCell/ModelsCell.tsx
Related issue - #288. Our elements in every table are not consistent. This PR fixes this issue. (close #288)
=> feat: unify the gap between elements in every table

.github/workflows/add-issue-to-prj.yml, .github/workflows/add-pr-to-prj.yml, src/components/destination/ConfigureDestinationForm.tsx, src/components/model/ConfigureModelForm.tsx, src/components/model/CreateModelForm.tsx, src/components/onboarding/OnboardingForm/OnboardingForm.tsx, src/components/pipeline/ConfigurePipelineForm.tsx, src/components/source/ConfigureSourceForm.tsx, src/components/source/CreateSourceForm.tsx, src/pages/models/[id].tsx, src/pages/pipelines/[id].tsx, src/pages/sources/[id].tsx, src/services/pipeline/useUpdatePipeline.ts
Because
- The Formik library has lots of overheads
This commit
- Deprecate Formik 
- We still need to deprecate multi-step form in the future
=> refactor: deprecate create model formik

integration-test/common/mgmt.ts, integration-test/onboarding.spec.ts, package.json, pnpm-lock.yaml, src/components/destination/ConfigureDestinationForm.tsx, src/components/formik/FormikField/StatefulToggleField/StatefulToggleField.tsx, src/components/model/ConfigureModelForm.tsx, src/components/model/ConfigureModelInstanceForm.tsx, src/components/model/CreateModelForm.tsx, src/components/pipeline/ConfigurePipelineForm.tsx, src/components/source/ConfigureSourceForm.tsx, src/components/ui/ChangeResourceStateButton.tsx, src/components/ui/Modals/DeleteResourceModal/DeleteResourceModal.tsx, src/lib/instill/model/actions.ts, src/lib/instill/model/queries.ts, src/lib/instill/types.ts, src/services/model/useDeployModelInstance.ts, src/services/model/useUnDeployModelInstance.ts
Because
- We need to support model-backend long run operation (#305)
This commit
- Adapt long run operation request and response
- Adjust e2e test 
- Add reminder to educate our user when they deploy and undeploy model
- close #305
=> feat: support model-backend async long run operation

integration-test/common/model.ts, integration-test/helper/global-teardown.ts, integration-test/model-artivc.spec.ts, integration-test/model-github.spec.ts, integration-test/model-huggingface.spec.ts, integration-test/model-local.spec.ts, integration-test/pipeline-async.spec.ts, integration-test/pipeline-sync.spec.ts
Because
- There has a issue when teardown the test suite
This commit
- Fix the above issue
=> feat: update e2e test

integration-test/common/mgmt.ts, src/components/onboarding/OnboardingForm/OnboardingForm.tsx, src/lib/instill/mgmt/mocks.ts, src/lib/instill/mgmt/mutations.ts, src/lib/instill/mgmt/queries.ts, src/lib/instill/mgmt/types.ts, src/pages/onboarding.tsx, src/services/mgmt/useTrackingToken.ts
Because
- mgmt-backend and protobuf had been updated
This commit
- adapt new mgmt backend and protobuf
=> feat: adapt new mgmt backend and protobuf

src/services/mgmt/useUpdateUser.ts, src/services/mgmt/useUser.ts
Because
- update user had some bug
This commit
- fix update user bug
=> fix: fix update user bug

.env, Dockerfile
Because
- env file configuration is wrong
This commit
- fix env file configuration
=> fix: fix env file

README.md, integration-test/common/model.ts, integration-test/common/pipeline.ts, package.json
Because
- #353
This commit
- turn off test related to long running operation
=> feat: turn off test related to long running operation

README.md, integration-test/README.md, integration-test/common/model.ts, integration-test/common/pipeline.ts, integration-test/destination-sync.spec.ts, integration-test/model-artivc.spec.ts, integration-test/model-github.spec.ts, integration-test/model-huggingface.spec.ts, integration-test/model-local.spec.ts, integration-test/pipeline-async.spec.ts, integration-test/pipeline-sync.spec.ts
Because
- #353
This commit
- Further disable tests
=> feat: update tests to skip long-running operation related tests

src/lib/markdown/template/pipeline-text-generation.mdx, src/lib/markdown/template/pipeline-text-to-image.mdx
Because
- the Text Generation task trigger snippet is incorrect
This commit
- refactor the trigger code for the Text to Image task to generate better images
- fix the trigger code for the Text Generation task
=> fix: refactor the trigger codes

src/components/onboarding/OnboardingForm/OnboardingForm.tsx, src/components/ui/Tables/ModelsTable.tsx
Because
- The cookie won't be set when the vdp had user in db
This commit
- fix onboarding issue when vdp had user in db
=> fix: fix onboarding issue when vdp had user in db

src/components/onboarding/OnboardingForm/OnboardingForm.tsx
Because
- update token no matter db had user or not
This commit
- update token no matter db had user or not
=> fix: update token no matter db had user or not

.env, integration-test/destination-async.spec.ts, integration-test/source.spec.ts, package.json, pnpm-lock.yaml, src/pages/destinations/[id].tsx, src/pages/destinations/create.tsx, src/pages/destinations/index.tsx, src/pages/models/[id].tsx, src/pages/models/create.tsx, src/pages/models/index.tsx, src/pages/pipelines/[id].tsx, src/pages/pipelines/create.tsx, src/pages/pipelines/index.tsx, src/pages/sources/[id].tsx, src/pages/sources/create.tsx, src/pages/sources/index.tsx
Because
- we use controller to control the state of resources
This commit
- adapt controller state
=> feat: adapt controller state

package.json, pnpm-lock.yaml, src/pages/models/[id].tsx, src/pages/pipelines/[id].tsx
Because
- the resource toggle button should be disabled when NEXT_PUBLIC_DISABLE_CREATE_UPDATE_DELETE_RESOURCE=false
This commit
-  fix toggle resource button is not disabled
=> fix: fix toggle resource button is not disabled

src/components/OnboardingForm.tsx
Because
- We had changed default user id
This commit
- fix default user id
=> fix: fix default user id

.env, src/pages/_app.tsx
Because
- console edition is wrong
This commit
- fix console edition
=> fix: [INS-463] fix console edition

package.json, pnpm-lock.yaml, src/pages/destinations/[id].tsx, src/pages/destinations/index.tsx, src/pages/models/[id].tsx, src/pages/models/index.tsx, src/pages/pipelines/[id].tsx, src/pages/pipelines/index.tsx, src/pages/sources/[id].tsx, src/pages/sources/index.tsx
Because
- we have new design related to model-backend
This commit
- update logic related to create model
=> feat: update logic related to create model

integration-test/onboarding.spec.ts, src/components/OnboardingForm.tsx
Because
- #407
This commit
- fix bad user experience at Onboarding page
- close #407
- Co-authored-by: @iamnamananand996
=> fix: fix bad user experience at Onboarding page

entrypoint-playwright.sh, integration-test/README.md, integration-test/common/connector.ts, integration-test/common/model.ts, integration-test/common/pipeline.ts, integration-test/destination-async.spec.ts, integration-test/destination-sync.spec.ts, integration-test/helper/index.ts, integration-test/model-artivc.spec.ts, integration-test/model-general.spec.ts, integration-test/model-github.spec.ts, integration-test/onboarding.spec.ts, integration-test/pipeline-async.spec.ts, integration-test/pipeline-sync.spec.ts, integration-test/source.spec.ts
Because
- `expect(locator).toHaveCount(1)` is not stable
This commit
- use waitFor to stabilize tests
=> feat: use waitFor to stabilize tests

package.json, pnpm-lock.yaml, src/pages/destinations/[id].tsx, src/pages/models/[id].tsx, src/pages/sources/[id].tsx
Because
- we didn't correctly query the pipelines that use this resource
This commit
- fix not correctly query pipelines that use this resource
=> fix: [INS-805] fix not correctly query pipelines that use this resource

.github/workflows/integration-test.yml, package.json, pnpm-lock.yaml
Because
- We want to empower our user to test their connector's connection
This commit
- add test connector connection button
=> feat: add test connector connection button 

package.json, pnpm-lock.yaml, src/pages/destinations/[id].tsx, src/pages/destinations/create.tsx, src/pages/models/[id].tsx, src/pages/models/create.tsx, src/pages/pipelines/[id].tsx, src/pages/pipelines/create.tsx, src/pages/sources/[id].tsx, src/pages/sources/create.tsx
Because
- create-source page has memory leak
- Other form has minor interaction issue
This commit
- fix create-source page memory leak and other form issues
=> fix: fix create-source page memory leak and other form issues

.github/templates/webpack-diff-comment.md, release-please/config.json
Because
- release-please config is out-of-date
This commit
- fix release-please config
=> chore: fix release-please config

.env, .github/workflows/integration-test.yml, integration-test/destination-async.spec.ts, integration-test/helper/index.ts, package.json, pnpm-lock.yaml, scripts/docker-run-test.sh, scripts/docker-run.sh, src/pages/_app.tsx, src/pages/destinations/[id].tsx, src/pages/destinations/index.tsx, src/pages/pipelines/[id].tsx, src/pages/sources/[id].tsx, src/pages/sources/index.tsx
Because
- We are centralizing the connector endpoint 
This commit
- adapt the singular connector endpoint design
=> feat(core): adapt the singular connector endpoint design

integration-test/destination-async.spec.ts, integration-test/helper/index.ts, integration-test/integration-test.list.ts, playwright.config.ts
Because
- connector endpoint in e2e test is wrong
This commit
- fix wrong connector endpoint
=> fix: fix wrong connector endpoint

package.json, pnpm-lock.yaml, src/components/pipeline-builder/flow/Flow.tsx, src/components/pipeline-builder/flow/FlowControl.tsx, src/components/pipeline-builder/left-panel/LeftPanel.tsx, src/components/pipeline-builder/left-panel/SelectConnectorDefinitionDialog.tsx, src/components/pipeline-builder/right-panel/AIForm.tsx, src/components/pipeline-builder/right-panel/DestinationForm.tsx, src/components/pipeline-builder/right-panel/SourceForm.tsx, src/lib/pipeline-builder/createInitialGraphData.tsx, src/pages/pipelines/[id].tsx, src/stores/usePipelineBuilderStore.ts
Because
- User can update the configuration of the resources
This commit
- implement the resource configuration at the pipeline-builder right panel
=> feat(pipeline-builder): implement the resource configuration at the pipeline-builder right panel

package.json, pnpm-lock.yaml, src/components/pipeline-builder/flow/Flow.tsx, src/components/pipeline-builder/flow/FlowControl.tsx, src/components/pipeline-builder/index.ts, src/components/pipeline-builder/left-panel/LeftPanel.tsx, src/components/pipeline-builder/left-panel/SelectConnectorDefinitionDialog.tsx, src/components/pipeline-builder/left-sidebar/LeftSidebar.tsx, src/components/pipeline-builder/left-sidebar/index.ts, src/components/pipeline-builder/nodes/BlockchainNode.tsx, src/components/pipeline-builder/nodes/index.ts, src/components/pipeline-builder/right-panel/BlockchainForm.tsx, src/components/pipeline-builder/right-panel/DestinationForm.tsx, src/components/pipeline-builder/right-panel/RightPanel.tsx, src/lib/pipeline-builder/createInitialGraphData.tsx, src/pages/pipelines/[id].tsx
Because
- We will support direct creation of blockchain connector in pipeline-builder
This commit
- support blockchain in pipeline-builder
=> feat(pipeline-builder): support blockchain in pipeline-builder

src/components/Sidebar/Sidebar.tsx, src/components/cards/StatusCardsGroup.tsx, src/components/charts/LineChart.tsx, src/components/skeleton/Skeleton.tsx, src/components/skeleton/index.ts, src/pages/api/pipeline/queries.ts, src/pages/dashboard/index.tsx
Because
- Need to new API's for dashboard triggers
This commit
- API's for dashboard triggers
=> feat: namananand/ins 1077 api connection for dashboard triggers

src/components/pipeline-builder/flow/FlowControl.tsx, src/components/pipeline-builder/right-panel/PipelineForm.tsx, src/pages/_app.tsx, src/pages/pipelines/[id].tsx
Because
- Rename is causing lots of issue in the pipeline-builder, especially for route changing event
This commit
-  fix multiple pipeline-builder flow issues related to rename
=> fix(pipeline-builder): fix multiple pipeline-builder flow issues related to rename

src/components/pipeline-builder/flow/Flow.tsx, src/components/pipeline-builder/flow/FlowControl.tsx, src/components/pipeline-builder/right-panel/AIForm.tsx, src/lib/pipeline-builder/constructPipelineRecipe.tsx, src/lib/pipeline-builder/createGraphLayout.tsx, src/lib/pipeline-builder/createInitialGraphData.tsx, src/lib/pipeline-builder/parseDependencyComponents.ts, src/pages/pipelines/[id].tsx
Because
- We need to support creating complex pipeline DAG
This commit
- support complex DAG in pipeline-builder
=> feat(pipeline-builder): support complex DAG in pipeline-builder

package.json, pnpm-lock.yaml, src/components/pipeline-builder/PipelineNameForm.tsx, src/components/pipeline-builder/flow/Flow.tsx, src/components/pipeline-builder/flow/FlowControl.tsx
Because
- activate pipeline button will always show activate
This commit
- fix activate pipeline button will always show activate
=> fix(pipeline-builder): fix activate pipeline button will always show activate

package.json, pnpm-lock.yaml, tailwind.config.js
Because
- We had fixed multiple bugs in cortex
This commit
-  fix pipeline-builder bugs
=> fix: fix pipeline-builder bugs

src/components/badge/Badge.tsx, src/components/cards/StatusCard.tsx, src/components/cards/StatusCardsGroup.tsx, src/components/charts/LineChart.tsx, src/lib/dashboard/options.ts, src/lib/dashboard/utils.ts, src/pages/dashboard/index.tsx, src/types/dashboard.ts
Because
- we need percentage comparison mechanism for completed and error on card
This commit
- percentage comparison mechanism for completed and error on card
=> feat: namananand/ins 1157 percentage comparison mechanism for completed and error

package.json, pnpm-lock.yaml
Because
- We are going to support more model
This commit
- support Stability AI SDXL model
=> feat: support Stability AI SDXL model

src/pages/model-hub/[id].tsx
Because
- accidentally query pipeline in MDL
This commit
- fix accidentally query pipeline in MDL
=> fix: fix accidentally query pipeline in MDL

src/components/Sidebar/Sidebar.tsx
Because
- sidebar menu is miss aligned
This commit
- sidebar menu css fix
=> fix: sidebar css fix

package.json, pnpm-lock.yaml, src/pages/model-hub/[id].tsx
Because
- AI/Blockchain form has disabled field issue
This commit
- bump cortex version to fix disabled field issue
=> fix: bump cortex version to fix disabled field issue

src/pages/_app.tsx, src/pages/pipelines/index.tsx
Because
- we have a pipeline builder render bug
This commit
- pipeline builder render bug
=> fix: Namananand/ins 1363 pipeline builder render bug

pnpm-lock.yaml, src/components/AIsTable.tsx, src/components/table/AITablePlaceholder.tsx, src/components/table/TableCell.tsx, src/lib/table/index.ts, src/lib/table/utils.ts, src/pages/ais/index.tsx
Because
- we need to update AI model table with new design
This commit
- updated AI model table with new design
=> feat: namananand/ins 1352 update AI model table with new design

src/components/BlockchainsTable.tsx, src/components/table/BlockchainTablePlaceholder.tsx, src/components/table/PlaceholderSVG.tsx, src/pages/blockchains/index.tsx
Because
-  we need new blockchain table design
This commit
- new blockchain table design
=> feat: blockchain table

src/components/DestinationsTable.tsx, src/pages/destinations/index.tsx
Because
- destination table with new design
This commit
- destination table with new design
=> feat: namananand/ins 1354 update destination table with new design

src/components/SourcesTable.tsx, src/pages/pipelines/index.tsx, src/pages/sources/index.tsx
Because
- update source table with new design
This commit
- source table with new design
=> feat: namananand/ins 1353 update source table with new design

src/components/BlockchainsTable.tsx, src/components/PipelinesTable.tsx, src/pages/blockchains/create.tsx, src/pages/pipelines/index.tsx
Because
- we need to update pipeline table with new design
This commit
- update pipeline table with new design
=> feat: namananand/ins 1351 update pipeline table with new design

integration-test/destination-async.spec.ts, integration-test/destination-sync.spec.ts, integration-test/helper/index.ts, integration-test/source.spec.ts, src/components/Sidebar/PipelineCollapsible.tsx, src/pages/data/[id].tsx, src/pages/data/create.tsx, src/pages/data/index.tsx, src/pages/operators/[id].tsx, src/pages/operators/create.tsx, src/pages/operators/index.tsx, src/pages/pipelines/create.tsx
Because
- we need to update sidebar with new component names and folders
This commit
- updated sidebar component names and folders
=> feat: update sidebar with new component names and folders

package.json, pnpm-lock.yaml, src/components/CreateSourceForm.tsx, src/components/SourcesTable.tsx, src/pages/operators/create.tsx, src/pages/operators/index.tsx
Because
- update table for operator api response
This commit
- update table for operator api response
=> feat: Namananand/ins 1445 update table for operator api response

package.json, pnpm-lock.yaml, src/pages/pipelines/[id].tsx
Because
- create AI form update
This commit
- create AI form update
=> fix: create AI form update

package.json, pnpm-lock.yaml, src/pages/pipelines/[id].tsx
Because
- support audios node
This commit
- support audios node
=> chore: support audios node

package.json, pnpm-lock.yaml
Because
- small issue for the pipeline component dependency
This commit
- small issue for the pipeline component dependency
=> chore: namananand/ins 1467 small issue for the pipeline component dependency

integration-test/source.spec.ts, package.json, pnpm-lock.yaml, src/pages/data/[id].tsx, src/pages/operators/[id].tsx, src/pages/operators/create.tsx
Because
- bump versions
This commit
- bump versions
=> chore: bump versions

package.json, pnpm-lock.yaml, src/components/DashboardPipelinesTable.tsx, src/lib/dashboard/index.ts, src/lib/dashboard/triggers.ts, src/lib/dashboard/utils.ts, src/pages/dashboard/index.tsx
Because
- integrate new table data api to dashboard pipelines
This commit
- integrate new table data api to dashboard pipelines
=> feat: Namananand/ins 1488 integrate new table data api to dashboard pipelines

package.json, pnpm-lock.yaml, src/components/InputType.tsx, src/pipeline-builder/StartNode.tsx
Because
- start operator form changes
This commit
- start operator form changes
=> feat: start operator form changes

package.json, pnpm-lock.yaml, src/components/Combobox.tsx, src/components/index.ts, src/pipeline-builder/FlowControl.tsx
Because
- add dropdown fro the ai and data connectors
This commit
- add dropdown fro the ai and data connectors
=> feat: namananand/ins 1526 add dropdown for the ai and data connectors

package.json, pnpm-lock.yaml, src/pages/ais/[id].tsx, src/pages/ais/index.tsx, src/pages/blockchains/[id].tsx, src/pages/blockchains/index.tsx, src/pages/data/[id].tsx, src/pages/data/index.tsx, src/pages/operators/[id].tsx, src/pages/operators/index.tsx, src/pages/pipelines/index.tsx
Because
- update tables access token props
This commit
- update tables access token props
=> feat: update tables access token props

src/pipeline-builder/EndNode.tsx, src/pipeline-builder/StartNode.tsx
Because
- add end operator form
This commit
- add end operator form
=> feat: add end operator form

package.json, pnpm-lock.yaml, src/pages/pipelines/[id].tsx, src/pipeline-builder/AIForm.tsx, src/pipeline-builder/BlockchainForm.tsx, src/pipeline-builder/Flow.tsx, src/pipeline-builder/FlowControl.tsx, src/pipeline-builder/RightPanel.tsx, src/pipeline-builder/StartNode.tsx, src/pipeline-builder/StartNodeInputType.tsx, src/pipeline-builder/constructPipelineRecipe.tsx, src/pipeline-builder/createInitialGraphData.tsx, src/pipeline-builder/sdk.ts, src/pipeline-builder/type.ts
Because
- We need the new start operator to indicate the input
This commit
-  Implement start operator logic in new pipeline-builder
=> feat: Implement start operator logic in new pipeline-builder

src/pages/pipelines/[id].tsx, src/pipeline-builder/EndNode.tsx, src/pipeline-builder/Flow.tsx, src/pipeline-builder/StartNode.tsx, src/pipeline-builder/createInitialGraphData.tsx, src/pipeline-builder/type.ts
Because
- We will have new pipeline builder
This commit
- implement the end operator node's logic
=> feat: implement the end operator node's logic

src/pages/pipelines/[id].tsx, src/pipeline-builder/FlowControl.tsx, src/pipeline-builder/PipelineNameForm.tsx
Because
- We are revamping our pipeline builder
This commit
- add new pipeline builder name editor
=> feat: add new pipeline builder name editor

src/components/Topbar.tsx, src/pages/dashboard/index.tsx, src/pages/dashboard/pipeline/[id].tsx, src/pages/model-hub/[id].tsx, src/pages/model-hub/index.tsx, src/pages/pipelines/[id].tsx, src/pages/pipelines/create.tsx, src/pages/pipelines/index.tsx, src/pages/resources/index.tsx, src/pipeline-builder/Flow.tsx, src/pipeline-builder/components/ConnectorNode.tsx, src/pipeline-builder/components/EndNode.tsx, src/pipeline-builder/components/PipelineNameForm.tsx, src/pipeline-builder/components/StartNode.tsx
Because
- We move to lighter color
This commit
- update pipeline-builder color
=> feat: update pipeline-builder color

src/pages/model-hub/create.tsx, src/pages/onboarding.tsx
Because
- pages not correctly passing Topbar props 
This commit
- fix Pages not correctly passing Topbar props
=> fix: fix Pages not correctly passing Topbar props

package.json, pnpm-lock.yaml
Because
- We need newer toolkit version
This commit
- bump up toolkit version
=> feat: bump up toolkit version 

package.json, pnpm-lock.yaml, src/pages/resources/index.tsx, src/pipeline-builder/components/AddConnectorResourceDialog.tsx
Because
- We need a way for user to create resource under /resources page
This commit
- add create resource dialog into /resources page
=> feat: add create resource dialog into /resources page

package.json, pnpm-lock.yaml, src/components/ResourcesTable.tsx, src/components/index.ts, src/pages/pipelines/[id].tsx, src/pages/pipelines/index.tsx, src/pages/resources/[id].tsx, src/pages/resources/index.tsx, src/pipeline-builder/components/AIResourceForm.tsx, src/pipeline-builder/components/AddConnectorResourceDialog.tsx, src/pipeline-builder/components/BlockchainResourceForm.tsx, src/pipeline-builder/components/DataResourceForm.tsx, src/pipeline-builder/components/PipelineNameForm.tsx, src/pipeline-builder/components/StartNode.tsx, src/pipeline-builder/lib/index.ts, src/pipeline-builder/lib/recursiveReplaceTargetValue.ts, src/pipeline-builder/usePipelineBuilderStore.ts
Because
- We need resource details page
This commit
- add /resources/rid page
=> feat: add /resources/rid page

package.json, pnpm-lock.yaml, src/pages/model-hub/index.tsx, src/pipeline-builder/FlowControl.tsx, src/pipeline-builder/components/ConnectorNode/ConnectorNode.tsx, src/pipeline-builder/components/EndNode.tsx, src/pipeline-builder/components/StartNode.tsx, src/pipeline-builder/components/TriggerPipelineSnippetModal.tsx, src/pipeline-builder/components/triggerPipelineSnippets.ts, src/pipeline-builder/lib/composePipelineInputSnippet.ts
Because
- We want to dynamically generate pipeline trigger snippet
This commit
- update pipeline trigger snippet
=> feat: update pipeline trigger snippet

src/components/Topbar.tsx, src/pages/pipelines/[id].tsx
Because
- We want to make topbar consistent across pages
This commit
- update topbar color
=> feat: update topbar color

package.json, pnpm-lock.yaml
Because
- Data connector node has issue when edit input
This commit
- fix data connector issue
=> fix: fix data source issue

package.json, pnpm-lock.yaml
Because
- pipeline trigger snippet has typo
This commit
- fix snippet typo
=> fix: fix snippet typo

public/images/auth-page-bg-strip.svg, src/components/AuthPageBase.tsx, src/components/LoginForm.tsx, src/components/index.ts, src/lib/auth/index.ts, src/lib/auth/withMiddlewareAuthRequired.ts, src/lib/index.ts, src/middleware.ts, src/pages/login.tsx
Because
- User without authenticated can not use the services
This commit
- Unauthenticated user will be block by our auth-guard
=> feat(auth): Unauthenticated user will be block by our auth-guard

package.json, pnpm-lock.yaml, src/pages/[entity]/pipelines/[id].tsx, src/pages/[entity]/resources/index.tsx
Because
- Increase the size of the node to increase the UX
This commit
- User will have 1.5x wider node under normal mode and 2.0 wider node under test mode
=> feat(pipeline-builder): User will have 1.5x wider node under normal mode and 2.0 wider node under test mode

package.json, pnpm-lock.yaml, src/pages/[entity]/pipelines/[id].tsx
Because
- Improve UX of pipeline-builder
This commit
- When user delete the whole name of pipeline, we will recover it back to previous name on blur or enter
=> feat(pipeline-builder): When user delete the whole name of pipeline, we will recover it back to previous name on blur or enter 

package.json, pnpm-lock.yaml
Because
- Improve UX and enable template engine
This commit
- user can have node with uncreated resource on pipeline builder
=> feat(pipeline-builder): user can have node with uncreated resource on pipeline builder

package.json, pnpm-lock.yaml, src/pages/_app.tsx
Because
- We need template to improve usability
This commit
- User can view staff pick templates on pipeline list page
=> feat(pipeline-builder): User can view staff pick templates on pipeline list page

.github/workflows/bundle-diff.yml, .github/workflows/images.yml, .github/workflows/unit-test.yml, package.json, pnpm-lock.yaml, scripts/checkPnpmOverrides.mjs
Because
- In case someone push a package with pnpm overrides
This commit
- better guard our repo from pnpm overrides
=> chore: better guard our repo from pnpm overrides

package.json, pnpm-lock.yaml
Because
- Empower user to share
This commit
- user can share their private pipeline with sharing a unique link
=> feat(pipeline-builder): user can share their private pipeline with sharing a unique link

package.json, pnpm-lock.yaml
Because
- empower user to share
This commit
- User can clone pipeline that is shared by other users
=> feat(pipeline-builder): User can clone pipeline that is shared by other users

package.json, pnpm-lock.yaml, src/components/ChangePasswordForm.tsx, src/components/OnboardingForm.tsx, src/pages/[entity]/model-hub/[id].tsx, src/pages/login.tsx
Because
- user should not be able to change password to default password
This commit
- fix a bug that user can change password to default password
=> fix: fix a bug that user can change password to default password

package.json, pnpm-lock.yaml
Because
- back to latest version button won't reset the field value on node
This commit
- fix back to latest version button won't reset the field value on node
=> fix: fix back to latest version button won't reset the field value on node

package.json, pnpm-lock.yaml
Because
- Improve UX
This commit
- user can have pre-formatted text field to better visualize the output
=> feat(pipeline-builder): user can have pre-formatted text field to better visualize the output

package.json, pnpm-lock.yaml
Because
- user can't have filtered existing resource when create resource on node
This commit
- fix user can't have filtered existing resource when create resource on node
=> fix: fix user can't have filtered existing resource when create resource on node

src/pages/onboarding.tsx
Because
- update title onboarding
This commit
- update title onboarding
=> chore: update title onboarding

package.json, pnpm-lock.yaml
Because
- path issue when get input/output schema for data connector
This commit
- fix path issue when get input/output schema for data connector
=> fix(pipeline-builder): fix path issue when get input/output schema for data connector

package.json, pnpm-lock.yaml
Because
- Improve UX
This commit
- User can better identify the process is still running when doing actions
=> feat(general): User can better identify the process is still running when doing actions

package.json, pnpm-lock.yaml
Because
- prepare 0.30.0 release
This commit
- prepare 0.30.0 release
=> chore: prepare 0.30.0 release

.github/workflows/images.yml, .github/workflows/integration-test.yml
Because
- fix images GA wrong condition
This commit
- fix images GA wrong condition
=> fix: fix images GA wrong condition

packages/toolkit/src/lib/vdp-sdk/helper/createInstillAxiosClient.ts, packages/toolkit/src/lib/vdp-sdk/metric/pipeline/queries.ts, packages/toolkit/src/lib/vdp-sdk/mgmt/actions.ts, packages/toolkit/src/lib/vdp-sdk/mgmt/mutations.ts, packages/toolkit/src/lib/vdp-sdk/mgmt/queries.ts
Because
- We will have a new project structure
This commit
- adapt new core structure among instill-ai project
=> chore: adapt new core structure among instill-ai project

.github/CONTRIBUTING.md, README.md
Because
- We are close to accept contribution on console
This commit
- update console README and contribution guideline
=> chore(docs): update console README and contribution guideline

apps/instill-form-playground/src/mocks/mock_nested_oneOf.json, apps/instill-form-playground/src/mocks/mock_simple.json, packages/toolkit/src/lib/type/index.ts, packages/toolkit/src/lib/type/zod.ts, packages/toolkit/src/lib/use-instill-form/transform/transformInstillJSONSchemaToZod.test.ts, packages/toolkit/src/lib/use-instill-form/transform/transformInstillJSONSchemaToZod.ts, packages/toolkit/src/lib/use-instill-form/type.ts, packages/toolkit/src/view/pipeline-builder/use-node-input-fields/useStartOperatorTestModeInputForm.tsx
Because
- Improve UX
This commit
- User can have fine-grained field level error message when input the reference/template
=> feat(auto-form): User can have fine-grained field level error message when input the reference/template

packages/design-system/src/new-ui/Toast/use-toast.tsx
Because
- Improve DX
This commit
- expose Toast related function return types
=> chore(design-system): expose Toast related function return types

.github/CONTRIBUTING.md, packages/toolkit/src/lib/index.ts, packages/toolkit/src/lib/toastInstillError.ts, packages/toolkit/src/lib/useResourceAdditionalForm.tsx, packages/toolkit/src/view/ai/AIResourceAutoForm.tsx, packages/toolkit/src/view/pipeline-builder/RightPanel.tsx, packages/toolkit/src/view/pipeline-builder/components/CreateResourceDialog.tsx, packages/toolkit/src/view/resource/AddConnectorResourceDialog.tsx, packages/toolkit/src/view/resource/ResourceSettingPageMainView.tsx
Because
- support auto-form-generation
This commit
- adapt auto-form on AI related forms
=> feat(auto-form-generation): adapt auto-form-generation on AI related forms

packages/toolkit/src/view/ai/AIComponentAutoForm.tsx, packages/toolkit/src/view/ai/index.ts, packages/toolkit/src/view/blockchain/BlockchainComponentAutoForm.tsx, packages/toolkit/src/view/blockchain/BlockchainResourceAutoForm.tsx, packages/toolkit/src/view/blockchain/index.ts, packages/toolkit/src/view/pipeline-builder/RightPanel.tsx, packages/toolkit/src/view/pipeline-builder/components/CreateResourceDialog.tsx, packages/toolkit/src/view/pipeline-builder/components/SelectConnectorResourceDialog.tsx, packages/toolkit/src/view/resource/AddConnectorResourceDialog.tsx, packages/toolkit/src/view/resource/ResourceComponentForm.tsx, packages/toolkit/src/view/resource/ResourceResourceForm.tsx, packages/toolkit/src/view/resource/ResourceSettingPageMainView.tsx, packages/toolkit/src/view/resource/index.ts
Because
- Improve UX
This commit
- support auto-form-generation on blockchain related forms
=> feat(auto-form-generation): support auto-form-generation on blockchain related forms

packages/toolkit/src/lib/use-instill-form/transform/transformInstillJSONSchemaToFormTree.ts
Because
- correctly parse field's type from anyOf
This commit
- correctly parse field's type from anyOf
=> feat(auto-gen-form): correctly parse field's type from anyOf

apps/instill-form-playground/src/mocks/mock_nested_oneOf.json, apps/instill-form-playground/src/mocks/mock_simple_array.json, packages/toolkit/src/lib/use-instill-form/components/OneOfConditionField.tsx, packages/toolkit/src/lib/use-instill-form/components/TextAreaField.tsx, packages/toolkit/src/lib/use-instill-form/components/TextField.tsx, packages/toolkit/src/lib/use-instill-form/pick/pickFieldComponentFromInstillFormTree.tsx, packages/toolkit/src/lib/use-instill-form/transform/transformInstillFormTreeToDefaultValue.test.ts, packages/toolkit/src/lib/use-instill-form/transform/transformInstillFormTreeToDefaultValue.ts, packages/toolkit/src/lib/use-instill-form/transform/transformInstillJSONSchemaToFormTree.test.ts, packages/toolkit/src/lib/use-instill-form/useInstillForm.tsx, packages/toolkit/src/view/pipeline-builder/components/SharePipelineDialog.tsx, packages/toolkit/src/view/pipeline-builder/components/connector-node/InputPropertyItem.tsx, packages/toolkit/src/view/pipeline/PipelineBuilderMainView.tsx, packages/toolkit/src/view/pipeline/PipelineListPageMainView.tsx
Because
- correctly display nested fields
This commit
- correctly display nested fields
=> feat(auto-gen-form): correctly display nested fields

packages/toolkit/src/lib/use-instill-form/transform/transformInstillFormTreeToInitialSelectedCondition.test.ts, packages/toolkit/src/lib/use-instill-form/transform/transformInstillFormTreeToInitialSelectedCondition.ts, packages/toolkit/src/lib/use-instill-form/useInstillForm.tsx, packages/toolkit/src/view/blockchain/BlockchainComponentAutoForm.tsx, packages/toolkit/src/view/data/DataComponentAutoForm.tsx, packages/toolkit/src/view/data/index.ts, packages/toolkit/src/view/pipeline-builder/RightPanel.tsx
Because
- support auto-gen-form on data related forms
This commit
- support auto-gen-form on data related forms
=> feat(auto-gen-form): support auto-gen-form on data related forms

packages/toolkit/src/view/pipeline-builder/Flow.tsx, packages/toolkit/src/view/pipeline-builder/FlowControl.tsx, packages/toolkit/src/view/pipeline-builder/components/BackToLatestVersionTopBar.tsx, packages/toolkit/src/view/pipeline-builder/components/BottomBar.tsx, packages/toolkit/src/view/pipeline-builder/components/EndNode.tsx, packages/toolkit/src/view/pipeline-builder/components/ReleasePipelineModal.tsx, packages/toolkit/src/view/pipeline-builder/components/connector-node/ConnectorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/start-node/StartNode.tsx, packages/toolkit/src/view/pipeline-builder/components/start-node/StartNodeInputForm.tsx, packages/toolkit/src/view/pipeline-builder/components/triggerPipelineSnippets.ts, packages/toolkit/src/view/pipeline-builder/lib/useSortedReleases.tsx, packages/toolkit/src/view/pipeline-builder/usePipelineBuilderStore.ts, packages/toolkit/src/view/pipeline/PipelineBuilderMainView.tsx
Because
- fix pipeline released version not correctly guard, the trigger endpoint not correctly generate
This commit
- fix pipeline released version not correctly guard, the trigger endpoint not correctly generate
- close https://github.com/instill-ai/community/issues/449
- close https://github.com/instill-ai/community/issues/448
=> fix(version-control): fix pipeline released version not correctly guard, the trigger endpoint not correctly generate

apps/console/src/pages/_app.tsx, packages/toolkit/src/view/pipeline-builder/components/EndNode.tsx, packages/toolkit/src/view/pipeline-builder/components/connector-node/ConnectorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/start-node/StartNode.tsx, packages/toolkit/src/view/pipeline-builder/use-node-input-fields/ImageField.tsx, packages/toolkit/src/view/pipeline-builder/use-node-input-fields/ImagesField.tsx, packages/toolkit/src/view/pipeline-builder/use-node-input-fields/TextField.tsx, packages/toolkit/src/view/pipeline-builder/use-node-input-fields/TextsField.tsx, packages/toolkit/src/view/resource/ResourcesTable.tsx
Because
- user can have more unified nodes width across pipeline builder
This commit
- user can have more unified nodes width across pipeline builder
=> feat(pipeline-builder): user can have more unified nodes width across pipeline builder

packages/design-system/src/new-ui/Icons/DotsHorizontal.tsx, packages/design-system/src/new-ui/Icons/index.ts
Because
- add DotsHorizontal icon
This commit
- add DotsHorizontal icon
=> chore: add DotsHorizontal icon

packages/toolkit/src/view/pipeline-builder/components/connector-node/ConnectorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/connector-node/ConnectorNodeControlPanel.tsx
Because
- User can have a cleaner control dropdown on pipeline-builder's component
This commit
- User can have a cleaner control dropdown on pipeline-builder's component
=> feat(pipeline-builder): User can have a cleaner control dropdown on pipeline-builder's component

packages/design-system/src/new-ui/Icons/Minus.tsx, packages/design-system/src/new-ui/Icons/index.ts
Because
- add minus icon
This commit
- add minus icon
=> chore(design-system): add minus icon

packages/toolkit/src/view/pipeline-builder/components/connector-node/ConnectorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/connector-node/ConnectorNodeControlPanel.tsx
Because
- User can collapse/expand the component
This commit
- User can collapse/expand the component
=> feat(pipeline-builder): User can collapse/expand the component

packages/toolkit/src/view/pipeline-builder/components/SharePipelineDialog.tsx, packages/toolkit/src/view/pipeline/PipelineBuilderMainView.tsx
Because
- fix console not correctly displayed shared pipeline
This commit
- fix console not correctly displayed shared pipeline
=> fix(pipeline-builder): fix console not correctly displayed shared pipeline

README.md, apps/console/src/styles/global.css, packages/toolkit/src/components/PageBase.tsx, packages/toolkit/src/components/Topbar.tsx, packages/toolkit/src/view/pipeline-builder/components/EndNode.tsx, packages/toolkit/src/view/pipeline-builder/components/connector-node/ConnectorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/connector-node/ConnectorNodeControlPanel.tsx, packages/toolkit/src/view/pipeline-builder/components/start-node/StartNode.tsx, packages/toolkit/src/view/pipeline-builder/lib/composeEdgesFromReferences.tsx, packages/toolkit/src/view/pipeline-builder/use-node-output-fields/AudioField.tsx, packages/toolkit/src/view/pipeline-builder/use-node-output-fields/AudiosField.tsx, packages/toolkit/src/view/pipeline-builder/use-node-output-fields/FieldRoot.tsx, packages/toolkit/src/view/pipeline-builder/use-node-output-fields/ImageField.tsx, packages/toolkit/src/view/pipeline-builder/use-node-output-fields/ImagesField.tsx, packages/toolkit/src/view/pipeline-builder/use-node-output-fields/NumberField.tsx, packages/toolkit/src/view/pipeline-builder/use-node-output-fields/NumbersField.tsx, packages/toolkit/src/view/pipeline-builder/use-node-output-fields/ObjectField.tsx, packages/toolkit/src/view/pipeline-builder/use-node-output-fields/ObjectsField.tsx, packages/toolkit/src/view/pipeline-builder/use-node-output-fields/TextField.tsx, packages/toolkit/src/view/pipeline-builder/use-node-output-fields/TextsField.tsx, packages/toolkit/src/view/pipeline-builder/use-node-output-fields/useEndOperatorTestModeOutputFields.tsx, packages/toolkit/src/view/pipeline/PipelineBuilderMainView.tsx
Because
- fix console not correctly recognize complicated reference
This commit
- fix console not correctly recognize complicated reference
=> fix(pipeline-builder): fix console not correctly recognize complicated reference

packages/toolkit/src/view/pipeline-builder/Flow.tsx
Because
- disable snap to grid
This commit
- disable snap to grid
=> chore: disable snap to grid

.github/workflows/integration-test.yml
Because
- we need to update the docker hub login
This commit
- update docker hub login
=> ci(workflow): update docker hub login

packages/toolkit/src/view/pipeline-builder/components/connector-node/ConnectorNode.tsx
Because
- fix a but that user can rename component ID to another existed component ID
This commit
- fix a but that user can rename component ID to another existed component ID
- close https://github.com/instill-ai/community/issues/468
=> fix(pipeline-builder): fix a but that user can rename component ID to another existed component ID

packages/toolkit/src/lib/vdp-sdk/model/mutations.ts
Because
- fix user can not create model with multipart form data 
This commit
- fix user can not create model with multipart form data
=> fix: fix user can not create model with multipart form data 

packages/toolkit/src/lib/use-instill-form/transform/transformInstillJSONSchemaToFormTree.ts, packages/toolkit/src/view/model/CreateModelForm.tsx
Because
- support ordering for auto-gen-form's fields
This commit
- support ordering for auto-gen-form's fields
=> feat(auto-gen-form): support ordering for auto-gen-form's fields

docs/instill-auto-form.md, packages/toolkit/src/lib/use-instill-form/pick/pickFieldComponentFromInstillFormTree.tsx, packages/toolkit/src/lib/use-instill-form/transform/transformInstillJSONSchemaToFormTree.test.ts, packages/toolkit/src/lib/use-instill-form/transform/transformInstillJSONSchemaToFormTree.ts, packages/toolkit/src/lib/use-instill-form/transform/transformInstillJSONSchemaToZod.test.ts, packages/toolkit/src/lib/use-instill-form/transform/transformInstillJSONSchemaToZod.ts, packages/toolkit/src/lib/use-instill-form/type.ts, packages/toolkit/src/lib/use-instill-form/useInstillForm.tsx, packages/toolkit/src/view/resource/ResourceComponentForm.tsx
Because
- expose props to hide specific fields
This commit
- expose props to hide specific fields
=> feat(auto-gen-form): expose props to hide specific fields

packages/toolkit/src/lib/index.ts, packages/toolkit/src/lib/use-instill-form/transform/transformInstillJSONSchemaToFormTree.test.ts, packages/toolkit/src/lib/use-instill-form/useInstillForm.tsx, packages/toolkit/src/lib/use-instill-store/smartHintSlice.ts, packages/toolkit/src/lib/use-instill-store/types.ts, packages/toolkit/src/lib/use-smart-hint/extractHintsFromConnectorComponentOutputFormTree.ts, packages/toolkit/src/lib/use-smart-hint/index.ts, packages/toolkit/src/lib/use-smart-hint/useSmartHint.ts, packages/toolkit/src/view/pipeline-builder/components/connector-node/InputProperties.tsx, packages/toolkit/src/view/pipeline-builder/components/connector-node/OutputProperties.tsx, packages/toolkit/src/view/pipeline-builder/lib/composePipelineInputSnippet.ts, packages/toolkit/src/view/pipeline-builder/lib/getConnectorInputOutputSchema.ts, packages/toolkit/src/view/pipeline-builder/lib/getPipelineInputOutputSchema.ts, packages/toolkit/src/view/pipeline-builder/lib/getPropertiesFromOpenAPISchema.ts, packages/toolkit/src/view/pipeline/PipelineBuilderMainView.tsx
Because
- Parse connector component to retrieve the smart hints and put them into central store
This commit
- Parse connector component to retrieve the smart hints and put them into central store
=> feat(smart-hint): Parse connector component to retrieve the smart hints and put them into central store

packages/toolkit/src/lib/dashboard/generateChartData.ts, packages/toolkit/src/lib/index.ts, packages/toolkit/src/lib/react-query-service/pipeline/useCreateUserPipelineRelease.ts, packages/toolkit/src/lib/store/useConfigureModelFormStore.ts, packages/toolkit/src/lib/toastInstillError.ts, packages/toolkit/src/lib/use-instill-form/components/OneOfConditionField.tsx, packages/toolkit/src/lib/usePipelineBuilderGraph.tsx, packages/toolkit/src/lib/vdp-sdk/pipeline/mutations.ts, packages/toolkit/src/lib/vdp-sdk/pipeline/types.ts, packages/toolkit/src/view/pipeline-builder/FlowControl.tsx, packages/toolkit/src/view/pipeline-builder/components/BackToLatestVersionTopBar.tsx, packages/toolkit/src/view/pipeline-builder/components/BottomBar.tsx, packages/toolkit/src/view/pipeline-builder/components/PipelineNameForm.tsx, packages/toolkit/src/view/pipeline-builder/components/template/StaffPickTemplates.tsx, packages/toolkit/src/view/pipeline-builder/lib/checkIsValidPosition.test.ts, packages/toolkit/src/view/pipeline-builder/lib/checkIsValidPosition.ts, packages/toolkit/src/view/pipeline-builder/lib/composePipelineMetadataFromNodes.test.ts, packages/toolkit/src/view/pipeline-builder/lib/composePipelineMetadataFromNodes.ts, packages/toolkit/src/view/pipeline-builder/lib/createInitialGraphData.tsx, packages/toolkit/src/view/pipeline-builder/lib/index.ts, packages/toolkit/src/view/pipeline-builder/type.ts, packages/toolkit/src/view/pipeline/PipelineBuilderMainView.tsx, packages/toolkit/src/view/pipeline/PipelinesTable.tsx
Because
- User can store their pipeline-builder layout 
This commit
- User can store their pipeline-builder layout
=> feat(pipeline-builder): User can store their pipeline-builder layout 

packages/toolkit/src/lib/use-instill-form/components/TextField.tsx, packages/toolkit/src/lib/use-smart-hint/index.ts, packages/toolkit/src/lib/use-smart-hint/transformStartOperatorMetadataToSmartHints.test.ts, packages/toolkit/src/lib/use-smart-hint/transformStartOperatorMetadataToSmartHints.ts, packages/toolkit/src/lib/use-smart-hint/useSmartHint.ts, packages/toolkit/src/lib/vdp-sdk/pipeline/types.ts, packages/toolkit/src/view/pipeline-builder/FlowControl.tsx, packages/toolkit/src/view/pipeline-builder/components/StartNodeInputType.tsx, packages/toolkit/src/view/pipeline-builder/components/start-node/StartNodeInputForm.tsx, packages/toolkit/src/view/pipeline-builder/lib/composeEdgesFromReferences.tsx, packages/toolkit/src/view/pipeline-builder/lib/templates.ts, packages/toolkit/src/view/pipeline-builder/use-node-input-fields/useStartOperatorTestModeInputForm.tsx, packages/toolkit/src/view/pipeline-builder/use-node-output-fields/useConnectorTestModeOutputFields.tsx, packages/toolkit/src/view/pipeline-builder/use-node-output-fields/useEndOperatorTestModeOutputFields.tsx
Because
- support smart hint
This commit
- adapt instillFormat in start operator metadata
=> feat(smart-hint): adapt instillFormat in start operator metadata

packages/toolkit/src/lib/use-instill-form/pick/index.ts, packages/toolkit/src/lib/use-instill-form/pick/pickComponentOutputFieldsFromInstillFormTree.tsx, packages/toolkit/src/lib/use-instill-form/useComponentOutputFields.tsx, packages/toolkit/src/view/pipeline-builder/components/EndNode.tsx, packages/toolkit/src/view/pipeline-builder/components/connector-node/OutputProperties.tsx
Because
- fix component output issue
This commit
- fix component output issue
=> fix(smart-hint): fix component output issue

packages/design-system/src/new-ui/ScrollArea/ScrollArea.tsx, packages/toolkit/src/lib/use-instill-form/components/regular/TextField.tsx, packages/toolkit/src/lib/use-instill-form/pick/pickRegularFieldsFromInstillFormTree.tsx, packages/toolkit/src/lib/use-instill-form/transform/transformInstillJSONSchemaToFormTree.ts, packages/toolkit/src/lib/use-instill-form/transform/transformInstillJSONSchemaToZod.test.ts, packages/toolkit/src/lib/use-instill-form/transform/transformInstillJSONSchemaToZod.ts, packages/toolkit/src/lib/use-instill-store/types.ts, packages/toolkit/src/lib/use-smart-hint/pickSmartHintsFromAcceptFormats.ts, packages/toolkit/src/lib/use-smart-hint/transformConnectorComponentFormTreeToSmartHints.test.ts, packages/toolkit/src/lib/use-smart-hint/transformConnectorComponentFormTreeToSmartHints.ts, packages/toolkit/src/lib/usePipelineBuilderGraph.tsx, packages/toolkit/src/lib/vdp-sdk/pipeline/types.ts, packages/toolkit/src/view/pipeline-builder/FlowControl.tsx, packages/toolkit/src/view/pipeline-builder/components/EndNode.tsx, packages/toolkit/src/view/pipeline-builder/components/StartNodeInputType.tsx, packages/toolkit/src/view/pipeline-builder/components/start-node/StartNodeInputForm.tsx, packages/toolkit/src/view/pipeline-builder/use-node-input-fields/useStartOperatorTestModeInputForm.tsx, packages/toolkit/src/view/pipeline/PipelineBuilderMainView.tsx
Because
- user can be hinted by the smart hint system
This commit
- user can be hinted by the smart hint system
=> feat(smart-hint): user can be hinted by the smart hint system

packages/toolkit/src/lib/use-instill-form/components/regular/TextField.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/SmartHintInfoCard.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/SmartHintList.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/TextArea.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/TextField.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/index.ts, packages/toolkit/src/lib/use-instill-form/components/smart-hint/onClickSmartHint.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/onInputChange.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/onInputKeydown.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/useFilteredHints.tsx, packages/toolkit/src/lib/use-instill-form/pick/pickRegularFieldsFromInstillFormTree.tsx, packages/toolkit/src/lib/use-instill-form/transform/transformInstillJSONSchemaToFormTree.ts, packages/toolkit/src/lib/use-instill-form/transform/transformInstillJSONSchemaToZod.ts, packages/toolkit/src/lib/use-instill-form/type.ts, packages/toolkit/src/lib/use-instill-form/useComponentOutputFields.tsx, packages/toolkit/src/lib/use-instill-form/useInstillForm.tsx, packages/toolkit/src/view/pipeline-builder/components/EndNode.tsx, packages/toolkit/src/view/resource/ResourceComponentForm.tsx
Because
- support textarea smart-hint
This commit
- support textarea smart-hint
=> feat(smart-hint): support textarea smart-hint

packages/toolkit/src/view/pipeline-builder/components/CreateResourceDialog.tsx, packages/toolkit/src/view/pipeline-builder/components/EmptyNode.tsx, packages/toolkit/src/view/pipeline-builder/components/SelectConnectorResourceDialog.tsx, packages/toolkit/src/view/pipeline-builder/components/connector-node/ConnectorNode.tsx, packages/toolkit/src/view/resource/AddConnectorResourceDialog.tsx
Because
- unify the term on the console and add scroll-area into dialog
This commit
- unify the term on the console and add scroll-area into dialog
=> feat: unify the term on the console and add scroll-area into dialog

apps/console/integration-test/common/mgmt.ts, apps/console/integration-test/helper/global-teardown.ts, apps/console/src/pages/api/set-user-cookie.ts, apps/instill-form-playground/src/pages/index.tsx, packages/design-system/src/ui/TextAreas/TextAreaBase/TextAreaBase.stories.tsx, packages/design-system/src/ui/UploadFileFields/BasicUploadFileField/BasicUploadFileField.stories.tsx, packages/design-tokens/src/buildTailwindPreset.ts, packages/toolkit/src/components/ImageWithFallback.tsx, packages/toolkit/src/lib/amplitude/helper.ts, packages/toolkit/src/lib/use-instill-form/components/regular/OneOfConditionField.tsx, packages/toolkit/src/lib/use-instill-form/pick/pickComponentOutputFieldsFromInstillFormTree.tsx, packages/toolkit/src/lib/use-instill-form/pick/pickRegularFieldsFromInstillFormTree.tsx, packages/toolkit/src/lib/use-instill-form/transform/recursivelyResetFormData.ts, packages/toolkit/src/lib/use-instill-form/transform/transformInstillJSONSchemaToFormTree.ts, packages/toolkit/src/lib/use-instill-form/useInstillForm.tsx, packages/toolkit/src/lib/usePipelineBuilderGraph.tsx, packages/toolkit/src/view/pipeline-builder/FlowControl.tsx, packages/toolkit/src/view/pipeline-builder/components/BackToLatestVersionTopBar.tsx, packages/toolkit/src/view/pipeline-builder/components/BottomBar.tsx, packages/toolkit/src/view/user-settings/billing-tab/BillingTab.tsx, scripts/checkPnpmOverrides.mjs
Because
- fix auto-gen form not correctly handle re-render issue
This commit
- fix auto-gen form not correctly handle re-render issue
=> fix(auto-gen-form): fix auto-gen form not correctly handle re-render issue

packages/toolkit/src/lib/use-instill-form/components/regular/OneOfConditionField.tsx, packages/toolkit/src/lib/use-instill-form/transform/recursivelyResetFormData.ts, packages/toolkit/src/lib/use-instill-form/transform/transformInstillFormTreeToDefaultValue.ts, packages/toolkit/src/lib/use-instill-form/useComponentOutputFields.tsx, packages/toolkit/src/lib/use-instill-form/useInstillForm.tsx, packages/toolkit/src/view/pipeline-builder/lib/recursiveParseToNum.ts
Because
- User can have better default value when they switch between different condition
This commit
- User can have better default value when they switch between different condition
=> feat(auto-gen-form): User can have better default value when they switch between different condition

packages/toolkit/src/lib/use-instill-form/components/component-output/AudioField.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output/AudiosField.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output/FieldRoot.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output/ImageField.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output/ImagesField.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output/NumberField.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output/NumbersField.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output/ObjectArrayField.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output/ObjectField.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output/ObjectsField.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output/TextField.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output/TextsField.tsx, packages/toolkit/src/lib/use-instill-form/pick/pickComponentOutputFieldsFromInstillFormTree.tsx, packages/toolkit/src/lib/use-instill-form/useComponentOutputFields.tsx, packages/toolkit/src/view/pipeline-builder/components/connector-node/OutputProperties.tsx, packages/toolkit/src/view/pipeline-builder/lib/getPipelineInputOutputSchema.ts
Because
- fix auto-gen-form not correctly handle objectArray issue
This commit
- fix auto-gen-form not correctly handle objectArray issue
=> fix(auto-gen-form): fix auto-gen-form not correctly handle objectArray issue

packages/toolkit/src/lib/use-instill-form/components/smart-hint/onClickSmartHint.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/onInputKeydown.tsx, packages/toolkit/src/lib/use-smart-hint/pickSmartHintsFromAcceptFormats.ts
Because
- fix smart hit can't correctly filter the hints
This commit
- fix smart hit can't correctly filter the hints
=> fix(smart-hint): fix smart hit can't correctly filter the hints

packages/toolkit/src/lib/use-instill-form/components/smart-hint/SmartHintInfoCard.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/SmartHintList.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/TextArea.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/TextField.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/onClickSmartHint.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/onInputChange.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/onInputKeydown.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/useFilteredHints.tsx, packages/toolkit/src/lib/use-instill-form/useInstillForm.tsx
Because
- user can have more tolerant smart hint session and auto enclose
This commit
- user can have more tolerant smart hint session and auto enclose
=> feat(smart-hint): user can have more tolerant smart hint session and auto enclose

packages/toolkit/src/lib/use-instill-form/components/smart-hint/SmartHintInfoCard.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/TextArea.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/TextField.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/useValidateReferenceAndTemplate.tsx, packages/toolkit/src/lib/use-instill-form/type.ts, packages/toolkit/src/view/pipeline-builder/components/connector-node/ConnectorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/connector-node/ConnectorNodeControlPanel.tsx
Because
- warn user about the not available reference or template
This commit
- warn user about the not available reference or template
=> feat(smart-hint): warn user about the not available reference or template

.github/workflows/integration-test.yml
Because
- fix GA integration-test model init issue
This commit
- fix GA integration-test model init issue
=> fix: fix GA integration-test model init issue

packages/toolkit/src/lib/use-instill-form/components/smart-hint/useValidateReferenceAndTemplate.tsx, packages/toolkit/src/view/pipeline-builder/components/SelectConnectorResourceDialog.tsx, packages/toolkit/src/view/pipeline-builder/components/connector-node/ConnectorIDTag.tsx, packages/toolkit/src/view/pipeline-builder/components/connector-node/ConnectorNode.tsx
Because
- fix typo and make smart hint validation tolerant more
This commit
- fix typo and make smart hint validation tolerant more
=> fix(smart-hint): fix typo and make smart hint validation tolerant more

packages/toolkit/src/view/pipeline-builder/components/EndNode.tsx
Because
- fix end component not picking the title as title in test mode
This commit
- fix end component not picking the title as title in test mode
=> fix(auto-gen-form): fix end component not picking the title as title in test mode

packages/toolkit/src/lib/utility/index.ts, packages/toolkit/src/lib/utility/validateComponentID.ts, packages/toolkit/src/view/pipeline-builder/components/EndNode.tsx, packages/toolkit/src/view/pipeline-builder/components/connector-node/ConnectorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/start-node/StartNodeInputForm.tsx
Because
- fix validate component ID's regex
This commit
- fix validate component ID's regex
=> fix(pipeline-builder): fix validate component ID's regex

apps/console/src/components/Topbar/Topbar.tsx, apps/console/src/components/Topbar/TopbarLink.tsx, apps/console/src/components/Topbar/index.ts, apps/console/src/components/index.ts, apps/console/src/pages/[entity]/connectors/[id].tsx, apps/console/src/pages/[entity]/connectors/index.tsx, apps/console/src/pages/[entity]/dashboard/index.tsx, apps/console/src/pages/[entity]/dashboard/pipeline/[id].tsx, apps/console/src/pages/[entity]/model-hub/[id].tsx, apps/console/src/pages/[entity]/model-hub/create.tsx, apps/console/src/pages/[entity]/model-hub/index.tsx, apps/console/src/pages/[entity]/pipelines/[id].tsx, apps/console/src/pages/[entity]/pipelines/create.tsx, apps/console/src/pages/[entity]/pipelines/index.tsx, apps/console/src/pages/onboarding.tsx, apps/console/src/styles/global.css, packages/toolkit/src/view/model/ModelHubListPageMainView.tsx, packages/toolkit/src/view/pipeline/PipelineListPageMainView.tsx
Because
- refactor sidebar and topbar
This commit
- refactor sidebar and topbar
=> chore: Namananand/ins 2592 refactor sidebar and topbar

apps/console/src/components/Topbar/Topbar.tsx, apps/console/src/pages/settings.tsx
Because
- implement user profile dropdown
This commit
- implement user profile dropdown
=> chore(user-profile): Namananand/ins 2593 implement user profile dropdown

packages/design-system/src/new-ui/Breadcrumb/Breadcrumb.stories.tsx, packages/design-system/src/new-ui/Breadcrumb/Breadcrumb.tsx, packages/design-system/src/new-ui/Breadcrumb/index.ts, packages/design-system/src/new-ui/index.ts
Because
- add Breadcrumb component
This commit
- add Breadcrumb component
=> chore(design-system): add Breadcrumb component

packages/design-system/src/new-ui/ComplicateIcons/ComplicateIcons.stories.tsx, packages/design-system/src/new-ui/ComplicateIcons/Drag.tsx, packages/design-system/src/new-ui/ComplicateIcons/index.ts
Because
- add DragIcon
This commit
- add DragIcon
=> chore: add DragIcon

apps/console/src/components/Topbar/Topbar.tsx, apps/console/src/pages/[entity]/profile/index.tsx
Because
- user profile page UI
This commit
- user profile page UI
=> chore(user-profile): Namananand/ins 2594 user profile page UI

packages/eslint-config-cortex/index.js, packages/toolkit/src/view/pipeline-builder/components/end-operator-node/EndOperatorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/end-operator-node/UserDefinedFieldItem.tsx
Because
-  User can have better end component node design
This commit
-  User can have better end component node design
=> feat(pipeline-builder): User can have better end component node design

apps/console/src/pages/settings/account.tsx, apps/console/src/pages/settings/api-tokens.tsx, apps/console/src/pages/settings/billings.tsx, apps/console/src/pages/settings/index.tsx, apps/console/src/pages/settings/organizations.tsx, packages/toolkit/src/view/index.ts, packages/toolkit/src/view/organizations/CreateOrganizationDialog.tsx, packages/toolkit/src/view/organizations/OrganizationTab.tsx, packages/toolkit/src/view/organizations/index.ts, packages/toolkit/src/view/user-settings/TabBase.tsx
Because
- user organization tab
This commit
- user organization tab
=> chore(user-profile): user organization tab

packages/design-system/src/new-ui/Icons/FilePlus01.tsx, packages/design-system/src/new-ui/Icons/index.ts
Because
- add FilePlus01 icon
This commit
- add FilePlus01 icon
=> chore: add FilePlus01 icon

apps/console/src/components/OrganizationSidebar/OrganizationSidebar.tsx, apps/console/src/components/OrganizationSidebar/OrganizationSidebarLink.tsx, apps/console/src/components/OrganizationSidebar/index.tsx, apps/console/src/components/index.ts, apps/console/src/pages/organization/[id]/settings.tsx, packages/design-system/src/new-ui/ComplicateIcons/Drag.tsx, packages/toolkit/src/view/organizations/OrganizationSettings.tsx, packages/toolkit/src/view/organizations/OrganizationsTab.tsx, packages/toolkit/src/view/organizations/index.ts
Because
- add organization page and sidebar
This commit
- add organization page and sidebar
=> chore(organization): add organization page and sidebar

apps/console/src/components/OrganizationSidebar/OrganizationSidebar.tsx, apps/console/src/pages/organization/[id]/account.tsx, apps/console/src/pages/organization/[id]/api-tokens.tsx, apps/console/src/pages/organization/[id]/billing.tsx, apps/console/src/pages/organization/[id]/members.tsx, apps/console/src/pages/organization/[id]/permissions.tsx, apps/console/src/pages/settings/organizations.tsx, packages/toolkit/src/view/organizations/OrganizationSettings.tsx
Because
- oraganization page
This commit
- oraganization page
=> chore(oraganization): oraganization page

apps/console/src/pages/organization/[id]/members.tsx, packages/toolkit/src/view/organizations/MemberCard.tsx, packages/toolkit/src/view/organizations/OrganizationMembers.tsx, packages/toolkit/src/view/organizations/index.ts
Because
- oraganization members page
This commit
- oraganization members page
=> chore: Namananand/ins 2605 oraganization members page

packages/toolkit/src/lib/fillArrayWithZero.ts, packages/toolkit/src/lib/index.ts, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/ImageListItem.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/ImagesField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/NewImageField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/NewImagesField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/index.ts, packages/toolkit/src/view/pipeline-builder/components/start-node/StartOperatorNode.tsx
Because
- update the design of image and multiple images field on start operator node
This commit
- update the design of image and multiple images field on start operator node
=> feat(pipeline-builder): update the design of image and multiple images field on start operator node

apps/console/src/pages/organization/[id]/permissions.tsx, packages/toolkit/src/view/organizations/UsersCard.tsx, packages/toolkit/src/view/organizations/index.ts
Because
- oraganization all users profile components under permission
This commit
- oraganization all users profile components under permission
=> chore(organization): Namananand/ins 2608 oraganization all users profile components under permission

packages/design-system/package.json, packages/design-system/src/new-ui/Progress/Progress.stories.tsx, packages/design-system/src/new-ui/Progress/Progress.tsx, packages/design-system/src/new-ui/Progress/index.ts, packages/design-system/src/new-ui/index.ts, pnpm-lock.yaml
Because
- add Progress component
This commit
- add Progress component
=> feat(design-system): add Progress component

packages/design-system/src/new-ui/Icons/Globe01.tsx, packages/design-system/src/new-ui/Icons/index.ts
Because
- add globe icon
This commit
- add globe icon
=> chore(design-system): add globe icon

apps/console/src/components/PricingPlanLayout.tsx, apps/console/src/components/index.ts, apps/console/src/pages/settings/pricing.tsx, packages/toolkit/src/view/organizations/OrganizationsTab.tsx
Because
- pricing page
This commit
- pricing page
=> chore(organization): Namananand/ins 2666 pricing page

apps/console/src/pages/organization/[id]/index.tsx, apps/console/src/pages/organization/[id]/permissions.tsx, packages/toolkit/src/view/organizations/OrganizationsTab.tsx
Because
- members page
This commit
- members page
=> chore(organization): members page

packages/toolkit/src/lib/useResourceAdditionalForm.tsx, packages/toolkit/src/lib/utility/index.ts, packages/toolkit/src/lib/utility/validateComponentID.ts, packages/toolkit/src/lib/utility/validateInstillID.ts, packages/toolkit/src/lib/utility/validateResourceId/index.ts, packages/toolkit/src/lib/utility/validateResourceId/validateResourceId.ts, packages/toolkit/src/view/data/DataResourceForm.tsx, packages/toolkit/src/view/model/CreateModelForm.tsx, packages/toolkit/src/view/pipeline-builder/components/connector-node/ConnectorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/end-operator-node/EndOperatorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/operator-node/OperatorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/start-operator-node/constructFieldKey.ts
Because
- update the new rule for all the resource's ID - lowercase, digit, underscore only and 32 characters max
This commit
- update the new rule for all the resource's ID - lowercase, digit, underscore only and 32 characters max
=> feat: update the new rule for all the resource's ID - lowercase, digit, underscore only and 32 characters max

apps/console/src/pages/organization/[id]/index.tsx, packages/toolkit/src/view/organizations/TeamMembersCard.tsx, packages/toolkit/src/view/organizations/index.ts
Because
- team members card component
This commit
- team members card component
=> chore(organization): Namananand/ins 2609 team members card component

apps/console/src/pages/[entity]/pipelines/index.tsx, packages/toolkit/src/view/organizations/CreateOrganizationDialog.tsx, packages/toolkit/src/view/organizations/OrganizationsTab.tsx, packages/toolkit/src/view/organizations/index.ts
Because
- create oraganization model form card
This commit
- create oraganization model form card
=> chore(organization): Namananand/ins 2614 create oraganization model form card

packages/design-system/src/new-ui/Icons/Recording03.tsx, packages/design-system/src/new-ui/Icons/index.ts
Because
- add recording-03 icon
This commit
- add recording-03 icon
=> chore: add recording-03 icon

packages/design-system/src/new-ui/Icons/PauseCircle.tsx, packages/design-system/src/new-ui/Icons/PlayCircle.tsx, packages/design-system/src/new-ui/Icons/index.ts
Because
- add PauseCircle and PlayCircle icons
This commit
- add PauseCircle and PlayCircle icons
=> chore: add PauseCircle and PlayCircle icons

packages/toolkit/package.json, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/AudioField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/AudioListItem.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/UploadFileInput.tsx, pnpm-lock.yaml
Because
- user can have the new audio input on the start operator
This commit
- user can have the new audio input on the start operator
=> feat(pipeline-builder): user can have the new audio input on the start operator

packages/design-system/src/new-ui/Icons/File02.tsx, packages/design-system/src/new-ui/Icons/FilePlus02.tsx, packages/design-system/src/new-ui/Icons/Recording04.tsx, packages/design-system/src/new-ui/Icons/Recording05.tsx, packages/design-system/src/new-ui/Icons/TypePlus.tsx, packages/design-system/src/new-ui/Icons/index.ts
Because
- add start input types icon
This commit
- add start input types icon
=> chore: add start input types icon

packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/AudioField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/AudiosField.tsx, packages/toolkit/src/lib/vdp-sdk/pipeline/types.ts, packages/toolkit/src/view/pipeline-builder/components/start-operator-node/StartNodeInputType.tsx, packages/toolkit/src/view/pipeline-builder/components/start-operator-node/StartOperatorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/start-operator-node/StartOperatorNodeFreeForm.tsx, packages/toolkit/src/view/pipeline-builder/components/start-operator-node/pickSelectedTypeFromInstillFormat.ts
Because
- User can have new multiple audios input
This commit
- User can have new multiple audios input
=> feat(pipeline-builder):  User can have new multiple audios input

packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/AudiosField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/FileField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/FileListItem.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/ImagesField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/index.ts, packages/toolkit/src/lib/use-instill-form/pick/pickStartOperatorFreeFormFields.tsx, packages/toolkit/src/view/pipeline-builder/components/start-operator-node/StartNodeInputType.tsx, packages/toolkit/src/view/pipeline-builder/components/start-operator-node/StartOperatorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/start-operator-node/StartOperatorNodeFreeForm.tsx
Because
- User can upload file on start operator
This commit
- User can upload file on start operator
=> feat(pipeline-builder): User can upload file on start operator

packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/AudioField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/AudiosField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/FilesField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/ImageField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/index.ts, packages/toolkit/src/lib/use-instill-form/pick/pickStartOperatorFreeFormFields.tsx, packages/toolkit/src/view/pipeline-builder/components/start-operator-node/StartNodeInputType.tsx, packages/toolkit/src/view/pipeline-builder/components/start-operator-node/StartOperatorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/start-operator-node/StartOperatorNodeFreeForm.tsx, packages/toolkit/src/view/pipeline-builder/components/start-operator-node/pickSelectedTypeFromInstillFormat.ts
Because
- User can upload multiple files on start operator
This commit
- User can upload multiple files on start operator
=> feat(pipeline-builder): User can upload multiple files on start operator

packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/FieldHead.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/TextsField.tsx, packages/toolkit/src/view/pipeline-builder/components/start-operator-node/StartNodeInputType.tsx, packages/toolkit/src/view/pipeline-builder/components/start-operator-node/StartOperatorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/start-operator-node/StartOperatorNodeFreeForm.tsx
Because
- User can use new array:string in start operator
This commit
- User can use new array:string in start operator
=> feat(pipeline-builder): User can use new array:string in start operator

packages/design-system/src/new-ui/Icons/Lightning01.tsx, packages/design-system/src/new-ui/Icons/index.ts, packages/design-system/src/new-ui/Switch/Switch.tsx
Because
- add lightning01 icons and expose more props on Switch
This commit
- add lightning01 icons and expose more props on Switch
=> chore: add lightning01 icons and expose more props on Switch

packages/toolkit/package.json, packages/toolkit/src/lib/use-instill-form/components/component-output/CopyButton.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output/MDTextViewer.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output/TextField.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output/TextsField.tsx, packages/toolkit/src/lib/use-instill-form/pick/pickComponentOutputFieldsFromInstillFormTree.tsx, packages/toolkit/src/view/pipeline-builder/components/start-operator-node/StartOperatorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/start-operator-node/constructFieldKey.ts, pnpm-lock.yaml
Because
- User can have new formatted output text field
This commit
- User can have new formatted output text field
=> feat(pipeline-builder): User can have new formatted output text field

packages/design-system/package.json, packages/design-system/src/new-ui/Menubar/Menubar.stories.tsx, packages/design-system/src/new-ui/Menubar/Menubar.tsx, packages/design-system/src/new-ui/Menubar/index.ts, packages/design-system/src/new-ui/index.ts, pnpm-lock.yaml
Because
- add Menubar
This commit
- add Menubar
=> feat(design-system): add Menubar

packages/toolkit/src/constant/errors.ts, packages/toolkit/src/lib/useResourceAdditionalForm.tsx, packages/toolkit/src/lib/utility/validateInstillID.ts, packages/toolkit/src/view/data/DataResourceForm.tsx, packages/toolkit/src/view/model/CreateModelForm.tsx, packages/toolkit/src/view/pipeline-builder/components/PipelineNameForm.tsx, packages/toolkit/src/view/pipeline-builder/components/connector-node/ConnectorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/end-operator-node/EndOperatorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/operator-node/OperatorNode.tsx
Because
- Update the latest naming rule ^[a-z_][-a-z_0-9]{0,31}$
This commit
- Update the latest naming rule ^[a-z_][-a-z_0-9]{0,31}$
=> feat(general): Update the latest naming rule ^[a-z_][-a-z_0-9]{0,31}$

packages/toolkit/src/view/pipeline-builder/components/NodeBottomBar.tsx, packages/toolkit/src/view/pipeline-builder/components/NodeWrapper.tsx, packages/toolkit/src/view/pipeline-builder/components/connector-node/ConnectorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/start-operator-node/StartOperatorNode.tsx
Because
- User can have a bottom bar on the connector node to showcase output information
This commit
- User can have a bottom bar on the connector node to showcase output information
=> feat(pipeline-builder): User can have a bottom bar on the connector node to showcase output information

packages/design-system/src/new-ui/ScrollArea/ScrollArea.tsx, packages/toolkit/src/components/ObjectViewer.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output/AudioField.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output/AudiosField.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output/FieldRoot.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output/ImageField.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output/ImagesField.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output/NumberField.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output/NumbersField.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output/ObjectArrayField.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output/ObjectField.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output/ObjectsField.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output/TextField.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output/TextsField.tsx, packages/toolkit/src/view/pipeline-builder/FlowControl.tsx, packages/toolkit/src/view/pipeline-builder/components/NodeWrapper.tsx, packages/toolkit/src/view/pipeline-builder/components/connector-node/ConnectorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/control-panel/ConnectorOperatorControlPanel.tsx, packages/toolkit/src/view/pipeline-builder/components/operator-node/OperatorNode.tsx
Because
- highlight the node when user select it
This commit
- highlight the node when user select it
=> feat(pipeline-builder): highlight the node when user select it

packages/design-system/src/new-ui/Menubar/Menubar.tsx, packages/toolkit/package.json, packages/toolkit/src/lib/use-smart-hint/pickSmartHintsFromAcceptFormats.ts, packages/toolkit/src/lib/use-smart-hint/useSmartHint.ts, packages/toolkit/src/view/data/DataResourceForm.tsx, packages/toolkit/src/view/model/CreateModelForm.tsx, packages/toolkit/src/view/model/ModelsTable.tsx, packages/toolkit/src/view/pipeline-builder/FlowControl.tsx, packages/toolkit/src/view/pipeline-builder/components/BottomBar.tsx, packages/toolkit/src/view/pipeline-builder/components/PipelineToolkitModal.tsx, packages/toolkit/src/view/pipeline-builder/components/select-component-definition-dialog/SelectPipelineComponentDefinitionDialog.tsx
Because
- fix various bugs that will affect UI style and smart hint
This commit
- fix various bugs that will affect UI style and smart hint
=> fix: fix various bugs that will affect UI style and smart hint

apps/console/src/components/OrganizationSidebar/OrganizationSidebar.tsx, apps/console/src/pages/[entity]/profile/index.tsx, apps/console/src/pages/organization/[id]/account.tsx, apps/console/src/pages/organization/[id]/api-tokens.tsx, apps/console/src/pages/organization/[id]/billing.tsx, apps/console/src/pages/organization/[id]/index.tsx, apps/console/src/pages/organization/[id]/members.tsx, apps/console/src/pages/organization/[id]/permissions.tsx, apps/console/src/pages/organization/[id]/settings.tsx, apps/console/src/pages/settings/account.tsx, apps/console/src/pages/settings/api-tokens.tsx, apps/console/src/pages/settings/billings.tsx, apps/console/src/pages/settings/index.tsx, apps/console/src/pages/settings/organizations.tsx, packages/toolkit/src/components/BreadcrumbWithLink/BreadcrumbWithLink.tsx, packages/toolkit/src/components/BreadcrumbWithLink/index.ts, packages/toolkit/src/components/index.ts, packages/toolkit/src/lib/react-query-service/index.ts, packages/toolkit/src/lib/react-query-service/organization/index.ts, packages/toolkit/src/lib/react-query-service/organization/useCreateOrganization.ts, packages/toolkit/src/lib/react-query-service/organization/useOrganizations.ts, packages/toolkit/src/lib/vdp-sdk/index.ts, packages/toolkit/src/lib/vdp-sdk/organization/index.ts, packages/toolkit/src/lib/vdp-sdk/organization/mutations.ts, packages/toolkit/src/lib/vdp-sdk/organization/queries.ts, packages/toolkit/src/lib/vdp-sdk/organization/types.ts, packages/toolkit/src/view/organizations/CreateOrganizationDialog.tsx, packages/toolkit/src/view/organizations/OrganizationsTab.tsx
Because
- api implementation create organization
This commit
- api implementation create organization
=> chore(organization): Namananand/ins 2681 api implementation create organization

packages/toolkit/src/view/pipeline/PipelineListPageMainView.tsx
Because
- update create pipeline link to pipeline builder
This commit
- update create pipeline link to pipeline builder
=> chore: update create pipeline link to pipeline builder

apps/console/src/components/OnboardingForm.tsx, apps/console/src/lib/mgmtRoleOptions.ts, packages/design-system/src/index.ts, packages/design-system/src/new-ui/Combobox/Combobox.stories.tsx, packages/design-system/src/new-ui/Combobox/Combobox.tsx, packages/design-system/src/new-ui/MultiSelect/MultiSelect.stories.tsx, packages/design-system/src/new-ui/MultiSelect/MultiSelect.tsx, packages/design-system/src/new-ui/MultiSelect/index.ts, packages/design-system/src/new-ui/index.ts, packages/design-system/src/types/general.ts, packages/design-system/src/ui/SingleSelects/BasicSingleSelect/BasicSingleSelect.stories.tsx, packages/design-system/src/ui/SingleSelects/SingleSelectBase/SelectItem.tsx, packages/design-system/src/ui/SingleSelects/SingleSelectBase/SingleSelectBase.stories.tsx, packages/design-system/src/ui/SingleSelects/SingleSelectBase/SingleSelectBase.tsx, packages/design-system/src/ui/SingleSelects/index.ts, packages/design-system/src/ui/index.ts, packages/toolkit/src/lib/dashboard/getPipeLineOptions.ts, packages/toolkit/src/lib/dashboard/options.ts, packages/toolkit/src/view/airbyte/OneOfConditionSection.tsx, packages/toolkit/src/view/dashboard/DashboardPipelineDetailsPageMainView.tsx, packages/toolkit/src/view/dashboard/DashboardPipelineListPageMainView.tsx, packages/toolkit/src/view/dashboard/FilterByDay.tsx, packages/toolkit/src/view/dashboard/PipelineTriggerCountsLineChart.tsx, packages/toolkit/src/view/mgmt/ConfigureProfileForm.tsx, packages/toolkit/src/view/model/CreateModelForm.tsx, packages/toolkit/src/view/user-settings/ProfileTab.tsx
Because
- add MultiSelect component
This commit
- add MultiSelect component
=> feat(design-system): add MultiSelect component

packages/design-system/src/new-ui/index.ts, packages/design-system/src/new-ui/tab-menu/TabMenu.stories.tsx, packages/design-system/src/new-ui/tab-menu/TabMenu.tsx, packages/design-system/src/new-ui/tab-menu/index.ts
Because
- add TabMenu component
This commit
- add TabMenu component
=> feat(design-system): add TabMenu component

packages/design-system/package.json, packages/toolkit/package.json, packages/toolkit/src/lib/react-query-service/organization/useUpdateOrgaization.ts, packages/toolkit/src/lib/vdp-sdk/organization/mutations.ts, packages/toolkit/src/lib/vdp-sdk/organization/types.ts
Because
- Fix organization related types
This commit
- Fix organization related types
=> fix(sdk): Fix organization related types

packages/design-system/package.json, packages/design-system/src/new-ui/Icons/UserPlus01.tsx, packages/design-system/src/new-ui/Icons/index.ts
Because
- add user plus icon
This commit
- add user plus icon
=> chore(design-system): add user plus icon

packages/design-system/package.json, packages/design-system/src/new-ui/index.ts, packages/design-system/src/new-ui/radio-group/RadioGroup.stories.tsx, packages/design-system/src/new-ui/radio-group/RadioGroup.tsx, packages/design-system/src/new-ui/radio-group/index.ts, pnpm-lock.yaml
Because
- add RadioGroup component
This commit
- add RadioGroup component
=> feat(design-system): add RadioGroup component

packages/toolkit/src/view/pipeline-builder/FlowControl.tsx, packages/toolkit/src/view/pipeline-builder/components/BottomBar.tsx, packages/toolkit/src/view/pipeline-builder/components/dialog-share-pipeline/DialogSharePipeline.tsx, packages/toolkit/src/view/pipeline-builder/components/menu-release/Description.tsx, packages/toolkit/src/view/pipeline-builder/components/menu-release/Head.tsx, packages/toolkit/src/view/pipeline-builder/components/menu-release/MenuRelease.tsx, packages/toolkit/src/view/pipeline-builder/components/menu-release/SemverSelect.tsx
Because
- Simplified release flow and make it more intuitive
This commit
- Simplified release flow and make it more intuitive
=> feat(pipeline-builder): Simplified release flow and make it more intuitive

packages/toolkit/src/lib/vdp-sdk/mgmt/actions.ts, packages/toolkit/src/lib/vdp-sdk/mgmt/queries.ts, packages/toolkit/src/lib/vdp-sdk/mgmt/types.ts, packages/toolkit/src/view/mgmt/ConfigureProfileForm.tsx, packages/toolkit/src/view/pipeline-builder/components/PipelineToolkitModal.tsx
Because
- add checkNamespace action 
This commit
- add checkNamespace action
=> feat(sdk): add checkNamespace endpoint

apps/console/src/components/top-bar/Topbar.tsx, apps/console/src/pages/hub.tsx, packages/design-system/src/new-ui/tab-menu/TabMenu.tsx, packages/toolkit/src/components/UserProfileCard.tsx, packages/toolkit/src/components/index.ts, packages/toolkit/src/lib/react-query-service/pipeline/index.ts, packages/toolkit/src/lib/react-query-service/pipeline/useInfinitePipelines.ts, packages/toolkit/src/lib/react-query-service/pipeline/usePipelines.ts, packages/toolkit/src/lib/vdp-sdk/mgmt/types.ts, packages/toolkit/src/lib/vdp-sdk/pipeline/queries.ts, packages/toolkit/src/view/hub/hub-view/Body.tsx, packages/toolkit/src/view/hub/hub-view/Header.tsx, packages/toolkit/src/view/hub/hub-view/HubView.tsx, packages/toolkit/src/view/hub/hub-view/Tab.tsx, packages/toolkit/src/view/hub/hub-view/index.ts, packages/toolkit/src/view/hub/index.ts, packages/toolkit/src/view/index.ts, packages/toolkit/src/view/pipeline-builder/components/dialogs/share-pipeline-dialog/Head.tsx, packages/toolkit/src/view/pipeline/view-pipeline/Head.tsx
Because
- User can browse other's pipelines on hub page
This commit
- User can browse other's pipelines on hub page
=> feat: User can browse other's pipelines on hub page

packages/toolkit/src/components/ImageWithFallback.tsx, packages/toolkit/src/components/card-pipeline/Body.tsx, packages/toolkit/src/components/card-pipeline/CardPipeline.tsx, packages/toolkit/src/components/card-pipeline/Footer.tsx, packages/toolkit/src/components/card-pipeline/Head.tsx, packages/toolkit/src/components/card-pipeline/Menu.tsx, packages/toolkit/src/lib/react-query-service/pipeline/useCreateUserPipeline.ts, packages/toolkit/src/lib/react-query-service/pipeline/useDeleteUserPipeline.ts, packages/toolkit/src/lib/vdp-sdk/pipeline/mutations.ts, packages/toolkit/src/lib/vdp-sdk/pipeline/types.ts, packages/toolkit/src/view/hub/hub-view/Body.tsx, packages/toolkit/src/view/pipeline-builder/components/PipelineNameForm.tsx, packages/toolkit/src/view/pipeline-builder/components/ReadOnlyPipelineBuilder.tsx, packages/toolkit/src/view/pipeline-builder/components/dialogs/publish-pipeline-dialog/Head.tsx, packages/toolkit/src/view/pipeline-builder/components/dialogs/publish-pipeline-dialog/Metadata.tsx, packages/toolkit/src/view/pipeline-builder/components/dialogs/publish-pipeline-dialog/PublishPipelineDialog.tsx, packages/toolkit/src/view/pipeline-builder/components/dialogs/publish-pipeline-dialog/ReadmeEditor.tsx, packages/toolkit/src/view/pipeline-builder/components/dialogs/share-pipeline-dialog/TabPublish.tsx, packages/toolkit/src/view/pipeline-builder/components/dialogs/share-pipeline-dialog/TabShare.tsx, packages/toolkit/src/view/pipeline-builder/components/dialogs/share-pipeline-dialog/UnpublishPipelineDialog.tsx, packages/toolkit/src/view/pipeline-builder/lib/getRawPipelineRecipeFromPipelineRecipe.ts, packages/toolkit/src/view/pipeline-builder/lib/useSortedReleases.tsx, packages/toolkit/src/view/pipeline/view-pipeline/EditMetadataDialog.tsx, packages/toolkit/src/view/pipeline/view-pipeline/Head.tsx, packages/toolkit/src/view/pipeline/view-pipeline/InOutPut.tsx, packages/toolkit/src/view/pipeline/view-pipeline/Readme.tsx, packages/toolkit/src/view/pipeline/view-pipeline/ViewPipeline.tsx, packages/toolkit/src/view/pipeline/view-pipelines/ViewPipelines.tsx, packages/toolkit/src/view/settings/api-tokens/APITokenTable.tsx, packages/toolkit/src/view/settings/user/UserAPITokenTab.tsx
Because
- adapt new pipeline readme design to store complicated description
This commit
- adapt new pipeline readme design to store complicated description
=> feat(general): adapt new pipeline readme design to store complicated description

packages/toolkit/src/lib/store/useCreateResourceFormStore.ts, packages/toolkit/src/lib/tip-tap/markdown.ts, packages/toolkit/src/lib/type/zod.ts, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/AudioField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/AudiosField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/BooleanField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/FieldHead.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/FileField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/FilesField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/ImageField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/ImagesField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/LongTextField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/NumberField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/NumbersField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/TextField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/TextareaField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/TextsField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/UploadFileInput.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/types.ts, packages/toolkit/src/lib/use-instill-form/pick/pickStartOperatorFreeFormFields.tsx, packages/toolkit/src/lib/use-instill-form/transform/transformStartOperatorMetadataToZod.ts, packages/toolkit/src/lib/use-instill-form/type.ts, packages/toolkit/src/lib/use-instill-form/useStartOperatorTriggerPipelineForm.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/start-operator-node/StartOperatorNode.tsx, packages/toolkit/src/view/pipeline/view-pipeline/InOutPut.tsx
Because
- fix input-output form not working on the pipeline details page
This commit
- fix input-output form not working on the pipeline details page
=> fix(pipeline): fix input-output form not working on the pipeline details page

packages/eslint-config-cortex/index.js, packages/toolkit/package.json, packages/toolkit/src/components/UserProfileCard.tsx, packages/toolkit/src/lib/dot/index.test.ts, packages/toolkit/src/lib/use-instill-form/components/smart-hint/onInputChange.tsx, packages/toolkit/src/lib/use-instill-form/pick/pickComponentOutputFieldsFromInstillFormTree.tsx, packages/toolkit/src/lib/use-instill-form/transform/recursivelyResetFormData.test.ts, packages/toolkit/src/lib/use-instill-form/useComponentOutputFields.tsx, packages/toolkit/src/view/hub/hub-view/Body.tsx, packages/toolkit/src/view/hub/hub-view/HubView.tsx, packages/toolkit/src/view/pipeline-builder/components/VerticalSortableWrapper.tsx, packages/toolkit/src/view/pipeline-builder/components/dialogs/publish-pipeline-dialog/Metadata.tsx, packages/toolkit/src/view/pipeline-builder/components/dialogs/publish-pipeline-dialog/PublishPipelineDialog.tsx, packages/toolkit/src/view/pipeline-builder/components/dialogs/publish-pipeline-dialog/ReadmeEditor.tsx, packages/toolkit/src/view/pipeline-builder/components/dialogs/share-pipeline-dialog/UnpublishPipelineDialog.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/common/NodeIDEditor.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/start-operator-node/StartOperatorNodeFreeForm.tsx, packages/toolkit/src/view/pipeline-builder/components/release-menu/ReleaseMenu.tsx
Because
- fix hub not correctly fetch current user and unpublish-publish pipeline issue
This commit
- fix hub not correctly fetch current user and unpublish-publish pipeline issue
=> fix: fix hub not correctly fetch current user and unpublish-publish pipeline issue

packages/toolkit/src/view/pipeline-builder/FlowControl.tsx, packages/toolkit/src/view/pipeline-builder/components/PipelineNameForm.tsx
Because
- fix routing issue in pipeline-builder, redirect new pipeline backward back to /pipelines page
This commit
- fix routing issue in pipeline-builder, redirect new pipeline backward back to /pipelines page
=> fix: fix routing issue in pipeline-builder, redirect new pipeline backward back to /pipelines page

apps/console/src/components/CreatePipelineDialog.tsx, apps/console/src/components/index.ts, apps/console/src/pages/[entity]/pipelines/index.tsx, packages/design-system/src/new-ui/Icons/BookOpen02.tsx, packages/design-system/src/new-ui/Icons/index.ts, packages/toolkit/src/lib/hook/useNavigationObserver.tsx, packages/toolkit/src/lib/usePipelineBuilderGraph.tsx, packages/toolkit/src/lib/vdp-sdk/pipeline/mutations.ts, packages/toolkit/src/view/pipeline-builder/components/nodes/connector-node/ConnectorNode.tsx, packages/toolkit/src/view/pipeline/PipelineBuilderMainView.tsx, packages/toolkit/src/view/pipeline/view-pipelines/ViewPipelines.tsx
Because
- User can have new advanced pipeline creation dialog
This commit
- User can have new advanced pipeline creation dialog
=> feat(pipeline-builder): User can have new advanced pipeline creation dialog

apps/console/src/components/CreatePipelineDialog.tsx, apps/console/src/pages/[entity]/pipelines/index.tsx, packages/design-system/package.json, packages/design-system/src/new-ui/Icons/BarChartSquare02 copy.tsx, packages/toolkit/package.json, packages/toolkit/src/components/InlineTextSeparator.tsx, packages/toolkit/src/components/UserProfileCard.tsx, packages/toolkit/src/components/card-pipeline/Footer.tsx, packages/toolkit/src/components/index.ts, packages/toolkit/src/lib/index.ts, packages/toolkit/src/lib/useEntity.ts, packages/toolkit/src/lib/usePipelineBuilderGraph.tsx, packages/toolkit/src/lib/vdp-sdk/organization/types.ts, packages/toolkit/src/view/ai/AIResourceAutoForm.tsx, packages/toolkit/src/view/blockchain/BlockchainResourceAutoForm.tsx, packages/toolkit/src/view/data/DataResourceForm.tsx, packages/toolkit/src/view/hub/hub-view/Body.tsx, packages/toolkit/src/view/pipeline-builder/components/BottomBar.tsx, packages/toolkit/src/view/pipeline-builder/components/PipelineNameForm.tsx, packages/toolkit/src/view/pipeline-builder/components/dialogs/share-pipeline-dialog/UnpublishPipelineDialog.tsx, packages/toolkit/src/view/pipeline/view-pipeline/EditMetadataDialog.tsx, packages/toolkit/src/view/pipeline/view-pipeline/InOutPut.tsx, packages/toolkit/src/view/pipeline/view-pipeline/Readme.tsx, packages/toolkit/src/view/pipeline/view-pipelines/ViewPipelines.tsx, packages/toolkit/src/view/profile/Separator.tsx, packages/toolkit/src/view/resource/AddConnectorDialog.tsx, packages/toolkit/src/view/resource/ResourceSettingPageMainView.tsx, packages/toolkit/src/view/resource/ResourcesTable.tsx, packages/toolkit/src/view/resource/index.ts, pnpm-lock.yaml
Because
- fix wrongly used entity issue
This commit
- fix wrongly used entity issue
=> fix: fix wrongly used entity issue

apps/console/src/components/top-bar/Topbar.tsx, packages/toolkit/package.json, packages/toolkit/src/lib/hook/useNavigationObserver.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output/ObjectsField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/BooleanField.tsx, packages/toolkit/src/lib/use-instill-form/pick/pickStartOperatorFreeFormFields.tsx, packages/toolkit/src/lib/use-instill-form/transform/transformStartOperatorMetadataToSuperRefineRules.ts, packages/toolkit/src/view/pipeline-builder/components/nodes/start-operator-node/StartOperatorNode.tsx, packages/toolkit/src/view/pipeline/PipelineBuilderMainView.tsx
Because
- fix navigation bug and start operator input issue
This commit
- fix navigation bug and start operator input issue
=> fix: fix navigation bug and start operator input issue

apps/console/src/components/CreatePipelineDialog.tsx, packages/toolkit/package.json, packages/toolkit/src/components/card-pipeline/Head.tsx, packages/toolkit/src/constant/index.ts, packages/toolkit/src/index.ts, packages/toolkit/src/lib/useResourceAdditionalForm.tsx, packages/toolkit/src/view/dashboard/DashboardPipelineListPageMainView.tsx, packages/toolkit/src/view/dashboard/DashboardPipelinesTable.tsx, packages/toolkit/src/view/dashboard/RemainingTriggers.tsx, packages/toolkit/src/view/pipeline-builder/Flow.tsx, packages/toolkit/src/view/pipeline-builder/FlowControl.tsx, packages/toolkit/src/view/pipeline-builder/components/ComponentFormOnRightPanel.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/connector-node/ConnectorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/release-menu/ReleaseMenu.tsx, packages/toolkit/src/view/resource/ResourceListPageMainView.tsx
Because
- fix creating pipeline public/private issue
This commit
- fix creating pipeline public/private issue
=> fix: fix creating pipeline public/private issue

apps/console/src/components/CreatePipelineDialog.tsx, packages/toolkit/package.json, packages/toolkit/src/components/UserProfileCard.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/BooleanField.tsx, packages/toolkit/src/lib/useEntity.ts, packages/toolkit/src/view/dashboard/DashboardPipelineDetailsPageMainView.tsx, packages/toolkit/src/view/dashboard/DashboardPipelineListPageMainView.tsx, packages/toolkit/src/view/hub/hub-view/Body.tsx
Because
- fix dashboard not correctly display organization metric
This commit
- fix dashboard not correctly display organization metric
=> fix: fix dashboard not correctly display organization metric

packages/toolkit/package.json, packages/toolkit/src/view/dashboard/RemainingTriggers.tsx
Because
- update dashboard loader
This commit
- update dashboard loader
=> chore(dashboard): update dashboard loader

packages/toolkit/src/view/pipeline-builder/components/nodes/connector-node/ConnectorNode.tsx, packages/toolkit/src/view/pipeline-builder/lib/getPropertiesFromOpenAPISchema.ts
Because
- fix console not correctly parse semi-structured output object
This commit
- fix console not correctly parse semi-structured output object
=> fix(pipeline-builder): fix console not correctly parse semi-structured output object

packages/design-system/src/new-ui/Icons/BracketSlash.tsx, packages/design-system/src/new-ui/Icons/index.ts, packages/toolkit/src/lib/use-instill-form/components/smart-hint/useFilteredHints.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/ObjectField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/index.ts, packages/toolkit/src/lib/use-instill-form/pick/pickRegularFieldsFromInstillFormTree.tsx, packages/toolkit/src/lib/use-instill-form/pick/pickStartOperatorFreeFormFields.tsx, packages/toolkit/src/lib/use-instill-form/transform/transformInstillJSONSchemaToZod.ts, packages/toolkit/src/lib/use-instill-form/transform/transformStartOperatorMetadataToZod.ts, packages/toolkit/src/lib/use-smart-hint/pickSmartHintsFromAcceptFormats.ts, packages/toolkit/src/lib/vdp-sdk/pipeline/types.ts, packages/toolkit/src/view/pipeline-builder/components/nodes/start-operator-node/StartNodeInputType.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/start-operator-node/StartOperatorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/start-operator-node/StartOperatorNodeFreeForm.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/start-operator-node/pickSelectedTypeFromInstillFormat.ts
Because
- support JSON input on start operator
This commit
- support JSON input on start operator
=> feat(pipeline-builder): support JSON input on start operator

packages/design-system/package.json, packages/toolkit/package.json, packages/toolkit/src/components/GenerateDeleteResourceDialog.tsx, packages/toolkit/src/view/dashboard/DashboardPipelineListPageMainView.tsx, packages/toolkit/src/view/dashboard/RemainingTriggers.tsx
Because
- fix delete resource dialog close button wrongly positioned
This commit
- fix delete resource dialog close button wrongly positioned
=> fix: fix delete resource dialog close button wrongly positioned

apps/console/src/components/index.ts, apps/console/src/pages/[entity]/pipelines/[id]/index.tsx, apps/console/src/pages/[entity]/pipelines/index.tsx, packages/toolkit/package.json, packages/toolkit/src/components/ClonePipelineDialog.tsx, packages/toolkit/src/components/WarnUnsavedChangesDialog.tsx, packages/toolkit/src/components/card-pipeline/Body.tsx, packages/toolkit/src/components/card-pipeline/CardPipeline.tsx, packages/toolkit/src/components/card-pipeline/Footer.tsx, packages/toolkit/src/components/index.ts, packages/toolkit/src/lib/toastInstillError.ts, packages/toolkit/src/view/pipeline-builder/Flow.tsx, packages/toolkit/src/view/pipeline-builder/FlowControl.tsx, packages/toolkit/src/view/pipeline/PipelineBuilderMainView.tsx, packages/toolkit/src/view/pipeline/view-pipeline/Head.tsx, packages/toolkit/src/view/pipeline/view-pipelines/CreatePipelineDialog.tsx, packages/toolkit/src/view/pipeline/view-pipelines/ViewPipelines.tsx
Because
- fix user can not smoothly clone the pipeline and decide what is its permission level
This commit
- fix user can not smoothly clone the pipeline and decide what is its permission level
=> fix: fix user can not smoothly clone the pipeline and decide what is its permission level

packages/toolkit/package.json, packages/toolkit/src/components/ClonePipelineDialog.tsx, packages/toolkit/src/components/card-pipeline/Footer.tsx, packages/toolkit/src/components/card-pipeline/Head.tsx, packages/toolkit/src/components/card-pipeline/Menu.tsx, packages/toolkit/src/lib/react-query-service/pipeline/useTriggerUserPipeline.tsx, packages/toolkit/src/lib/vdp-sdk/pipeline/actions.ts, packages/toolkit/src/view/dashboard/DashboardPipelineListPageMainView.tsx, packages/toolkit/src/view/pipeline-builder/components/dialogs/share-pipeline-dialog/Head.tsx, packages/toolkit/src/view/pipeline-builder/components/dialogs/share-pipeline-dialog/TabShare.tsx, packages/toolkit/src/view/pipeline/view-pipeline/ViewPipeline.tsx
Because
- fix invalid share-by-link link
This commit
- fix invalid share-by-link link
=> fix: fix invalid share-by-link link

apps/console/CHANGELOG.md, apps/console/src/pages/[entity]/dashboard/index.tsx, packages/toolkit/CHANGELOG.md, packages/toolkit/package.json, packages/toolkit/src/components/card-pipeline/Body.tsx, packages/toolkit/src/components/card-pipeline/CardPipeline.tsx, packages/toolkit/src/components/card-pipeline/Head.tsx, packages/toolkit/src/lib/react-query-service/metric/useUsersSubscription.ts, packages/toolkit/src/view/dashboard/DashboardPipelineDetailsPageMainView.tsx, packages/toolkit/src/view/dashboard/DashboardPipelineListPageMainView.tsx, packages/toolkit/src/view/dashboard/RemainingTriggers.tsx, packages/toolkit/src/view/hub/hub-view/Body.tsx, packages/toolkit/src/view/pipeline-builder/Flow.tsx, packages/toolkit/src/view/pipeline-builder/FlowControl.tsx, packages/toolkit/src/view/pipeline-builder/components/ReadOnlyPipelineBuilder.tsx, packages/toolkit/src/view/pipeline-builder/components/release-menu/ReleaseMenu.tsx, packages/toolkit/src/view/pipeline/view-pipeline/Head.tsx, packages/toolkit/src/view/pipeline/view-pipeline/ViewPipeline.tsx, packages/toolkit/src/view/pipeline/view-pipelines/ViewPipelines.tsx, packages/toolkit/src/view/resource/ResourcesTable.tsx, pnpm-lock.yaml
Because
- fix not correctly add nodes at the center of the nodes
This commit
- fix not correctly add nodes at the center of the nodes
=> fix(pipeline-builder): fix not correctly add nodes at the center of the nodes

packages/toolkit/src/view/settings/instillUserRoles.ts
Because
- update the new user role options
This commit
- update the new user role options
=> feat: update the new user role options

packages/toolkit/src/components/card-pipeline/CardPipeline.tsx, packages/toolkit/src/components/card-pipeline/Footer.tsx, packages/toolkit/src/lib/index.ts, packages/toolkit/src/lib/isPublicPipeline.ts, packages/toolkit/src/view/hub/hub-view/Body.tsx, packages/toolkit/src/view/pipeline/view-pipeline/Head.tsx
Because
- add pipeline sharing permission label to help user recognize it
This commit
- add pipeline sharing permission label to help user recognize it
=> feat: add pipeline sharing permission label to help user recognize it

.github/workflows/unit-test.yml, packages/toolkit/src/view/profile/Bio.tsx
Because
- fix twitter link and capitalize issue
This commit
- fix twitter link and capitalize issue
=> fix: fix twitter link and capitalize issue

.github/workflows/unit-test.yml, packages/toolkit/src/view/pipeline-builder/Flow.tsx
Because
- Introduce MiniMap in the pipeline-builder to improve UX
This commit
- Introduce MiniMap in the pipeline-builder to improve UX
=> feat(pipeline-builder): Introduce MiniMap in the pipeline-builder to improve UX

.gitignore, apps/console/src/pages/_app.tsx, apps/console/tsconfig.json
This commit
- Adds TS check for unused variables in console app
- Removes unused import of `useLayoutEffect` in `_app.tsx`
=> chore: add ts check for unused variables, remove unused useLayoutEffect import

packages/design-system/package.json, packages/toolkit/src/lib/airbytes/helpers/transformAirbyteSchemaToYup.ts, packages/toolkit/src/lib/airbytes/hooks/useAirbyteFieldValues.ts, packages/toolkit/src/view/airbyte/OneOfConditionSection.tsx, packages/toolkit/src/view/airbyte/useBuildAirbyteFields.tsx, pnpm-lock.yaml
Because
- support the action of merging Airbyte connectors into single one
This commit
- support the action of merging Airbyte connectors into single one
=> feat(auto-gen-form): support the action of merging Airbyte connectors into single one

apps/console/src/pages/_app.tsx
Because
Prettier checks failed in CI
```
Checking formatting...
[warn] apps/console/src/pages/_app.tsx
[warn] Code style issues found in the above file. Run Prettier to fix.
 ELIFECYCLE  Command failed with exit code 1.
Error: Process completed with exit code 1.
```
This commit
- Fixes the formatting issues in `apps/console/src/pages/_app.tsx`
=> chore: fix format issues in `apps/console/src/pages/_app.tsx` 

docs/instill-auto-form.md, packages/toolkit/src/view/settings/user/UserProfileTab.tsx
Because
- Console not correctly display the loading state when user updating the profile
This commit
- fix profile setting page not having correct loading flag
=> fix: fix profile setting page not having correct loading flag

apps/console/src/pages/[entity]/index.tsx
Because
- redirect user to 404 page if the user is not found
This commit
- redirect user to 404 page if the user is not found
=> chore: redirect user to 404 page if the user is not found

packages/toolkit/src/lib/use-instill-form/pick/pickComponentOutputFieldsFromInstillFormTree.tsx, packages/toolkit/src/lib/use-instill-form/pick/pickRegularFieldsFromInstillFormTree.tsx, packages/toolkit/src/lib/use-instill-form/type.ts, packages/toolkit/src/view/pipeline-builder/components/ComponentOutputs.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/connector-node/ConnectorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/end-operator-node/EndOperatorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/operator-node/OperatorNode.tsx, packages/toolkit/src/view/pipeline/view-pipeline/InOutPut.tsx
Because
- display the component ouput field title as title when demo
This commit
- display the component ouput field title as title when demo
=> feat(pipeline-builder): display the component ouput field title as title when demo

apps/console/src/pages/[entity]/models/[id].tsx, packages/toolkit/package.json, packages/toolkit/src/lib/useEntity.ts, packages/toolkit/src/view/model/ModelHubSettingPageMainView.tsx
Because
- fix model setting page query issue
This commit
- fix model setting page query issue
=> fix: fix model setting page query issue

packages/toolkit/src/lib/use-instill-form/pick/pickRegularFieldsFromInstillFormTree.tsx, packages/toolkit/src/lib/use-instill-form/transform/transformInstillJSONSchemaToFormTree.ts, packages/toolkit/src/lib/use-instill-form/type.ts, packages/toolkit/src/view/pipeline-builder/components/nodes/end-operator-node/EndOperatorNode.tsx
Because
- fix instillUIMultiline attribute is not working within auto-form
This commit
- fix instillUIMultiline attribute is not working within auto-form
=> fix(auto-form): fix instillUIMultiline attribute is not working within auto-form

packages/toolkit/src/lib/vdp-sdk/pipeline/queries.ts, packages/toolkit/src/view/profile/user-profile/UserProfile.tsx
Because
- user profile update pipeline query
This commit
- user profile update pipeline query
=> chore(user-profile): user profile update pipeline query

packages/toolkit/src/view/pipeline-builder/components/nodes/start-operator-node/StartOperatorNode.tsx, packages/toolkit/src/view/pipeline/view-pipeline/InOutPut.tsx
Because
-  fix start operator json input not working in /pipelines/pid page
This commit
-  fix start operator json input not working in /pipelines/pid page
=> fix: fix start operator json input not working in /pipelines/pid page

packages/design-system/src/new-ui/DropdownMenu/DropdownMenu.tsx, packages/design-system/src/ui/ProgressMessageBoxs/ProgressMessageBoxBase/ProgressMessageBoxBase.tsx, packages/design-system/src/ui/TextAreas/TextAreaBase/TextAreaBase.tsx, packages/design-system/src/ui/TextFields/TextFieldBase/TextFieldBase.tsx, packages/design-system/src/ui/ToggleFields/ToggleFieldBase/ToggleFieldBase.tsx, packages/design-system/src/ui/UploadFileFields/UploadFileFieldBase/UploadFileFieldBase.tsx, packages/eslint-config-cortex/index.js, packages/toolkit/package.json, packages/toolkit/src/components/ClonePipelineDialog.tsx, packages/toolkit/src/components/breadcrumb-with-link/BreadcrumbWithLink.tsx, packages/toolkit/src/components/cells/NameCell.tsx, packages/toolkit/src/components/cells/VisibilityCell.tsx, packages/toolkit/src/lib/airbytes/hooks/useAirbyteFieldValues.ts, packages/toolkit/src/lib/airbytes/types.ts, packages/toolkit/src/lib/dot/index.ts, packages/toolkit/src/lib/store/useCreateResourceFormStore.ts, packages/toolkit/src/lib/tip-tap/markdown.ts, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/AudiosField.tsx, packages/toolkit/src/lib/use-instill-form/transform/transformInstillFormTreeToInitialSelectedCondition.test.ts, packages/toolkit/src/lib/use-instill-form/type.ts, packages/toolkit/src/view/pipeline-builder/Flow.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/connector-node/ConnectorNode.tsx, packages/toolkit/src/view/pipeline-builder/lib/recursiveReplaceNullAndEmptyStringWithUndefined.ts, packages/toolkit/src/view/pipeline/view-pipelines/CreatePipelineDialog.tsx, packages/toolkit/src/view/pipeline/view-pipelines/index.ts, packages/toolkit/src/view/profile/user-profile/UserProfile.tsx, pnpm-lock.yaml, tsconfig.base.json
Because
- make creating private pipeline as default option
This commit
- make creating private pipeline as default option
=> chore: make creating private pipeline as default option

packages/toolkit/src/view/settings/instillUserRoles.ts
Because
- add Marketing into InstillUserRoles
This commit
- add Marketing into InstillUserRoles
=> chore: add Marketing into InstillUserRoles

apps/console/src/pages/[entity]/models/[id].tsx, packages/toolkit/package.json, packages/toolkit/src/view/model/ModelHubSettingPageMainView.tsx
Because
-  fix console fetch the wrong model readme namespace
This commit
-  fix console fetch the wrong model readme namespace
=> fix: fix console fetch the wrong model readme namespace

packages/toolkit/package.json, packages/toolkit/src/lib/react-query-service/pipeline/useInfinitePipelines.ts, packages/toolkit/src/lib/vdp-sdk/helper/getQueryString.ts, packages/toolkit/src/lib/vdp-sdk/pipeline/queries.ts, packages/toolkit/src/view/hub/hub-view/Body.tsx
Because
- filter out logged in user private pipeline on hub
This commit
- filter out logged in user private pipeline on hub
=> fix(hub): filter out logged in user private pipeline on hub

packages/toolkit/src/lib/use-smart-hint/useSmartHint.ts, packages/toolkit/src/view/pipeline-builder/lib/composeEdgesFromReferences.tsx
Because
- fix can not reference comp output and form the edges
This commit
- fix can not reference comp output and form the edges
=> fix(pipeline-builder): fix can not reference comp output and form the edges

apps/console/src/pages/_app.tsx, apps/console/src/styles/tip-tap.css, packages/toolkit/package.json, packages/toolkit/src/lib/tip-tap/extensions.ts, pnpm-lock.yaml
Because
- add the placeholder for the pipeline description editor
This commit
- add the placeholder for the pipeline description editor
=> feat: add the placeholder for the pipeline description editor

apps/console/src/pages/_app.tsx, apps/console/tailwind.config.js, packages/toolkit/src/view/dashboard/PipelineTriggerCountsLineChart.tsx
Because
- fix font not consistent on dashboard and improve the font optimization
This commit
- fix font not consistent on dashboard and improve the font optimization
=> fix: fix font not consistent on dashboard and improve the font optimization

packages/toolkit/src/lib/use-instill-form/useInstillForm.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/connector-node/ConnectorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/operator-node/OperatorNode.tsx, packages/toolkit/src/view/pipeline-builder/lib/getConnectorInputOutputSchema.ts, packages/toolkit/src/view/pipeline-builder/lib/getOperatorInputOutputSchema.ts
Because
- fix the component output not react to the selected task
This commit
- fix the component output not react to the selected task
=> fix(pipeline-builder): fix the component output not react to the selected task

packages/toolkit/package.json, packages/toolkit/src/view/pipeline/view-pipeline/Head.tsx, packages/toolkit/src/view/pipeline/view-pipeline/InOutPut.tsx
Because
- add loading state into pipelines/pid page to increase ux
This commit
- add loading state into pipelines/pid page to increase ux
=> feat: add loading state into pipelines/pid page to increase ux

apps/console/src/pages/_app.tsx, packages/toolkit/src/components/ClonePipelineDialog.tsx, packages/toolkit/src/lib/vdp-sdk/pipeline/mutations.ts, packages/toolkit/src/view/hub/hub-view/HubView.tsx, packages/toolkit/src/view/pipeline/view-pipeline/Head.tsx
Because
- fix duplicate pipeline didnt carry over pipeline brief
This commit
- fix duplicate pipeline didnt carry over pipeline brief
=> fix: fix duplicate pipeline didnt carry over pipeline brief

packages/toolkit/package.json, packages/toolkit/src/components/card-pipeline/Footer.tsx, packages/toolkit/src/view/pipeline-builder/FlowControl.tsx, packages/toolkit/src/view/pipeline/view-pipeline/Head.tsx, packages/toolkit/src/view/pipeline/view-pipeline/InOutPut.tsx, packages/toolkit/src/view/pipeline/view-pipeline/ViewPipeline.tsx
Because
- fix log in to clone not correctly redirect user to login
This commit
- fix log in to clone not correctly redirect user to login
=> fix: fix log in to clone not correctly redirect user to login

packages/toolkit/src/view/pipeline-builder/components/nodes/connector-node/ConnectorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/connector-node/ResourceNotCreatedWarning.tsx
Because
- improve the connector is not specified warning on the pipeline-builder component
This commit
- improve the connector is not specified warning on the pipeline-builder component
=> feat(pipeline-builder): improve the connector is not specified warning on the pipeline-builder component

packages/toolkit/src/lib/use-instill-form/components/component-output/MDTextViewer.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/SmartHintList.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/TextField.tsx, packages/toolkit/src/lib/use-smart-hint/pickSmartHintsFromAcceptFormats.ts
Because
- fix anchor tag overflow in the component formatted output
This commit
- fix anchor tag overflow in the component formatted output
=> fix: fix anchor tag overflow in the component formatted output

packages/toolkit/src/view/pipeline/view-pipeline/Head.tsx, packages/toolkit/src/view/pipeline/view-pipeline/InOutPut.tsx
Because
- fix the drift of the loading state of /pipelines/pid page
This commit
- fix the drift of the loading state of /pipelines/pid page
=> fix: fix the drift of the loading state of /pipelines/pid page

packages/toolkit/package.json, packages/toolkit/src/view/pipeline/view-pipelines/CreatePipelineDialog.tsx
Because
- improve namespace hint of pipeline creation process
This commit
- improve namespace hint of pipeline creation process
=> fix: improve namespace hint of pipeline creation process

packages/toolkit/package.json, packages/toolkit/src/components/ClonePipelineDialog.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/TextField.tsx, packages/toolkit/src/lib/use-smart-hint/pickSmartHintsFromAcceptFormats.ts, packages/toolkit/src/view/pipeline-builder/components/nodes/connector-node/ConnectorNode.tsx
Because
- improve the namespace hint when clone the pipeline
This commit
- improve the namespace hint when clone the pipeline
=> feat: improve the namespace hint when clone the pipeline

packages/toolkit/package.json, packages/toolkit/src/lib/react-query-service/connector/onSuccessAfterConnectMutation.tsx, packages/toolkit/src/lib/vdp-sdk/connector/actions.ts, packages/toolkit/src/lib/vdp-sdk/connector/mutations.ts, packages/toolkit/src/view/ai/AIResourceAutoForm.tsx, packages/toolkit/src/view/blockchain/BlockchainResourceAutoForm.tsx, packages/toolkit/src/view/data/DataResourceForm.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/connector-node/ConnectorNode.tsx
Because
- fix can't correctly pour in instill-model enum for connector
This commit
- fix can't correctly pour in instill-model enum for connector
=> fix(pipeline-builder): fix can't correctly pour in instill-model enum for connector

packages/toolkit/package.json, packages/toolkit/src/lib/react-query-service/pipeline/useInfinitePipelines.ts, packages/toolkit/src/lib/react-query-service/pipeline/useInfiniteUserPipelines.ts, packages/toolkit/src/lib/react-query-service/pipeline/usePipelines.ts, packages/toolkit/src/lib/react-query-service/pipeline/useUserPipelines.ts, packages/toolkit/src/lib/vdp-sdk/pipeline/queries.ts, packages/toolkit/src/view/hub/hub-view/Body.tsx, packages/toolkit/src/view/pipeline/view-pipelines/ViewPipelines.tsx, packages/toolkit/src/view/profile/user-profile/UserProfile.tsx, pnpm-lock.yaml
Because
- support backend search param for pipelines
This commit
- support backend search param for pipelines
=> feat: support backend search param for pipelines

apps/console/src/middleware.ts, packages/design-system/setupTests.ts, packages/design-system/vitest.config.ts, packages/toolkit/setupTests.ts, packages/toolkit/src/lib/test/utils.tsx, packages/toolkit/src/lib/use-instill-form/components/regular/TextField.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/TextField.tsx, packages/toolkit/src/lib/use-instill-form/useInstillForm.test.tsx
Because
- implement the unit test for nested auto gen form
This commit
- implement the unit test for nested auto gen form
=> feat: implement the unit test for nested auto gen form

apps/console/src/components/OnboardingForm.tsx, packages/toolkit/src/components/ClonePipelineDialog.tsx, packages/toolkit/src/lib/amplitude/helper.ts, packages/toolkit/src/lib/amplitude/type.ts, packages/toolkit/src/view/ai/AIResourceAutoForm.tsx, packages/toolkit/src/view/blockchain/BlockchainResourceAutoForm.tsx, packages/toolkit/src/view/data/DataResourceForm.tsx, packages/toolkit/src/view/model/ConfigureModelForm.tsx, packages/toolkit/src/view/model/CreateModelForm.tsx, packages/toolkit/src/view/pipeline-builder/FlowControl.tsx, packages/toolkit/src/view/pipeline-builder/components/PipelineNameForm.tsx, packages/toolkit/src/view/pipeline-builder/components/dialogs/publish-pipeline-dialog/PublishPipelineDialog.tsx, packages/toolkit/src/view/pipeline-builder/components/dialogs/share-pipeline-dialog/TabShare.tsx, packages/toolkit/src/view/pipeline-builder/components/dialogs/share-pipeline-dialog/UnpublishPipelineDialog.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/start-operator-node/StartOperatorNode.tsx, packages/toolkit/src/view/pipeline/PipelineBuilderMainView.tsx, packages/toolkit/src/view/pipeline/view-pipeline/EditMetadataDialog.tsx, packages/toolkit/src/view/pipeline/view-pipeline/InOutPut.tsx, packages/toolkit/src/view/pipeline/view-pipeline/Readme.tsx, packages/toolkit/src/view/pipeline/view-pipelines/CreatePipelineDialog.tsx, packages/toolkit/src/view/resource/ResourcesTable.tsx, packages/toolkit/src/view/settings/api-tokens/CreateAPITokenDialog.tsx, packages/toolkit/src/view/settings/api-tokens/DeleteAPITokenDialog.tsx, packages/toolkit/src/view/settings/user/UserProfileTab.tsx
Because
- update the amplitude action type
This commit
- update the amplitude action type
=> feat: update the amplitude action type

packages/toolkit/src/lib/use-instill-form/type.ts, packages/toolkit/src/lib/use-instill-form/useInstillForm.test.tsx
Because
- add real-world unit test case for useInstillForm
This commit
- add real-world unit test case for useInstillForm
=> feat(testing): add real-world unit test case for useInstillForm

.github/workflows/integration-test.yml, Dockerfile.playwright, apps/console/integration-test/helpers/env.ts, apps/console/integration-test/helpers/first-time-login.test.ts, apps/console/integration-test/pages/login.page.ts, apps/console/integration-test/pages/onboarding.page.ts, apps/console/integration-test/pages/pipelines.page.ts, apps/console/package.json, apps/console/playwright.config.ts, apps/console/src/pages/login.tsx, docs/integration-test.md, entrypoint-playwright.sh, pnpm-lock.yaml, scripts/docker-run-test.sh
Because
- adapt new page object model and new playwright
This commit
- adapt new page object model and new playwright
=> feat(test): adapt new page object model and new playwright

apps/console/src/components/top-bar/topBarData.tsx, apps/console/src/pages/_app.tsx, apps/console/src/pages/login.tsx, packages/design-system/src/new-ui/Icons/ReferenceIconCheck.tsx, packages/design-system/src/new-ui/Icons/ReferenceIconX.tsx, packages/design-system/src/new-ui/Icons/index.ts, packages/toolkit/src/lib/amplitude/AmplitudeContext.ts, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/AudioField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/AudiosField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/BooleanField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/FieldHead.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/FileField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/FilesField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/ImageField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/ImagesField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/LongTextField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/NumberField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/NumbersField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/ObjectField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/TextField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/TextareaField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/TextsField.tsx, packages/toolkit/src/lib/use-instill-form/pick/pickStartOperatorFreeFormFields.tsx, packages/toolkit/src/lib/use-instill-form/type.ts, packages/toolkit/src/lib/use-instill-form/useStartOperatorTriggerPipelineForm.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/control-panel/StartEndOperatorControlPanel.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/end-operator-node/EndOperatorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/start-operator-node/StartOperatorNode.tsx
Because
- add reference hint at the start operator
This commit
- add reference hint at the start operator
=> feat(pipeline-builder): add reference hint at the start operator

apps/console/src/pages/login.tsx, packages/toolkit/src/components/UserProfileCard.tsx, packages/toolkit/src/lib/react-query-service/pipeline/useInfiniteUserPipelines.ts, packages/toolkit/src/lib/react-query-service/pipeline/useUserPipelines.ts, packages/toolkit/src/lib/vdp-sdk/pipeline/queries.ts, packages/toolkit/src/view/hub/hub-view/Body.tsx, packages/toolkit/src/view/pipeline/view-pipelines/CreatePipelineDialog.tsx, packages/toolkit/src/view/pipeline/view-pipelines/ViewPipelines.tsx, packages/toolkit/src/view/profile/user-profile/UserProfile.tsx
Because
- support filtering the visibility of pipelines
This commit
- support filtering the visibility of pipelines
=> feat: support filtering the visibility of pipelines

packages/toolkit/src/components/ReferenceHintTag.tsx, packages/toolkit/src/components/index.ts, packages/toolkit/src/lib/use-instill-form/components/component-output-reference-hints/ListField.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output-reference-hints/ObjectArrayField.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output-reference-hints/index.ts, packages/toolkit/src/lib/use-instill-form/index.ts, packages/toolkit/src/lib/use-instill-form/pick/pickComponentOutputFieldsFromInstillFormTree.tsx, packages/toolkit/src/lib/use-instill-form/pick/pickComponentsFromReferenceHints.tsx, packages/toolkit/src/lib/use-instill-form/transform/transformInstillFormTreeToReferenceHints.ts, packages/toolkit/src/lib/use-instill-form/type.ts, packages/toolkit/src/lib/use-instill-form/useComponentOutputFields.tsx, packages/toolkit/src/lib/use-instill-form/useComponentOutputReferenceHintFields.tsx, packages/toolkit/src/lib/use-instill-form/useInstillForm.test.tsx, packages/toolkit/src/lib/vdp-sdk/connector/actions.ts, packages/toolkit/src/view/model/CreateModelForm.tsx, packages/toolkit/src/view/pipeline-builder/components/ComponentOutputReferenceHints.tsx, packages/toolkit/src/view/pipeline-builder/components/ComponentOutputs.tsx, packages/toolkit/src/view/pipeline-builder/components/index.ts, packages/toolkit/src/view/pipeline-builder/components/nodes/connector-node/ConnectorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/operator-node/OperatorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/start-operator-node/StartOperatorNode.tsx, packages/toolkit/src/view/pipeline-builder/lib/getReferencesFromString.ts, packages/toolkit/src/view/pipeline/view-pipelines/CreatePipelineDialog.tsx, packages/toolkit/src/view/pipeline/view-pipelines/ViewPipelines.tsx
Because
- implement the new component output reference hint design
This commit
- implement the new component output reference hint design
=> feat(pipeline-builder): implement the new component output reference hint design

packages/toolkit/src/lib/react-json-view/customTheme.tsx, packages/toolkit/src/lib/react-json-view/index.ts, packages/toolkit/src/view/pipeline-builder/components/nodes/common/node-bottom-bar/NodeBottomBarContent.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/common/node-bottom-bar/NodeBottomBarOutput.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/common/node-bottom-bar/NodeBottomBarSchema.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/connector-node/ConnectorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/operator-node/OperatorNode.tsx
Because
- User can better debug their component by using the new schema and data output view
This commit
- User can better debug their component by using the new schema and data output view
=> feat(pipeline-builder): User can better debug their component by using the new schema and data output view

packages/toolkit/src/lib/use-instill-form/transform/transformInstillJSONSchemaToZod.test.ts, packages/toolkit/src/view/pipeline-builder/components/ComponentFormOnRightPanel.tsx, packages/toolkit/src/view/pipeline-builder/components/useUpdaterOnNode.tsx, packages/toolkit/src/view/pipeline-builder/components/useUpdaterOnRightPanel.tsx
Because
- fix pipeline-builder updater update the form on every input
This commit
- fix pipeline-builder updater update the form on every input
=> fix(pipeline-builder): fix pipeline-builder updater update the form on every input

packages/design-system/tsconfig.json, packages/toolkit/src/components/ClonePipelineDialog.tsx, packages/toolkit/src/components/CopyToClipboardButton.tsx, packages/toolkit/src/components/ReferenceHintTag.tsx, packages/toolkit/src/components/card-pipeline/Footer.tsx, packages/toolkit/src/components/card-pipeline/Menu.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output-reference-hints/GroupByFormatField.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output-reference-hints/ListField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/FieldHead.tsx, packages/toolkit/src/view/pipeline-builder/Flow.tsx, packages/toolkit/src/view/pipeline-builder/components/ComponentOutputReferenceHints.tsx, packages/toolkit/src/view/pipeline-builder/components/ComponentOutputs.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/common/node-bottom-bar/NodeBottomBarOutput.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/common/node-bottom-bar/NodeBottomBarSchema.tsx, packages/toolkit/src/view/pipeline-builder/components/useUpdaterOnRightPanel.tsx, packages/toolkit/src/view/pipeline/view-pipeline/EditMetadataDialog.tsx, packages/toolkit/src/view/pipeline/view-pipeline/Head.tsx
Because
- hide edit/delete button of start input into dropdown
This commit
- hide edit/delete button of start input into dropdown
=> feat(pipeline-builder): hide edit/delete button of start input into dropdown

packages/toolkit/src/view/pipeline/view-pipeline/Head.tsx
Because
- fix /pipelines/pid head page description and button not align issue
This commit
- fix /pipelines/pid head page description and button not align issue
=> fix: fix /pipelines/pid head page description and button not align issue

packages/toolkit/src/view/pipeline-builder/components/nodes/connector-node/DataConnectorFreeForm.tsx
Because
- cannot delete connector free-form field
This commit
- cannot delete connector free-form field
=> fix(connector): cannot delete connector free-form field

packages/toolkit/src/lib/amplitude/type.ts
Because
- add subscription related amplitude event
This commit
- add subscription related amplitude event
=> feat(tracking): add subscription related amplitude event

packages/toolkit/src/lib/react-query-service/connector/onSuccessAfterConnectMutation.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/TextField.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/connector-node/ConnectorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/end-operator-node/EndOperatorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/end-operator-node/EndOperatorNodeFreeForm.tsx, packages/toolkit/src/view/pipeline/view-pipeline/InOutPut.tsx
Because
- make end operator free form field be consistent with start operator
This commit
- make end operator free form field be consistent with start operator
=> feat(pipeline-builder): make end operator free form field be consistent with start operator

packages/toolkit/src/components/ReferenceHintDataTypeTag.tsx, packages/toolkit/src/components/ReferenceHintTag.tsx, packages/toolkit/src/components/index.ts, packages/toolkit/src/lib/use-instill-form/components/component-output-reference-hints/GroupByFormatField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/FieldHead.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/control-panel/StartEndOperatorControlPanel.tsx
Because
- update the style of reference tag and data type tag
This commit
- update the style of reference tag and data type tag
=> feat(pipeline-builder): update the style of reference tag and data type tag

packages/toolkit/src/components/ReferenceHintTag.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output-reference-hints/GroupByFormatField.tsx, packages/toolkit/src/lib/use-instill-form/useInstillForm.test.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/end-operator-node/EndOperatorNodeFreeForm.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/end-operator-node/UserDefinedFieldItem.tsx
Because
- reference hint tag style and reference path are wrong
This commit
- fix reference hint tag style and wrong reference path
=> fix: fix reference hint tag style and wrong reference path

packages/toolkit/src/view/settings/user/UserProfileTab.tsx
Because
- add id to user profile bio
This commit
- add id to user profile bio
=> chore(user-profile): add id to user profile bio for better URL navigation

packages/toolkit/src/lib/use-instill-form/components/smart-hint/SmartHintInfoCard.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/SmartHintList.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/TextArea.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/TextField.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/getFieldPlaceholder.tsx, packages/toolkit/src/lib/use-instill-form/transform/index.ts, packages/toolkit/src/lib/use-instill-form/transform/transformInstillFormatToHumanReadableFormat.tsx, packages/toolkit/src/lib/use-instill-form/type.ts
Because
- We envision a better smart hint flow to reduce the overwhelmed feeling when building the pipeline
This commit
- implement the layered flow of smart hint
=> feat(pipeline-builder): implement the layered flow of smart hint

packages/toolkit/src/lib/useEntity.ts, packages/toolkit/src/view/profile/user-profile-view/UserProfileView.tsx
Because
- We should re-direct non exist view to 404
This commit
- fix not redirect non exist user page to 404
=> fix: fix not redirect non exist user page to 404

packages/toolkit/src/lib/use-instill-form/pick/pickRegularFieldsFromInstillFormTree.tsx, packages/toolkit/src/lib/use-instill-form/useComponentOutputFields.tsx, packages/toolkit/src/view/pipeline-builder/components/useUpdaterOnRightPanel.tsx
Because
- task description not react to the selected task
This commit
- fix task description not react to the selected task
=> fix(pipeline-builder): fix task description not react to the selected task

packages/toolkit/src/view/pipeline/view-pipelines/ViewPipelines.tsx
Because
- add visibility all label to dropdown
This commit
- add visibility all label to dropdown
=> chore(instill-hub): add visibility all label to dropdown

packages/toolkit/src/view/dashboard/PipelineTriggerCountsLineChart.tsx
Because
- fix dashboard font-family issue
This commit
- fix dashboard font-family issue
=> fix: fix dashboard font-family issue

packages/toolkit/package.json, packages/toolkit/src/lib/vdp-sdk/types.ts
Because
- add SubscriptionStatus to sdk
This commit
- add SubscriptionStatus to sdk
=> feat: add SubscriptionStatus to sdk

packages/toolkit/src/view/pipeline/view-pipeline/Head.tsx, packages/toolkit/src/view/pipeline/view-pipeline/InOutPut.tsx, packages/toolkit/src/view/pipeline/view-pipeline/ViewPipeline.tsx
Because
- We didn't consider the situation that pipeline. may not be versioned, cause the pipeline's input not correctly displayed
This commit
- fix pipelines/pid pipeline input not correctly displayed
=> fix: fix pipelines/pid pipeline input not correctly displayed

packages/toolkit/package.json, packages/toolkit/src/view/dashboard/DashboardPipelineDetailsPageMainView.tsx, packages/toolkit/src/view/dashboard/DashboardPipelineListPageMainView.tsx, packages/toolkit/src/view/resource/ResourceListPageMainView.tsx, packages/toolkit/src/view/resource/ResourceSettingPageMainView.tsx, packages/toolkit/src/view/settings/user/UserAPITokenTab.tsx, packages/toolkit/src/view/settings/user/UserAccountTab.tsx, packages/toolkit/src/view/settings/user/UserProfileTab.tsx
Because
- fix the navigation problem on organization profile and dashboard page
This commit
- fix the navigation problem on organization profile and dashboard page
=> fix: fix the navigation problem on organization profile and dashboard page

packages/toolkit/src/view/pipeline-builder/components/nodes/start-operator-node/StartOperatorNode.tsx
Because
- fix user can not edit start operator field
This commit
- fix user can not edit start operator field
=> fix(pipeline-builder): fix user can not edit start operator field

packages/toolkit/src/view/pipeline-builder/Flow.tsx, packages/toolkit/src/view/pipeline-builder/components/CustomEdge.tsx, packages/toolkit/src/view/pipeline-builder/components/CustomHandle.tsx
Because
- support the optimized connection line style
- Elevated edge when select on node to highlight the selected edges
This commit
- support the optimized connection line style
=> feat(pipeline-builder): support the optimized connection line style

packages/toolkit/package.json, packages/toolkit/src/lib/vdp-sdk/types.ts
Because
- Align with backend's protobuf
This commit
- add subscription detail field into StripeSubscriptionDetail type
=> feat: add subscription detail field into StripeSubscriptionDetail type

packages/toolkit/src/view/pipeline-builder/Flow.tsx, packages/toolkit/src/view/pipeline-builder/components/CustomEdge.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/common/NodeWrapper.tsx
Because
- selected edges is covered on top of node
This commit
- fix selected edges is covered on top of node
=> fix(pipeline-builder): fix selected edges is covered on top of node

apps/console/src/lib/useAccessToken.ts
Because
- Console need this changes to bump up a minor version
This commit
- prepare for console 0.40.0-beta release
=> feat: prepare for console 0.40.0-beta release

packages/toolkit/src/lib/use-instill-store/pipelineBuilderSlice.ts, packages/toolkit/src/lib/use-instill-store/types.ts, packages/toolkit/src/view/pipeline-builder/components/nodes/common/NodeDropdownMenu.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/common/NodeIDEditor.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/connector-node/DataConnectorFreeForm.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/start-operator-node/StartOperatorNode.tsx
Because
- The testModeEnabled is out-of-date
This commit
- remove the testModeEnabled flag
=> chore: remove the testModeEnabled flag

packages/design-system/src/new-ui/Icons/InfoSquare.tsx, packages/design-system/src/new-ui/Icons/index.ts, packages/toolkit/src/components/ImageWithFallback.tsx, packages/toolkit/src/components/ReferenceHintTag.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output-reference-hints/GroupByFormatField.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output-reference-hints/ListField.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output-reference-hints/ObjectArrayField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/FieldHead.tsx, packages/toolkit/src/lib/use-instill-form/pick/pickComponentsFromReferenceHints.tsx, packages/toolkit/src/lib/use-instill-form/pick/pickStartOperatorFreeFormFieldItems.tsx, packages/toolkit/src/lib/use-instill-form/transform/transformInstillFormTreeToReferenceHints.ts, packages/toolkit/src/lib/use-instill-form/types.ts, packages/toolkit/src/lib/use-smart-hint/transformConnectorComponentFormTreeToSmartHints.test.ts, packages/toolkit/src/lib/use-smart-hint/transformConnectorComponentFormTreeToSmartHints.ts, packages/toolkit/src/lib/use-smart-hint/transformStartOperatorFieldsToSmartHints.ts, packages/toolkit/src/lib/use-smart-hint/types.ts, packages/toolkit/src/view/pipeline-builder/components/ComponentOutputReferenceHints.tsx, packages/toolkit/src/view/pipeline-builder/components/dialogs/select-component-dialog/ExistingConnectorSection.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/common/NodeIDEditor.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/connector-node/ConnectorNode.tsx
Because
- We have new design for reference hint
This commit
- add the new design for reference link
=> feat: add the new design for reference hint

.github/workflows/integration-test.yml
Because
- e2e test is outdated(Still using the old VDP project structure)
This commit
- revamp outdated e2e test
=> fix: revamp outdated e2e test

Dockerfile, packages/design-system/package.json, packages/toolkit/package.json
Because
- console docker version is out of date
This commit
- fix docker node version
=> fix: fix docker node version

packages/toolkit/src/lib/use-smart-hint/pickSmartHintsFromNodes.ts
Because
- Make smart hint smarter
This commit
- user can use iterator_a's output as iterator_b's input
=> feat(pipeline-builder):  user can use iterator_a's output as iterator_b's input

packages/toolkit/package.json, packages/toolkit/src/components/top-bar/Topbar.tsx
Because
- Hub link on topbar wrongly redirect user to /entity/hub
This commit
-  fix hub link is not working on Topbar
=> fix: fix hub link is not working on Topbar

.github/workflows/integration-test.yml, packages/toolkit/package.json, packages/toolkit/src/lib/use-smart-hint/output-reference-hint/pickFieldsFromOutputReferenceHints.tsx, packages/toolkit/src/lib/use-smart-hint/output-reference-hint/pickOutputReferenceHintsFromComponent.tsx, packages/toolkit/src/lib/use-smart-hint/output-reference-hint/useOutputReferenceHintsFields.tsx, packages/toolkit/src/view/pipeline-builder/components/iterator-editor/iterator-output/DeleteOutputButton.tsx, packages/toolkit/src/view/pipeline-builder/components/iterator-editor/iterator-output/IteratorOutput.tsx, packages/toolkit/src/view/pipeline-builder/components/iterator-editor/iterator-output/OutputValueInput.tsx, packages/toolkit/src/view/pipeline-builder/lib/hooks/useSavePipeline.tsx
Because
- support directly input reference value in iterator
This commit
- support directly input reference value in iterator
=> feat(pipeline-builder): support directly input reference value in iterator

packages/toolkit/package.json, packages/toolkit/src/lib/use-instill-form/pick/pickComponentOutputFieldsFromInstillFormTree.tsx, packages/toolkit/src/lib/use-instill-form/pick/pickRegularFieldsFromInstillFormTree.tsx, packages/toolkit/src/lib/use-instill-form/transform/transformInstillFormTreeToDefaultValue.ts, packages/toolkit/src/lib/use-instill-form/transform/transformInstillFormTreeToReferenceHints.ts, packages/toolkit/src/lib/use-instill-form/transform/transformInstillFormatToHumanReadableFormat.tsx, packages/toolkit/src/lib/use-instill-form/transform/transformInstillJSONSchemaToFormTree.ts, packages/toolkit/src/lib/use-instill-form/types.ts, packages/toolkit/src/lib/use-smart-hint/output-reference-hint/fields/GroupByFormatField.tsx, packages/toolkit/src/lib/use-smart-hint/output-reference-hint/pickFieldsFromOutputReferenceHints.tsx, packages/toolkit/src/lib/use-smart-hint/output-reference-hint/pickOutputReferenceHintsFromComponent.tsx, packages/toolkit/src/lib/use-smart-hint/transformConnectorComponentFormTreeToSmartHints.test.ts, packages/toolkit/src/lib/use-smart-hint/transformFormTreeToSmartHints.ts, packages/toolkit/src/view/pipeline-builder/components/top-control-menu/Run.tsx, packages/toolkit/src/view/pipeline-builder/components/top-control-menu/Save.tsx
Because
- we are lacking the support of array in array hint and display
This commit
- introduce arrayArray type in InstillFormTree to handle array in array
=> feat(pipeline-builder): introduce arrayArray type in InstillFormTree to handle array in array

packages/toolkit/package.json, packages/toolkit/src/view/pipeline-builder/components/CustomEdge.tsx
Because
- adapt the new default edge color
This commit
- adapt the new default edge color
=> feat(pipeline-builder): adapt the new default edge color

packages/toolkit/package.json, packages/toolkit/src/view/hub/hub-view/Body.tsx, packages/toolkit/src/view/pipeline-builder/components/dialogs/publish-pipeline-dialog/PublishPipelineDialog.tsx, packages/toolkit/src/view/pipeline/view-pipelines/ViewPipelines.tsx
Because
- fix the search function cause re-render issue on the hub page
This commit
- fix the search function cause re-render issue on the hub page
=> fix: fix the search function cause re-render issue on the hub page

apps/console/integration-test/constant/test-id.ts, apps/console/integration-test/data-testid.ts, apps/console/integration-test/helpers/component-helpers/dropdown.ts, apps/console/integration-test/helpers/component-helpers/select.ts, apps/console/integration-test/pages/connector-list.ts, apps/console/integration-test/pages/pipeline-builder.page.ts, apps/console/integration-test/tests/should-change-component-id.test.ts, apps/console/integration-test/tests/should-unmarshal.test.ts, apps/console/package.json, apps/console/playwright.config.ts, packages/toolkit/src/components/GeneralDeleteResourceDialog.tsx, packages/toolkit/src/constant/data-testid.ts, packages/toolkit/src/constant/index.ts, packages/toolkit/src/view/pipeline-builder/components/dialogs/select-component-dialog/SelectComponentDialog.tsx, packages/toolkit/src/view/pipeline-builder/components/dialogs/set-up-component-dialog/SetupComponentDialog.tsx, packages/toolkit/src/view/pipeline-builder/components/dialogs/set-up-component-dialog/index.ts, packages/toolkit/src/view/pipeline-builder/components/index.ts, packages/toolkit/src/view/pipeline-builder/components/nodes/common/NodeIDEditor.tsx, packages/toolkit/src/view/pipeline-builder/components/top-control-menu/TopControlMenu.tsx, packages/toolkit/src/view/pipeline/view-pipelines/CreatePipelineDialog.tsx, packages/toolkit/src/view/resource/ResourcesTable.tsx
Because
- pipeline-builder not correctly update component id
This commit
- fix pipeline-builder not correctly update component id
- add corresponding test
=> fix(pipeline-builder, test): fix pipeline-builder not correctly update component id

apps/console/integration-test/helpers/actions/connector.ts, apps/console/integration-test/helpers/actions/pipeline.ts, apps/console/integration-test/main.test.ts, apps/console/integration-test/pages/pipeline-builder.page.ts, apps/console/integration-test/tests/should-change-component-id.test.ts, apps/console/integration-test/tests/should-edit-create-start-end-field.test.ts, apps/console/integration-test/tests/should-unmarshal.test.ts, apps/console/package.json, apps/console/playwright.config.ts, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/FieldHead.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/end-operator-node/EndOperatorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/end-operator-node/UserDefinedFieldItem.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/start-operator-node/StartNodeInputType.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/start-operator-node/StartOperatorNode.tsx
Because
- console not correctly guard duplicated start/end operator field
https://github.com/instill-ai/console/assets/57251712/cc03829a-e8f5-4657-9f82-931e1120e5bd
This commit
-  fix not correctly guard duplicated start/end operator field
=> fix(pipeline-builder, test): fix not correctly guard duplicated start/end operator field

packages/toolkit/package.json, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/AudiosField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/FilesField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/ImagesField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/VideosField.tsx, packages/toolkit/src/lib/use-instill-form/transform/transformStartOperatorFieldsToZod.ts, packages/toolkit/src/lib/use-instill-form/transform/transformStartOperatorMetadataToSuperRefineRules.ts, packages/toolkit/src/view/pipeline/PipelinesTable.tsx
Because
- wrongly validate start operator form when delete array type items
This commit
- fix wrongly validate start operator form when delete array type items
=> fix(pipeline-builder): fix wrongly validate start operator form when delete array type items

packages/toolkit/src/components/top-bar/AppTopbar.tsx, packages/toolkit/src/components/top-bar/Topbar.tsx, packages/toolkit/src/view/not-found/NotFoundView.tsx
Because
- docs url and navbar update
This commit
- docs url and navbar update
=> fix: docs url and navbar update

packages/toolkit/package.json, packages/toolkit/src/view/pipeline/PipelinesTable.tsx
Because
- The link is not working, should be an issue of navigation between page route and app route
This commit
- fix pipelines table navigation issue on user/organization profile page
=> fix: fix pipelines table navigation issue on user/organization profile page

packages/toolkit/src/components/card-pipeline/CardPipeline.tsx, packages/toolkit/src/view/hub/hub-view/Body.tsx
Because
- clear rendered card after next call
This commit
- clear rendered card after next call
=> fix(hub): clear rendered card after next call

apps/console/integration-test/main.test.ts
Because
- enable e2e testing
This commit
- enable e2e testing
=> chore: enable e2e testing

apps/console/integration-test/tests/should-change-component-id.test.ts, apps/console/integration-test/tests/should-edit-create-start-end-field.test.ts, apps/console/integration-test/tests/should-unmarshal.test.ts
Because
- stabilize test related to save pipeline action
This commit
- stabilize test related to save pipeline action
=> chore: stabilize test related to save pipeline action

apps/console/integration-test/tests/should-change-component-id.test.ts, apps/console/integration-test/tests/should-edit-create-start-end-field.test.ts, apps/console/src/app/[entity]/page.tsx, apps/console/src/app/[entity]/pipelines/[id]/page.tsx, apps/console/src/components/ConsoleCorePageHead.tsx, apps/console/src/pages/404.tsx, apps/console/src/pages/[entity]/connectors/[id].tsx, apps/console/src/pages/[entity]/connectors/index.tsx, apps/console/src/pages/[entity]/dashboard/index.tsx, apps/console/src/pages/[entity]/dashboard/pipeline/[id].tsx, apps/console/src/pages/[entity]/models/[id].tsx, apps/console/src/pages/[entity]/models/create.tsx, apps/console/src/pages/[entity]/models/index.tsx, apps/console/src/pages/[entity]/pipelines/[id]/builder.tsx, apps/console/src/pages/[entity]/pipelines/index.tsx, apps/console/src/pages/settings/api-tokens.tsx
Because
- Some title is using Pascal case some doesn't. This PR unify this behavior
This commit
- make the page title consistent using Pascal Case
=> chore: make the page title consistent using Pascal Case

packages/toolkit/package.json, packages/toolkit/src/view/pipeline-builder/PipelineBuilderMainView.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/start-operator-node/StartComponentFields.tsx
Because
- array:string configuration is wrong
This commit
- fix start operator field select type
=> fix: fix start operator field select type

apps/console/src/app/render.tsx, packages/toolkit/src/components/top-bar/AppTopbar.tsx, packages/toolkit/src/components/top-bar/CETopbarDropdown.tsx, packages/toolkit/src/components/top-bar/CloudTopbarDropdown.tsx, packages/toolkit/src/components/top-bar/Topbar.tsx, packages/toolkit/src/lib/hook/index.ts, packages/toolkit/src/lib/hook/useGuardPipelineBuilderUnsavedChangesNavigation.ts, packages/toolkit/src/lib/index.ts, packages/toolkit/src/lib/pathname-evaluator/index.ts, packages/toolkit/src/lib/pathname-evaluator/is-pipeline-builder-page.ts, packages/toolkit/src/lib/pathname-evaluator/is-pipeline-overview-page.ts, packages/toolkit/src/view/pipeline-builder/components/top-control-menu/TopControlMenu.tsx
Because
- Wrongly guard navigation when the page is not on builder page
This commit
- fix wrongly guard non builder page navigation
=> fix: fix wrongly guard non builder page navigation

packages/toolkit/src/components/cells/TableCell.tsx, packages/toolkit/src/view/dashboard/DashboardPipelinesTable.tsx, packages/toolkit/src/view/pipeline/PipelinesTable.tsx
Because
- hover:underline css style in Nextjs Link element will block navigation
This commit
- fix underline issue
=> fix: temp fix hover:underline in Link element issue

apps/console/src/app/layout.tsx, apps/console/src/app/render.tsx, apps/console/src/app/sitemap.ts
Because
- Sitemap generation un-expectly throw error cause the build process to fall
This commit
- fix sitemap generation error block building process
=> fix: fix sitemap generation error block building process

apps/console/src/app/render.tsx, packages/toolkit/src/components/ClonePipelineDialog.tsx, packages/toolkit/src/lib/use-instill-form/components/regular/SingleSelectField.tsx, packages/toolkit/src/lib/use-instill-form/pick/index.ts, packages/toolkit/src/lib/use-instill-form/pick/pickDefaultCondition.ts, packages/toolkit/src/lib/use-instill-form/pick/pickRegularFieldsFromInstillFormTree.tsx, packages/toolkit/src/lib/use-instill-form/pick/pickSelectedConditionMap.ts, packages/toolkit/src/lib/use-instill-form/transform/recursivelyResetFormData.ts, packages/toolkit/src/lib/use-instill-form/transform/transformInstillFormTreeToDefaultValue.ts, packages/toolkit/src/lib/use-instill-form/transform/transformInstillJSONSchemaToFormTree.test.ts, packages/toolkit/src/lib/use-instill-form/transform/transformInstillJSONSchemaToFormTree.ts, packages/toolkit/src/lib/use-instill-form/transform/transformInstillJSONSchemaToZod.ts, packages/toolkit/src/lib/vdp-sdk/pipeline/types.ts, packages/toolkit/src/view/pipeline-builder/components/nodes/connector-node/ConnectorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/right-panel/ComponentFormOnRightPanel.tsx, packages/toolkit/src/view/pipeline-builder/lib/checkIsValidPosition.test.ts, packages/toolkit/src/view/pipeline-builder/lib/checkIsValidPosition.ts, packages/toolkit/src/view/pipeline-builder/lib/composeEdgesFromNodes.test.ts, packages/toolkit/src/view/pipeline-builder/lib/composePipelineMetadataFromNodes.test.ts, packages/toolkit/src/view/pipeline-builder/lib/constructPipelineRecipeFromNodes.tsx, packages/toolkit/src/view/pipeline-builder/lib/createNodesFromPipelineRecipe.tsx, packages/toolkit/src/view/pipeline-builder/lib/getConnectorOperatorComponentConfiguration.ts, packages/toolkit/src/view/pipeline-builder/lib/hooks/useConstructNodeFromDefinition.tsx, packages/toolkit/src/view/pipeline-builder/lib/hooks/usePipelineBuilderGraph.tsx, packages/toolkit/src/view/pipeline-builder/lib/hooks/useUpdaterOnNode.tsx, packages/toolkit/src/view/pipeline-builder/lib/hooks/useUpdaterOnRightPanel.tsx
Because
- auto-gen-form didn't support some edges case like input the array of string as ["foo", "bar"]
This commit
- refactor auto gen form to make it more flexible
=> feat: refactor auto gen form to make it more flexible 

apps/console/src/app/settings/secrets/page.tsx, apps/console/src/app/settings/secrets/render.tsx, packages/toolkit/package.json, packages/toolkit/src/lib/amplitude/type.ts, packages/toolkit/src/lib/react-query-service/pipeline/index.ts, packages/toolkit/src/lib/react-query-service/pipeline/useDeleteUserSecret.ts, packages/toolkit/src/view/settings/api-tokens/DeleteAPITokenDialog.tsx, packages/toolkit/src/view/settings/index.ts, packages/toolkit/src/view/settings/secrets/CreateSecretDialog.tsx, packages/toolkit/src/view/settings/secrets/DeleteSecretDialog.tsx, packages/toolkit/src/view/settings/secrets/SecretTable.tsx, packages/toolkit/src/view/settings/secrets/index.ts, packages/toolkit/src/view/settings/user/UserAPITokenTab.tsx, packages/toolkit/src/view/settings/user/UserSecretTab.tsx, packages/toolkit/src/view/settings/user/UserSidebar.tsx, packages/toolkit/src/view/settings/user/index.ts
Because
- implement the UI of secret management service
This commit
- implement the UI of secret management service
=> feat: implement the UI of secret management service

packages/toolkit/package.json, packages/toolkit/src/lib/use-instill-form/components/smart-hint/TextField.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/useFilteredHints.tsx, packages/toolkit/src/lib/use-instill-form/components/trigger-request-form-fields/FieldHead.tsx, packages/toolkit/src/lib/use-instill-form/pick/pickRegularFieldsFromInstillFormTree.tsx, packages/toolkit/src/lib/use-instill-form/useInstillForm.tsx, packages/toolkit/src/lib/use-instill-store/generalSlice.ts, packages/toolkit/src/lib/use-instill-store/types.ts, packages/toolkit/src/lib/use-smart-hint/output-reference-hint/fields/ListField.tsx, packages/toolkit/src/lib/use-smart-hint/transformPipelineTriggerRequestFieldsToSmartHints.ts, packages/toolkit/src/view/pipeline-builder/PipelineBuilderMainView.tsx, packages/toolkit/src/view/pipeline-builder/components/dialogs/select-component-dialog/OperatorSection.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/connector-node/ConnectorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/operator-node/OperatorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/right-panel/ComponentFormOnRightPanel.tsx, packages/toolkit/src/view/pipeline-builder/lib/hooks/useUpdaterOnRightPanel.tsx, packages/toolkit/src/view/settings/user/UserSecretTab.tsx
Because
- support hinting secret in smart hint system
This commit
- support hinting secret in smart hint system
=> feat(pipeline-builder): support hinting secret in smart hint system

packages/toolkit/src/components/ClonePipelineDialog.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/response-node/ResponseNodeFreeForm.tsx
Because
- request membership only when clone pipeline dialog is open to reduce initial network request
This commit
- request membership only when clone pipeline dialog is open
=> feat: request membership only when clone pipeline dialog is open

packages/toolkit/package.json, packages/toolkit/src/lib/use-instill-form/pick/pickComponentOutputFieldsFromInstillFormTree.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/common/NodeDropdownMenu.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/common/NodeIDEditor.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/control-panel/ConnectorOperatorControlPanel.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/control-panel/ControlPanel.tsx
Because
- fix pipeline builder output not correctly output structured data
This commit
- fix pipeline builder output not correctly output structured data
=> fix(pipeline-builder): fix pipeline builder output not correctly output structured data

apps/console/integration-test/pages/pipeline-builder.page.ts, apps/console/integration-test/tests/should-change-component-id.test.ts, apps/console/src/app/api/remove-user-cookie/route.ts, apps/console/src/lib/use-app-access-token/client.ts, packages/toolkit/package.json, packages/toolkit/src/view/pipeline-builder/lib/constructPipelineRecipeFromNodes.tsx
Because
- fix not correctly parse component input in iterator
This commit
- fix not correctly parse component input in iterator
=> fix: fix not correctly parse component input in iterator

packages/toolkit/package.json, packages/toolkit/src/components/UserProfileCard.tsx, packages/toolkit/src/lib/react-query-service/pipeline/use-user-secrets/client.ts, packages/toolkit/src/view/pipeline/view-pipelines/ViewPipelines.tsx
Because
- fix organization list on user profile card is missing
This commit
- fix organization list on user profile card is missing
=> fix: fix organization list on user profile card is missing

apps/console/src/app/(providers)/root-provider.tsx, packages/toolkit/package.json, packages/toolkit/src/lib/use-instill-store/pipelineBuilderSlice.ts, packages/toolkit/src/lib/use-instill-store/types.ts
Because
- fix wrongly initiate the iterator state
This commit
- fix wrongly initiate the iterator state
=> fix(pipeline-builder): fix wrongly initiate the iterator state

packages/toolkit/src/view/pipeline-builder/components/BackToLatestVersionTopBar.tsx, packages/toolkit/src/view/pipeline-builder/components/BottomBar.tsx, packages/toolkit/src/view/pipeline-builder/components/PipelineToolkitDialog.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/iterator-node/IteratorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/top-control-menu/Toolkit.tsx, packages/toolkit/src/view/pipeline-builder/lib/checkIsValidPosition.test.ts, packages/toolkit/src/view/pipeline-builder/lib/checkIsValidPosition.ts, packages/toolkit/src/view/pipeline-builder/lib/composeCompleteNodesUnderEditingIteratorMode.tsx, packages/toolkit/src/view/pipeline-builder/lib/constructPipelineRecipeFromNodes.tsx, packages/toolkit/src/view/pipeline-builder/lib/hooks/usePipelineBuilderGraph.tsx, packages/toolkit/src/view/pipeline-builder/lib/hooks/useSavePipeline.tsx
Because
- fix not correctly display nodes position in iterator
This commit
- fix not correctly display nodes position in iterator
=> fix(pipeline-builder): fix not correctly display nodes position in iterator

packages/toolkit/src/lib/useAppEntity.ts, packages/toolkit/src/view/dashboard/DashboardPipelineDetailsPageMainView.tsx, packages/toolkit/src/view/dashboard/DashboardPipelineListPageMainView.tsx
Because
- useAppEntity unmaturly return object that is not complete, cause Dashboard to query wrong entity
This commit
- fix wrongly return entity object on useAppEntity causing issue on Dashboard
=> fix: fix wrongly return entity object on useAppEntity causing issue on Dashboard

apps/console/src/app/[entity]/pipelines/[id]/render.tsx, packages/toolkit/src/lib/react-query-service/pipeline/useCreateUserPipelineRelease.ts, packages/toolkit/src/lib/useAppEntity.ts, packages/toolkit/src/view/pipeline/view-pipeline/Head.tsx, packages/toolkit/src/view/pipeline/view-pipeline/Readme.tsx, packages/toolkit/src/view/pipeline/view-pipeline/ViewPipeline.tsx
Because
- fix pipeline-view head button and style
This commit
- fix pipeline-view head button and style
=> fix: fix pipeline-view head button and style

packages/toolkit/src/lib/use-instill-form/components/smart-hint/TextArea.tsx, packages/toolkit/src/lib/use-instill-form/pick/pickRegularFieldsFromInstillFormTree.tsx
Because
- fix we can not hint secrets on TextArea
This commit
- fix we can not hint secrets on TextArea
=> fix(pipeline-builder): fix we can not hint secrets on TextArea

packages/toolkit/src/lib/use-instill-form/pick/pickComponentOutputFieldsFromInstillFormTree.tsx
Because
- fix wrongly handle singular object type
This commit
- fix wrongly handle singular object type
=> fix(auto-gen-form): fix wrongly handle singular object type

packages/toolkit/src/view/pipeline-builder/components/dialogs/select-component-dialog/NewConnectorSection.tsx
Because
- fix typo
This commit
- fix typo
=> fix(pipeline-builder): update New Connectors to Connectors

.github/CONTRIBUTING.md
Because
- Typo
This commit
- Fix typo
=> fix(docs): typo CONTRIBUTING.md

.github/CONTRIBUTING.md
Because
- Using deprecated core link
This commit
- Update core link
=> fix(docs): fix typo CONTRIBUTING.md

packages/design-system/src/new-ui/Select/Select.stories.tsx, packages/design-system/src/new-ui/Select/Select.tsx, packages/toolkit/src/components/ClonePipelineDialog.tsx, packages/toolkit/src/lib/use-instill-form/components/regular/CollapsibleFormGroup.tsx, packages/toolkit/src/lib/use-instill-form/components/regular/OneOfConditionField.tsx, packages/toolkit/src/lib/use-instill-form/components/regular/SingleSelectField.tsx, packages/toolkit/src/lib/use-instill-form/components/regular/index.ts, packages/toolkit/src/lib/use-instill-form/pick/pickRegularFieldsFromInstillFormTree.tsx, packages/toolkit/src/lib/use-instill-form/useInstillForm.tsx, packages/toolkit/src/view/airbyte/OneOfConditionSection.tsx, packages/toolkit/src/view/airbyte/useBuildAirbyteFields.tsx, packages/toolkit/src/view/pipeline-builder/components/iterator-editor/iterator-input/IteratorInput.tsx, packages/toolkit/src/view/pipeline-builder/components/iterator-editor/iterator-output/OutputValueSelect.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/connector-node/ConnectorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/operator-node/OperatorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/trigger-node/TriggerNodeTypeSelect.tsx, packages/toolkit/src/view/pipeline-builder/components/right-panel/ComponentFormOnRightPanel.tsx, packages/toolkit/src/view/pipeline/view-pipelines/CreatePipelineDialog.tsx, packages/toolkit/src/view/pipeline/view-pipelines/ViewPipelines.tsx
Because
- support collapsible nested form
This commit
- support collapsible nested form
=> feat(pipeline-builder): support collapsible nested form

apps/console/src/app/(providers)/react-query-client-provider.tsx, package.json, packages/design-system/src/new-ui/Icons/CoinsStacked01.tsx, packages/design-system/src/new-ui/Icons/index.ts, packages/toolkit/src/constant/credit.ts, packages/toolkit/src/constant/index.ts, packages/toolkit/src/lib/use-instill-form/components/regular/CollapsibleFormGroup.tsx, packages/toolkit/src/lib/use-instill-form/components/regular/CredentialTextField.tsx, packages/toolkit/src/lib/use-instill-form/components/regular/OneOfConditionField.tsx, packages/toolkit/src/lib/use-instill-form/components/regular/SingleSelectField.tsx, packages/toolkit/src/lib/use-instill-form/components/regular/TextAreaField.tsx, packages/toolkit/src/lib/use-instill-form/components/regular/TextField.tsx, packages/toolkit/src/lib/use-instill-form/components/regular/index.ts, packages/toolkit/src/lib/use-instill-form/components/smart-hint/SmartHintList.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/TextArea.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/TextField.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/useFilteredHints.tsx, packages/toolkit/src/lib/use-instill-form/pick/pickRegularFieldsFromInstillFormTree.tsx, packages/toolkit/src/lib/use-instill-form/transform/transformInstillJSONSchemaToFormTree.test.ts, packages/toolkit/src/lib/use-instill-form/transform/transformInstillJSONSchemaToFormTree.ts, packages/toolkit/src/lib/use-instill-form/transform/transformInstillJSONSchemaToZod.test.ts, packages/toolkit/src/lib/use-instill-form/types.ts, packages/toolkit/src/lib/use-instill-form/useInstillForm.test.tsx, packages/toolkit/src/lib/use-instill-form/useInstillForm.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/connector-node/ConnectorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/operator-node/OperatorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/right-panel/ComponentFormOnRightPanel.tsx
Because
- implement the instill credit interaction on component
This commit
- implement the instill credit interaction on component
=> feat(pipeline-builder): implement the instill credit interaction on component

packages/toolkit/src/lib/react-query-service/mgmt/index.ts, packages/toolkit/src/lib/react-query-service/mgmt/useRemainingCredit.ts, packages/toolkit/src/lib/vdp-sdk/mgmt/queries.ts
Because
- add the remaining credit related sdk and query
This commit
- add the remaining credit related sdk and query
=> feat: add the remaining credit related sdk and query

packages/toolkit/src/components/top-bar/CloudTopbarDropdown.tsx, packages/toolkit/src/components/top-bar/RemainingCredit.tsx, packages/toolkit/src/view/pipeline-builder/Flow.tsx, packages/toolkit/src/view/pipeline-builder/components/RemainingCreditCTA.tsx, packages/toolkit/src/view/pipeline-builder/components/index.ts
Because
- add remaining credit view in the pipeline builder
This commit
- add remaining credit view in the pipeline builder
=> feat(pipeline-builder): add remaining credit view in the pipeline builder

apps/console/integration-test/tests/should-change-component-id.test.ts, packages/design-system/package.json, packages/toolkit/package.json, packages/toolkit/src/view/pipeline-builder/components/nodes/trigger-node/triggerNodeFields.tsx
Because
- fix wrongly generate instillFormat for trigger component
This commit
- fix wrongly generate instillFormat for trigger component
=> fix: fix wrongly generate instillFormat for trigger component

packages/toolkit/src/lib/react-query-service/pipeline/useCreateUserPipelineRelease.ts, packages/toolkit/src/lib/use-instill-form/components/component-output/ObjectField.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output/ObjectsField.tsx, packages/toolkit/src/view/pipeline-builder/lib/hooks/useUpdaterOnRightPanel.tsx
Because
- improve pipeline-builder json output style 
This commit
- improve pipeline-builder json output style
=> feat(pipeline-builder): improve pipeline-builder json output style 

packages/toolkit/src/lib/use-instill-form/pick/pickComponentOutputFieldsFromInstillFormTree.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/response-node/ResponseNode.tsx
Because
- During output the result, the result didn't follow the user defined order
This commit
- align the output result with the user defined order
=> feat(pipeline-builder): align the output result with the user defined order

packages/toolkit/package.json, packages/toolkit/src/components/top-bar/CloudTopbarDropdown.tsx, packages/toolkit/src/view/pipeline-builder/Flow.tsx
Because
- fix credit upgrade button direction (subscription -> subscribe )
This commit
- fix credit upgrade button direction
=> fix(instill-credit): fix credit upgrade button direction

packages/toolkit/package.json, packages/toolkit/src/components/top-bar/RemainingCredit.tsx, packages/toolkit/src/view/pipeline-builder/components/RemainingCreditCTA.tsx
Because
- fix remaining credit decimal display
This commit
- fix remaining credit decimal display
=> fix(instill-credit): fix remaining credit decimal display

packages/toolkit/src/components/top-bar/RemainingCredit.tsx, packages/toolkit/src/view/pipeline-builder/Flow.tsx, packages/toolkit/src/view/pipeline-builder/components/RemainingCreditCTA.tsx
Because
- fix credit has dollar sign as prefix
This commit
- fix credit has dollar sign as prefix
=> fix(instill-credit): fix credit has dollar sign as prefix

packages/toolkit/package.json, packages/toolkit/src/view/hub/hub-view/Body.tsx, packages/toolkit/src/view/hub/hub-view/card-pipeline-hub/Head.tsx
Because
- Change Display Name in pipeline to normal case
=> fix: change name case in pipeline to normal case

packages/toolkit/src/view/hub/hub-view/Body.tsx
Because
- Change the border-radius of search input on hub page
=> fix: border radius on search in hub

apps/console/tsconfig.json, packages/design-system/src/new-ui/Breadcrumb/Breadcrumb.stories.tsx, packages/design-system/src/new-ui/radio-group/RadioGroup.tsx, packages/design-system/src/new-ui/tab-menu/TabMenu.stories.tsx, packages/design-system/src/new-ui/tab-menu/TabMenu.tsx, packages/design-tokens/src/buildSDTokens.ts, packages/eslint-config-cortex/package.json, packages/toolkit/src/lib/react-query-service/hub/useHubStats.ts, packages/toolkit/src/view/hub/hub-view/NewsLetterCard.tsx, packages/toolkit/src/view/hub/hub-view/card-pipeline-hub/Body.tsx, pnpm-lock.yaml
Because
- fix eslint version and error
This commit
- fix eslint version and error
=> fix: fix eslint version and error

packages/toolkit/src/components/top-bar/CloudTopbarDropdown.tsx
Because
- fix upgrade to pro broken link
This commit
- fix upgrade to pro broken link
=> fix(navigation): fix upgrade to pro broken link

packages/toolkit/src/components/UploadAvatarFieldWithCrop.tsx
Because
-  update UploadAvatarFieldWithCrop component
This commit
- update UploadAvatarFieldWithCrop component
=> fix(organization): update UploadAvatarFieldWithCrop component to accept title props

package.json, pnpm-lock.yaml
Because
- fix alert of vite and expressjs
This commit
- fix alert of vite and expressjs
=> fix: fix alert of vite and expressjs

packages/toolkit/src/lib/use-instill-form/components/regular/BooleanField.tsx, packages/toolkit/src/lib/use-instill-form/components/regular/CredentialTextField.tsx, packages/toolkit/src/lib/use-instill-form/components/regular/ImageField.tsx, packages/toolkit/src/lib/use-instill-form/components/regular/OneOfConditionField.tsx, packages/toolkit/src/lib/use-instill-form/components/regular/SingleSelectField.tsx, packages/toolkit/src/lib/use-instill-form/components/regular/TextAreaField.tsx, packages/toolkit/src/lib/use-instill-form/components/regular/TextField.tsx, packages/toolkit/src/lib/use-instill-form/pick/pickRegularFieldsFromInstillFormTree.tsx, packages/toolkit/src/lib/use-instill-form/types.ts
Because
- fix auto-gen-form required field didn't show * sign
This commit
- fix auto-gen-form required field didn't show * sign
=> fix: fix auto-gen-form required field didn't show * sign

packages/toolkit/src/lib/use-instill-form/components/component-output/MDTextViewer.tsx, packages/toolkit/src/view/pipeline-builder/components/ComponentOutputs.tsx
Because
- fix bug that output markdown not correctly wrapped, cause text hard to read
This commit
- fix bug that output markdown not correctly wrapped, cause text hard to read
=> fix(auto-gen-form): fix bug that output markdown not correctly wrapped, cause text hard to read

packages/toolkit/src/view/hub/hub-view/LatestChangesCard.tsx, packages/toolkit/src/view/hub/hub-view/NewsLetterCard.tsx
Because
- Changes  style of Latest Changes card 
- Rebased main of this [PR](https://github.com/instill-ai/console/pull/1180)
=> feat: change style of Latest Changes card

packages/toolkit/src/lib/use-instill-form/components/regular/ImagesField.tsx, packages/toolkit/src/lib/use-instill-form/components/regular/index.ts, packages/toolkit/src/lib/use-instill-form/pick/pickRegularFieldsFromInstillFormTree.tsx, packages/toolkit/src/lib/use-instill-form/transform/transformInstillJSONSchemaToZod.ts
Because
- fix auto gen form didn't support Images field issue
This commit
- fix auto gen form didn't support Images field issue
=> fix(auto-gen-form): fix auto gen form didn't support Images field issue

LICENSE, packages/toolkit/src/view/settings/user/UserProfileTab.tsx
Because
- Instill Core project is now with Instill Community License
This commit
- update license file
=> docs(license): update repo license

packages/toolkit/src/components/top-bar/RemainingCredit.tsx
Because
- fix wrongly display upgrade button on the user profile dropdown
This commit
- fix wrongly display upgrade button on the user profile dropdown
=> fix(subscription): fix wrongly display upgrade button on the user profile dropdown

packages/toolkit/src/lib/use-instill-form/components/regular/ImagesField.tsx, packages/toolkit/src/lib/use-instill-form/pick/pickRegularFieldsFromInstillFormTree.tsx, packages/toolkit/src/lib/use-instill-form/transform/transformInstillJSONSchemaToFormTree.ts, packages/toolkit/src/lib/use-instill-form/transform/transformInstillJSONSchemaToZod.ts, packages/toolkit/src/lib/use-instill-form/types.ts
Because
- adapt special model trigger data format
This commit
- adapt special model trigger data format
=> feat(auto-gen-form): adapt special model trigger data format

packages/toolkit/package.json, packages/toolkit/src/view/hub/hub-view/Body.tsx
Because
- let the total number follow the user filter on hub page
This commit
- let the total number follow the user filter on hub page
=> feat(hub): let the total number follow the user filter on hub page

packages/design-system/package.json, packages/design-system/src/new-ui/DataTable/index.ts, packages/design-system/src/new-ui/Icons/index.ts, packages/design-system/src/new-ui/ToggleGroup/ToggleGroup.stories.tsx, packages/design-system/src/new-ui/ToggleGroup/ToggleGroup.tsx, packages/design-system/src/new-ui/ToggleGroup/index.tsx, packages/design-system/src/new-ui/index.ts, packages/toolkit/package.json, packages/toolkit/src/components/card-model/Stats.tsx, packages/toolkit/src/lib/formatNumberToLocale.ts, packages/toolkit/src/lib/generateDateInPast.ts, packages/toolkit/src/lib/index.ts, packages/toolkit/src/lib/react-query-service/index.ts, packages/toolkit/src/lib/use-instill-form/components/smart-hint/SmartHintInfoCard.tsx, packages/toolkit/src/view/hub/hub-view/Body.tsx, pnpm-lock.yaml
Because
- credits page needed some updates on the toolkit and design sides
This commit
- added required components and utilities to use in console-cloud
=> feat(billing): billing credits related updates

apps/console/src/app/login/render.tsx, apps/console/src/app/sitemap.ts, apps/console/src/components/OnboardingForm.tsx, apps/console/src/lib/auth/withMiddlewareAuthRequired.ts, packages/toolkit/package.json, packages/toolkit/src/components/card-model/CardModel.tsx, packages/toolkit/src/components/card-model/index.tsx, packages/toolkit/src/components/index.ts, packages/toolkit/src/lib/index.ts
Because
- maintain unified package version in toolkit
This commit
- re-export lodash for console-cloud usage
=> feat: re-export lodash for console-cloud usage

apps/console/src/app/sitemap.ts, packages/toolkit/package.json, packages/toolkit/src/lib/vdp-sdk/helper/getQueryString.test.ts, packages/toolkit/src/lib/vdp-sdk/helper/getQueryString.ts, packages/toolkit/src/view/dashboard/DashboardPipelineDetailsPageMainView.tsx, packages/toolkit/src/view/dashboard/DashboardPipelineListPageMainView.tsx
Because
- adapt the camelCase rule in the query param
This commit
- adapt the camelCase rule in the query param
=> feat: adapt the camelCase rule in the query param

packages/toolkit/package.json, packages/toolkit/src/components/top-bar/NamespaceSwitch.tsx, packages/toolkit/src/components/top-bar/NavLinks.tsx
Because
- fix topbar's navlinks not displayed in console-cloud
This commit
- fix topbar's navlinks not displayed in console-cloud
=> fix: fix topbar's navlinks not displayed in console-cloud

packages/design-system/package.json, packages/design-system/src/new-ui/Icons/CardRefresh.tsx, packages/design-system/src/new-ui/Icons/CurrencyDollar.tsx, packages/design-system/src/new-ui/Icons/index.ts
Because
- needed new icons for credits top up view
This commit
- added them
=> chore: add icons

apps/console/src/app/[entity]/models/create/render.tsx, packages/toolkit/package.json, packages/toolkit/src/components/top-bar/NamespaceSwitch.tsx, packages/toolkit/src/lib/react-query-service/connector/useConnectorDefinitions.ts, packages/toolkit/src/view/model/CreateModelForm.tsx, packages/toolkit/src/view/model/ModelHubCreatePageMainView.tsx
Because
- fix not selecting the selected namespace as default namespace when create model
This commit
- fix not selecting the selected namespace as default namespace when create model
=> fix(namespace-switch): fix not selecting the selected namespace as default namespace when create model

packages/toolkit/package.json, packages/toolkit/src/components/top-bar/NamespaceSwitch.tsx, packages/toolkit/src/view/model/CreateModelForm.tsx, packages/toolkit/src/view/pipeline/view-pipelines/CreatePipelineDialog.tsx
Because
- set namespaceAnchor when create model or pipeline
This commit
- set namespaceAnchor when create model or pipeline
=> fix: set namespaceAnchor when create model or pipeline

packages/toolkit/package.json, packages/toolkit/src/components/top-bar/NavLinks.tsx, packages/toolkit/src/components/top-bar/TopbarMiscLinks.tsx
Because
- fix incorrectly display navlinks for unauth user
This commit
- fix incorrectly display navlinks for unauth user
=> fix(namespace-switch): fix incorrectly display navlinks for unauth user

packages/toolkit/package.json, packages/toolkit/src/components/top-bar/NamespaceSwitch.tsx
Because
- fix switch namespace not correctly re-render namespace's image
This commit
- fix switch namespace not correctly re-render namespace's image
=> fix(namespace-switch): fix switch namespace not correctly re-render namespace's image

apps/console/src/styles/global.css, packages/design-system/package.json, packages/design-system/src/new-ui/Tag/Tag.tsx, packages/toolkit/package.json, packages/toolkit/src/components/NamespaceAvatarWithFallback.tsx, packages/toolkit/src/components/top-bar/AppTopbar.tsx, packages/toolkit/src/components/top-bar/NamespaceSwitch.tsx, packages/toolkit/src/components/top-bar/NavLinks.tsx
Because
- fix the namespace switch style and deviation 
This commit
- fix the namespace switch style and deviation
=> fix(namespace-switch): fix the namespace switch style and deviation 

packages/toolkit/package.json, packages/toolkit/src/view/pipeline-builder/components/nodes/general-node/GeneralNode.tsx
Because
- remove displaying data free form on big query
This commit
- remove displaying data free form on big query
=> feat(pipeline-editor): remove displaying data free form on big query

packages/toolkit/src/components/ClonePipelineDialog.tsx, packages/toolkit/src/components/EntitySelector.tsx, packages/toolkit/src/lib/react-query-service/pipeline/index.ts, packages/toolkit/src/lib/react-query-service/pipeline/useCloneNamespacePipeline.ts, packages/toolkit/src/lib/vdp-sdk/pipeline/mutations.ts, packages/toolkit/src/view/pipeline-builder/lib/createNodesFromPipelineComponents.tsx
Because
- fix not correctly clone pipeline and unify UI
This commit
- fix not correctly clone pipeline and unify UI
=> fix: fix not correctly clone pipeline and unify UI

packages/toolkit/package.json, packages/toolkit/src/components/ClonePipelineDialog.tsx, packages/toolkit/src/components/top-bar/NamespaceSwitch.tsx, packages/toolkit/src/lib/useUserNamespaces.ts
Because
- sort the namespaces
- deal with not handling namespaces in others pipeline
This commit
- fix issue about namespace switch list
=> fix(namespace-switch): fix issue about namespace switch list

apps/console/integration-test/tests/should-change-component-id.test.ts, apps/console/integration-test/tests/should-edit-create-start-end-field.test.ts, apps/console/src/app/(providers)/root-provider.tsx, apps/console/src/app/login/render.tsx, packages/toolkit/package.json, packages/toolkit/src/lib/table/formatDate.ts, packages/toolkit/src/lib/vdp-sdk/mgmt/types.ts, packages/toolkit/src/view/settings/api-tokens/APITokenTable.tsx
Because
- support sorting the last use date in api token table
This commit
- support sorting the last use date in api token table
=> feat: support sorting the last use date in api token table

apps/console/src/app/(providers)/root-provider.tsx
Because
- fix toaster style issue
This commit
- fix toaster style issue
=> fix: fix toaster style issue

packages/toolkit/src/view/pipeline-builder/components/iterator-editor/IteratorEditor.tsx, packages/toolkit/src/view/pipeline-builder/lib/composePipelineComponentMapFromNodes.ts
Because
- fix iterator saving issue
This commit
- fix iterator saving issue
=> fix(pipeline-builder): fix iterator saving issue

packages/toolkit/package.json, packages/toolkit/src/components/PageBase.tsx, packages/toolkit/src/components/UserProfileCard.tsx, packages/toolkit/src/view/pipeline/view-pipelines/ViewPipelines.tsx
Because
- fix container height variable wrongly calculated issue
This commit
- fix container height variable wrongly calculated issue
=> fix: fix container height variable wrongly calculated issue

packages/toolkit/package.json, packages/toolkit/src/components/top-bar/CloudTopbarDropdown.tsx, packages/toolkit/src/components/top-bar/NamespaceSwitch.tsx, packages/toolkit/src/components/top-bar/RemainingCredit.tsx, packages/toolkit/src/lib/index.ts, packages/toolkit/src/lib/react-query-service/mgmt/useNamespacesRemainingCredit.ts, packages/toolkit/src/lib/vdp-sdk/mgmt/queries.ts, packages/toolkit/src/lib/vdp-sdk/mgmt/types.ts, packages/toolkit/src/view/pipeline-builder/components/RemainingCreditCTA.tsx
=> feat: updates for the cloud top-up flow

packages/design-system/src/ui-helpers/getModelHardwareToolkit.ts, packages/design-system/src/ui-helpers/getModelRegionToolkit.ts, packages/toolkit/package.json, packages/toolkit/src/components/EmptyImageInputPlaceholder.tsx, packages/toolkit/src/components/StateLabel.tsx, packages/toolkit/src/components/card-model/CardModel.tsx, packages/toolkit/src/components/card-model/Tags.tsx, packages/toolkit/src/components/index.ts, packages/toolkit/src/components/top-bar/NamespaceSwitch.tsx, packages/toolkit/src/lib/react-query-service/model/useWatchUserModels.ts, packages/toolkit/src/lib/use-instill-form/components/regular/ImageField.tsx, packages/toolkit/src/lib/use-instill-form/components/regular/ImagesField.tsx, packages/toolkit/src/lib/vdp-sdk/model/types.ts, packages/toolkit/src/view/model/ModelsTable.tsx, packages/toolkit/src/view/model/view-model/ModelContentViewer.tsx, packages/toolkit/src/view/model/view-model/ModelHead.tsx, packages/toolkit/src/view/model/view-model/ModelOverview.tsx, packages/toolkit/src/view/model/view-model/ModelVersions.tsx, packages/toolkit/src/view/model/view-model/NoVersionsPlaceholder.tsx, packages/toolkit/src/view/model/view-model/constants.ts, packages/toolkit/src/view/model/view-model/index.tsx
=> feat: model view tweaks

packages/design-system/package.json, packages/design-system/src/new-ui/index.ts, packages/design-system/src/new-ui/resizable/Resizable.stories.tsx, packages/design-system/src/new-ui/resizable/Resizable.tsx, packages/design-system/src/new-ui/resizable/index.ts, pnpm-lock.yaml
Because
- add resizable component
This commit
- add resizable component
=> feat(design-system): add resizable component

packages/toolkit/package.json, packages/toolkit/src/lib/vdp-sdk/mgmt/types.ts, packages/toolkit/src/lib/vdp-sdk/organization/types.ts
Because
- add PLAN_UNPAID type into subscription plan
This commit
- add PLAN_UNPAID type into subscription plan
=> feat: add PLAN_UNPAID type into subscription plan

packages/toolkit/src/view/settings/api-tokens/APITokenTable.tsx
Because
- fix api-token table lastUsedTime empty text
This commit
- fix api-token table lastUsedTime empty text
=> fix(dashboard): fix api-token table lastUsedTime empty text

packages/toolkit/package.json, packages/toolkit/src/view/settings/api-tokens/APITokenTable.tsx, packages/toolkit/src/view/settings/secrets/CreateSecretDialog.tsx, packages/toolkit/src/view/settings/secrets/SecretTable.tsx
Because
- replace secret ID with Name in CreateSecretDialog and SecretTable
This commit
- replace secret ID with Name in CreateSecretDialog and SecretTable
=> fix: replace secret ID with Name in CreateSecretDialog and SecretTable

packages/toolkit/src/view/model/view-model/NoVersionsPlaceholder.tsx
=> fix: empty model placeholder link styles update

packages/toolkit/package.json, packages/toolkit/src/view/dashboard/DashboardContainer.tsx
Because
- disable credit consumption related feature
This commit
- disable credit consumption related feature
=> chore: disable credit consumption related feature

packages/toolkit/package.json, packages/toolkit/src/lib/useUserNamespaces.ts
Because
- fix useUserNamespaces return data too early
This commit
- fix useUserNamespaces return data too early
=> fix(namespace-switch): fix useUserNamespaces return data too early

apps/console/src/app/[entity]/dashboard/pipeline/[id]/render.tsx, packages/toolkit/src/lib/dashboard/getTriggersSummary.ts, packages/toolkit/src/lib/react-query-service/metric/usePipelineTriggerRecords.ts, packages/toolkit/src/view/dashboard/DashboardPipelineDetailsPageMainView.tsx, packages/toolkit/src/view/dashboard/DashboardPipelineListPageMainView.tsx, packages/toolkit/src/view/dashboard/FilterByDay.tsx
Because
- fix dashboard pipeline details page re-render issue
This commit
- fix dashboard pipeline details page re-render issue
=> fix(dashboard): fix dashboard pipeline details page re-render issue

packages/toolkit/src/view/dashboard/DashboardPipelineDetailsPageMainView.tsx
Because
- fix query pipeline trigger id filter id issue
This commit
- fix query pipeline trigger id filter id issue
=> fix(dashboard): fix query pipeline trigger id filter id issue

packages/toolkit/package.json, packages/toolkit/src/view/settings/secrets/CreateSecretDialog.tsx
Because
- fix use can't create secret for organization
This commit
- fix use can't create secret for organization
=> fix: fix use can't create secret for organization

apps/console/integration-test/tests/should-change-component-id.test.ts, packages/toolkit/package.json, packages/toolkit/src/lib/react-query-service/pipeline/useTriggerUserPipelineRelease.tsx, packages/toolkit/src/lib/use-instill-form/components/regular/SingleSelectField.tsx, packages/toolkit/src/lib/vdp-sdk/pipeline/actions.ts, packages/toolkit/src/view/pipeline-builder/components/nodes/common/node-bottom-bar/NodeBottomBarMenu.tsx, packages/toolkit/src/view/pipeline/view-pipeline/Head.tsx, packages/toolkit/src/view/pipeline/view-pipeline/InOutPut.tsx, packages/toolkit/src/view/pipeline/view-pipeline/ViewPipeline.tsx
Because
- fix console didn't trigger the correct pipeline version
This commit
- fix console didn't trigger the correct pipeline version
=> fix: fix console didn't trigger the correct pipeline version

packages/toolkit/package.json, packages/toolkit/src/view/pipeline/view-pipeline/InOutPut.tsx
Because
- fix trigger pipeline version didn't show result
This commit
- fix trigger pipeline version didn't show result
=> fix: fix trigger pipeline version didn't show result

packages/sdk/package.json, packages/sdk/src/core/metric/MetricClient.ts, packages/toolkit/package.json, packages/toolkit/src/lib/react-query-service/metric/index.ts, packages/toolkit/src/lib/react-query-service/metric/useCreditConsumptionChartRecords.ts, packages/toolkit/src/lib/react-query-service/metric/usePipelineTriggerComputationTimeCharts.ts, packages/toolkit/src/lib/react-query-service/metric/usePipelineTriggerMetric.ts, packages/toolkit/src/lib/react-query-service/metric/usePipelineTriggers.ts, packages/toolkit/src/view/dashboard/DashboardPipelineDetailsPageMainView.tsx, packages/toolkit/src/view/dashboard/DashboardPipelineListPageMainView.tsx
Because
- Adapt sdk for metric relate endpoint
This commit
- Adapt sdk for metric relate endpoint
=> feat: Adapt sdk for metric relate endpoint

apps/console/src/app/(providers)/amplitude-client-provider.tsx, packages/toolkit/src/lib/react-query-service/pipeline/useCreateNamespacePipelineRelease.ts, packages/toolkit/src/lib/react-query-service/pipeline/useInfiniteNamespacePipelineReleases.ts, packages/toolkit/src/view/pipeline-builder/components/release-menu/ReleaseMenu.tsx, packages/toolkit/src/view/pipeline-builder/components/top-control-menu/Release.tsx
Because
- fix release pipeline not correctly update cache cause
This commit
- fix release pipeline not correctly update cache cause
=> fix: fix release pipeline not correctly update cache cause

packages/sdk/src/helper/getInstillAdditionalHeaders.ts, packages/sdk/src/helper/index.ts, packages/sdk/src/vdp/pipeline/PipelineClient.ts, packages/sdk/src/vdp/release/ReleaseClient.ts, packages/sdk/src/vdp/trigger/TriggerClient.ts, packages/toolkit/src/lib/react-query-service/model/useTriggerUserModelAsync.tsx, packages/toolkit/src/lib/vdp-sdk/helper/getInstillAdditionalHeaders.test.ts, packages/toolkit/src/lib/vdp-sdk/helper/getInstillAdditionalHeaders.ts, packages/toolkit/src/lib/vdp-sdk/helper/index.ts, packages/toolkit/src/lib/vdp-sdk/model/actions.ts, packages/toolkit/src/lib/vdp-sdk/pipeline/actions.ts, packages/toolkit/src/lib/vdp-sdk/pipeline/queries.ts, packages/toolkit/src/view/model/view-model/ModelPlayground.tsx
Because
- add requester uid header when user trigger model
This commit
- add requester uid header when user trigger model
=> feat: add requester uid header when user trigger model

apps/console/src/app/[entity]/models/[id]/[tab]/render.tsx, apps/console/src/app/[entity]/models/render.tsx, packages/toolkit/package.json, packages/toolkit/src/view/model/ModelHubListPageMainView.tsx, packages/toolkit/src/view/model/ModelHubSettingPageMainView.tsx
Because
- remove unused page props on model related pages
This commit
- remove unused page props on model related pages
=> chore: remove unused page props on model related pages

packages/toolkit/package.json, packages/toolkit/src/components/SectionHeader.tsx, packages/toolkit/src/view/model/ModelHubListPageMainView.tsx, packages/toolkit/src/view/model/ModelHubSettingPageMainView.tsx, packages/toolkit/src/view/model/view-model/ModelContentViewer.tsx, packages/toolkit/src/view/model/view-model/ModelHead.tsx, packages/toolkit/src/view/pipeline/view-pipeline/Head.tsx, packages/toolkit/src/view/pipeline/view-pipeline/PipelineContentViewer.tsx, packages/toolkit/src/view/pipeline/view-pipeline/ViewPipeline.tsx, packages/toolkit/src/view/pipeline/view-pipelines/ViewPipelines.tsx
=> fix: layout width update

release-please/config.json, release-please/manifest.json
Because
- add instill-sdk into release-please config
This commit
- add instill-sdk into release-please config
=> chore: add instill-sdk into release-please config

packages/sdk/package.json, packages/sdk/src/model/ModelClient.ts, packages/sdk/src/model/types.ts, packages/toolkit/package.json, packages/toolkit/src/lib/react-query-service/model/useInfiniteModelVersions.ts, packages/toolkit/src/lib/react-query-service/model/useUserModel.tsx, packages/toolkit/src/lib/react-query-service/model/useWatchUserModels.ts, packages/toolkit/src/lib/vdp-sdk/index.ts, packages/toolkit/src/lib/vdp-sdk/model/queries.ts, packages/toolkit/src/lib/vdp-sdk/model/types.ts, packages/toolkit/src/view/model/view-model/ModelVersions.tsx
An update for the model related requests to allow for unauthorized users to get model, model state and model versions.
=> fix: model public requests

packages/toolkit/src/components/PageBase.tsx, packages/toolkit/src/view/model/view-model/ModelPlayground.tsx, packages/toolkit/src/view/pipeline/view-pipeline/Head.tsx, packages/toolkit/src/view/pipeline/view-pipeline/PipelineApi.tsx, packages/toolkit/src/view/pipeline/view-pipeline/PipelineContentViewer.tsx
fixes INS-5361
fixes INS-5360
fixes INS-5186
=> fix: pre-release fixes

packages/toolkit/src/view/pipeline-builder/Flow.tsx
Because
- Removes the credit balance from canvas
=> fix: remove the bottom credits balance

packages/sdk/package.json, packages/sdk/src/core/subscription/types.ts, packages/toolkit/package.json, packages/toolkit/src/lib/react-query-service/organization/useOrganizationSubscription.ts
Because
- update subscription endpoint PLAN type
This commit
- update subscription endpoint PLAN type
=> feat: update subscription endpoint PLAN type

packages/toolkit/src/components/card-model/Tags.tsx, packages/toolkit/src/view/model/CreateModelForm.tsx, packages/toolkit/src/view/model/ModelHubListPageMainView.tsx, packages/toolkit/src/view/model/view-model/ModelHead.tsx, packages/toolkit/src/view/model/view-model/ModelPlayground.tsx, packages/toolkit/src/view/model/view-model/ModelSettingsEditForm.tsx
Because
- make models public available
This commit
- make models public available
=> feat: make models public available

apps/console/src/app/login/render.tsx, packages/sdk/src/index.ts, packages/sdk/src/main/index.ts, packages/sdk/src/types.ts, packages/toolkit/package.json, packages/toolkit/src/lib/toastInstillError.ts, packages/toolkit/src/lib/vdp-sdk/helper/getInstillApiErrorMessage.tsx, packages/toolkit/src/view/model/CreateModelForm.tsx, packages/toolkit/src/view/pipeline-builder/components/dialogs/share-pipeline-dialog/TabShare.tsx, packages/toolkit/src/view/pipeline-builder/lib/hooks/useRenamePipeline.tsx, packages/toolkit/src/view/pipeline-builder/lib/hooks/useSavePipeline.tsx, packages/toolkit/src/view/settings/api-tokens/CreateAPITokenDialog.tsx, packages/toolkit/src/view/settings/api-tokens/DeleteAPITokenDialog.tsx, packages/toolkit/src/view/settings/secrets/CreateSecretDialog.tsx, packages/toolkit/src/view/settings/secrets/DeleteSecretDialog.tsx
Because
- unify how we handle error
This commit
- unify how we handle error
=> fix: unify how we handle error

packages/toolkit/package.json, packages/toolkit/src/view/model/CreateModelForm.tsx, packages/toolkit/src/view/model/view-model/ModelSettingsEditForm.tsx
Because
- open up model public setting option
This commit
- open up model public setting option
=> feat: open up model public setting option

packages/toolkit/src/view/knowledge/components/tabs/UploadExploreTab.tsx
Because
- File uploud safeguards
=> fix: add File safeguards to file uploud

packages/design-system/src/new-ui/Icons/LayoutLeft.tsx, packages/design-system/src/new-ui/Icons/index.ts, packages/toolkit/src/view/recipe-editor/Editor.tsx, packages/toolkit/src/view/recipe-editor/PipelineNamePopover.tsx, packages/toolkit/src/view/recipe-editor/RecipeEditorView.tsx
Because
- add name and visibility edit popover
This commit
- add name and visibility edit popover
=> feat: add name and visibility edit popover

packages/sdk/src/index.ts, packages/toolkit/src/lib/react-query-service/knowledge/useDeleteKnowledgeBaseFile.tsx, packages/toolkit/src/lib/react-query-service/knowledge/useGetChunkContent.ts, packages/toolkit/src/lib/react-query-service/knowledge/useGetFileContent.ts, packages/toolkit/src/lib/react-query-service/knowledge/useGetFileDetails.ts, packages/toolkit/src/lib/react-query-service/knowledge/useListChunks.ts, packages/toolkit/src/lib/react-query-service/knowledge/useListKnowledgeBaseFiles.ts, packages/toolkit/src/lib/react-query-service/knowledge/useProcessKnowledgeBaseFiles.ts, packages/toolkit/src/lib/react-query-service/knowledge/useUpdateChunk.ts, packages/toolkit/src/lib/react-query-service/knowledge/useUploadKnowledgeBaseFile.ts, packages/toolkit/src/view/knowledge/KnowledgeBaseView.tsx, packages/toolkit/src/view/knowledge/components/CreateKnowledgeBaseCard.tsx, packages/toolkit/src/view/knowledge/components/FileChunks.tsx, packages/toolkit/src/view/knowledge/components/FileDetailsOverlay.tsx, packages/toolkit/src/view/knowledge/components/tabs/CatalogFilesTab.tsx, packages/toolkit/src/view/knowledge/components/tabs/ChunkTab.tsx, packages/toolkit/src/view/knowledge/components/tabs/UploadExploreTab.tsx
Because
- Add load all resources for Catalog and Chunks tabs
=> fix: add pagination to Catalog

packages/toolkit/src/lib/react-query-service/knowledge/useListKnowledgeBaseFiles.ts
=> fix: catalog fix linting

packages/toolkit/src/components/top-bar/CETopbarDropdown.tsx, packages/toolkit/src/view/recipe-editor/RecipeEditorView.tsx, packages/toolkit/src/view/recipe-editor/ReleasePopover.tsx, packages/toolkit/src/view/recipe-editor/RunButton.tsx, packages/toolkit/src/view/recipe-editor/ShareDialogTrigger.tsx, packages/toolkit/src/view/recipe-editor/ToolkitDialogTrigger.tsx
Because
- add topbar elements
This commit
- add topbar elements
=> feat: add topbar elements

.github/workflows/integration-test.yml, docs/integration-test.md
Because
- fix integration test for latest instill-core launch method change
This commit
- fix integration test for latest instill-core launch method change
=> fix: fix integration test for latest instill-core launch method change

packages/toolkit/src/lib/amplitude/type.ts, packages/toolkit/src/view/model/view-model/ModelPlayground.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/variable-node/VariableNode.tsx, packages/toolkit/src/view/pipeline/view-pipeline/PipelinePlayground.tsx
Because
- add page_url into amplitude event properties
This commit
- add page_url into amplitude event properties
=> feat: add page_url into amplitude event properties

packages/design-system/src/new-ui/Icons/Download01.tsx, packages/design-system/src/new-ui/Icons/Expand01.tsx, packages/design-system/src/new-ui/Icons/Eye.tsx, packages/design-system/src/new-ui/Icons/Maximize02.tsx, packages/design-system/src/new-ui/Icons/Minimize01.tsx, packages/design-system/src/new-ui/Icons/index.ts, packages/design-system/src/new-ui/resizable/Resizable.tsx, packages/toolkit/src/lib/use-instill-store/editorSlice.ts, packages/toolkit/src/lib/use-instill-store/types.ts, packages/toolkit/src/view/recipe-editor/EditorViewBarItem.tsx, packages/toolkit/src/view/recipe-editor/EditorViewSectionBar.tsx, packages/toolkit/src/view/recipe-editor/HorizontalSortableWrapper.tsx, packages/toolkit/src/view/recipe-editor/InOutputEmptyView.tsx, packages/toolkit/src/view/recipe-editor/RecipeEditorView.tsx, packages/toolkit/src/view/recipe-editor/VscodeEditor.tsx, packages/toolkit/src/view/recipe-editor/flow/Flow.tsx, packages/toolkit/src/view/recipe-editor/prettifyYaml.ts
Because
- new low code multiple window layout
This commit
- new low code multiple window layout
=> feat: new low code multiple window layout

packages/toolkit/src/view/pipeline-builder/components/ComponentOutputs.tsx, packages/toolkit/src/view/recipe-editor/Input.tsx, packages/toolkit/src/view/recipe-editor/Output.tsx, packages/toolkit/src/view/recipe-editor/RecipeEditorView.tsx, packages/toolkit/src/view/recipe-editor/flow/Flow.tsx, packages/toolkit/src/view/recipe-editor/flow/nodes/GeneralNode.tsx, packages/toolkit/src/view/recipe-editor/sidebar/ComponentSection.tsx, packages/toolkit/src/view/recipe-editor/sidebar/PipelineSection.tsx, packages/toolkit/src/view/recipe-editor/sidebar/Sidebar.tsx, packages/toolkit/src/view/recipe-editor/sidebar/index.ts
Because
- low code editors sidebar implementation
This commit
- low code editors sidebar implementation
=> feat: low code editors sidebar implementation

packages/toolkit/package.json, packages/toolkit/src/view/pipeline-builder/components/ComponentOutputs.tsx, packages/toolkit/src/view/recipe-editor/Input.tsx, packages/toolkit/src/view/recipe-editor/Output.tsx, packages/toolkit/src/view/recipe-editor/RecipeEditorView.tsx, packages/toolkit/src/view/recipe-editor/flow/Flow.tsx, packages/toolkit/src/view/recipe-editor/flow/nodes/GeneralNode.tsx, packages/toolkit/src/view/recipe-editor/sidebar/ComponentSection.tsx, packages/toolkit/src/view/recipe-editor/sidebar/PipelineSection.tsx, packages/toolkit/src/view/recipe-editor/sidebar/RemainingCredit.tsx, packages/toolkit/src/view/recipe-editor/sidebar/Sidebar.tsx, packages/toolkit/src/view/recipe-editor/sidebar/SubscribeCTA.tsx, packages/toolkit/src/view/recipe-editor/sidebar/SupportLinks.tsx, packages/toolkit/src/view/recipe-editor/sidebar/index.ts, pnpm-lock.yaml
Because
- low code editors sidebar implementation
This commit
- low code editors sidebar implementation
=> feat low code editors sidebar implementation

packages/toolkit/src/lib/use-instill-form/components/component-output/ImageField.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output/VideoField.tsx, packages/toolkit/src/lib/use-instill-form/components/trigger-request-form-fields/ImageField.tsx
Because
- further fix image padding issue between input and output
This commit
- further fix image padding issue between input and output
=> fix(pipeline-editor): further fix image padding issue between input and output

packages/toolkit/src/view/pipeline-builder/components/nodes/general-node/GeneralNode.tsx
Because
- remove add field for data related component
This commit
- remove add field for data related component
=> fix: remove add field for data related component

packages/toolkit/src/lib/react-query-service/knowledge/useListKnowledgeBaseFiles.ts, packages/toolkit/src/view/knowledge/KnowledgeBaseView.tsx, packages/toolkit/src/view/knowledge/components/CreateKnowledgeBaseCard.tsx, packages/toolkit/src/view/knowledge/components/tabs/CatalogFilesTab.tsx, packages/toolkit/src/view/knowledge/components/tabs/ChunkTab.tsx, packages/toolkit/src/view/knowledge/components/tabs/UploadExploreTab.tsx
Because
- Add pagination to catalog pages
=> feat(catalog): pagination

packages/toolkit/package.json, packages/toolkit/src/view/knowledge/KnowledgeBaseView.tsx, packages/toolkit/src/view/knowledge/components/notifications/InsufficientStorageBanner.tsx, packages/toolkit/src/view/knowledge/components/notifications/UpgradePlanLink.tsx, packages/toolkit/src/view/knowledge/components/tabs/CatalogFilesTab.tsx, packages/toolkit/src/view/knowledge/components/tabs/KnowledgeBaseTab.tsx, packages/toolkit/src/view/knowledge/components/tabs/UploadExploreTab.tsx
Because
- Fixes link on Team Plan
=> fix(catalog): fix link on Team plan 

packages/toolkit/package.json, packages/toolkit/src/view/settings/api-tokens/SelectOrganization.tsx, packages/toolkit/src/view/settings/api-tokens/index.ts, packages/toolkit/src/view/settings/user/UserAPITokenTab.tsx
Because
- [https://linear.app/instill-ai/issue/INS-5746/[improvement]-enhance-uiux-and-documentation-for-consuming](https://linear.app/instill-ai/issue/INS-5746/%5Bimprovement%5D-enhance-uiux-and-documentation-for-consuming)
=> feat(dashboard): feat enhance UI/UX for consuming organization credits

packages/toolkit/src/view/recipe-editor/VscodeEditor.tsx, packages/toolkit/src/view/recipe-editor/tomorrowTheme.ts
Because
- implement the new autocomplete style
This commit
- implement the new autocomplete style
=> feat(low-code): implement the new autocomplete style

packages/design-system/src/new-ui/Command/Command.tsx, packages/design-system/src/new-ui/Icons/SearchMd.tsx, packages/design-system/src/new-ui/Icons/index.ts, packages/toolkit/src/lib/use-instill-store/editorSlice.ts, packages/toolkit/src/lib/use-instill-store/types.ts, packages/toolkit/src/view/recipe-editor/RecipeEditorView.tsx, packages/toolkit/src/view/recipe-editor/VscodeEditor.tsx, packages/toolkit/src/view/recipe-editor/cmdk/index.ts, packages/toolkit/src/view/recipe-editor/commands/ActionCmdk.tsx, packages/toolkit/src/view/recipe-editor/commands/CommandShortcutBadge.tsx, packages/toolkit/src/view/recipe-editor/commands/ComponentCmdo.tsx, packages/toolkit/src/view/recipe-editor/commands/index.ts
Because
- revamp the old cmdk with new design
This commit
- revamp the old cmdk with new design
=> feat: revamp the old cmdk with new design

apps/console/next.config.js, packages/toolkit/package.json, packages/toolkit/src/view/model/ModelHubSettingPageMainView.tsx, packages/toolkit/src/view/model/view-model/ModelContentViewer.tsx, packages/toolkit/src/view/model/view-model/ModelSettingsEditForm.tsx, packages/toolkit/src/view/pipeline/view-pipeline/PipelineContentViewer.tsx, packages/toolkit/src/view/pipeline/view-pipeline/PipelineSettings.tsx, packages/toolkit/src/view/pipeline/view-pipeline/ViewPipeline.tsx
Because
[https://instill.tech/ownerID/pipeline/pipelineID/settings ](https://instill.tech/ownerID/pipeline/pipelineID/playground) tab should be redirected to playground if not owner of pipeline
[https://instill.tech/ownerID/models/modelId/settings ](https://instill.tech/ownerID/pipeline/pipelineID/playground) tab should be redirected to playground if not owner of model
[https://instill.tech/](https://instill.tech/ownerID/models/modelID)[ownerID](https://instill.tech/ownerID/models/modelID)[/models/](https://instill.tech/ownerID/models/modelID)[modelID](https://instill.tech/ownerID/models/modelID)should redirect to playground (if exists)
[https://instill.tech/](https://instill.tech/ownerID/models/modelID)[ownerID](https://instill.tech/ownerID/models/modelID)[/models/](https://instill.tech/o …
=> fix(pipelines): fix add redirection to playground and to settings tab

packages/design-system/src/new-ui/Command/Command.tsx, packages/design-system/src/new-ui/Icons/FileDownload03.tsx, packages/design-system/src/new-ui/Icons/Rocket02.tsx, packages/design-system/src/new-ui/Icons/index.ts, packages/sdk/src/helper/getQueryString.ts, packages/sdk/src/vdp/component/ComponentClient.ts, packages/sdk/src/vdp/component/types.ts, packages/toolkit/src/lib/use-instill-store/editorSlice.ts, packages/toolkit/src/lib/use-instill-store/types.ts, packages/toolkit/src/view/recipe-editor/ImportRecipeDialog.tsx, packages/toolkit/src/view/recipe-editor/RecipeEditorView.tsx, packages/toolkit/src/view/recipe-editor/ReleasePopover.tsx, packages/toolkit/src/view/recipe-editor/ShareDialogTrigger.tsx, packages/toolkit/src/view/recipe-editor/ToolkitDialogTrigger.tsx, packages/toolkit/src/view/recipe-editor/VscodeEditor.tsx, packages/toolkit/src/view/recipe-editor/commands/ActionCmdk.tsx, packages/toolkit/src/view/recipe-editor/commands/ComponentCmdo.tsx, packages/toolkit/src/view/recipe-editor/schema.ts, packages/toolkit/src/view/recipe-editor/sidebar/ComponentSection.tsx, packages/toolkit/src/view/recipe-editor/sidebar/OutputSection.tsx, packages/toolkit/src/view/recipe-editor/sidebar/Sidebar.tsx, packages/toolkit/src/view/recipe-editor/sidebar/SidebarSection.tsx, packages/toolkit/src/view/recipe-editor/sidebar/SubscribeCTA.tsx, packages/toolkit/src/view/recipe-editor/sidebar/VariableSection.tsx, packages/toolkit/src/view/recipe-editor/validateVSCodeYaml.ts, pnpm-lock.yaml
Because
- revamp the add component dialog and the import recipe function 
This commit
- revamp the add component dialog and the import recipe function
=> feat: revamp the add component dialog and the import recipe function

packages/sdk/src/vdp/pipeline/types.ts, packages/toolkit/package.json, packages/toolkit/src/components/GeneralDeleteResourceDialog.tsx, packages/toolkit/src/constant/pipeline.ts, packages/toolkit/src/view/pipeline/view-pipelines/CreatePipelineDialog.tsx, packages/toolkit/src/view/recipe-editor/InOutputEmptyView.tsx, packages/toolkit/src/view/recipe-editor/Input.tsx, packages/toolkit/src/view/recipe-editor/Output.tsx, packages/toolkit/src/view/recipe-editor/RecipeEditorView.tsx, packages/toolkit/src/view/recipe-editor/VscodeEditor.tsx
Because
- Make the hints more readable
- Set up the initial hint comment when user create the pipeline
This commit
- enrich low-code editor hint features
=> feat: enrich low-code editor hint features

packages/toolkit/package.json, packages/toolkit/src/lib/react-query-service/model/useTriggerUserModelVersionAsync.ts
=> fix model trigger path

packages/sdk/package.json, packages/sdk/src/model/ModelClient.ts, packages/sdk/src/model/types.ts, packages/toolkit/package.json, packages/toolkit/src/lib/react-query-service/model/index.ts, packages/toolkit/src/lib/react-query-service/model/useLastModelTriggerResult.ts, packages/toolkit/src/lib/react-query-service/model/useModelVersionTriggerResult.ts, packages/toolkit/src/lib/vdp-sdk/model/queries.ts, packages/toolkit/src/lib/vdp-sdk/model/types.ts, packages/toolkit/src/view/model/view-model/ModelPlayground.tsx
Because
- On the model page there was no way to fetch specific version last run result
This commit
- Now there is
=> fix: fetch specific version operation

packages/toolkit/package.json, packages/toolkit/src/view/model/view-model/ModelPlayground.tsx
I messed up using user's id as a `namespaceId`.
=> fix: fix model triggering

packages/design-system/src/new-ui/Icons/MagicWand01.tsx, packages/design-system/src/new-ui/Icons/index.ts, packages/toolkit/src/view/recipe-editor/RecipeEditorView.tsx, packages/toolkit/src/view/recipe-editor/getting-started-view/GettingStartedView.tsx, packages/toolkit/src/view/recipe-editor/getting-started-view/codeTemplate.ts, packages/toolkit/src/view/recipe-editor/getting-started-view/index.ts, packages/toolkit/src/view/recipe-editor/sidebar/SupportLinks.tsx
Because
- add getting started view into low-code editor
- Getting started will be the guidance for user first time enter the editor
This commit
- add getting started view into low-code editor
=> feat(editor): add getting started view into low-code editor

packages/toolkit/package.json, packages/toolkit/src/view/pipeline/view-pipeline/PipelineContentViewer.tsx, packages/toolkit/src/view/pipeline/view-pipeline/PipelineVersions.tsx
Because
- no need to the test button when we have the versions dropdown
This commit
- removed the test button from the pipeline versions table
=> feat: removed Test button from pipeline versions table

packages/toolkit/src/view/recipe-editor/Output.tsx, packages/toolkit/src/view/recipe-editor/RecipeEditorView.tsx, packages/toolkit/src/view/recipe-editor/RunButton.tsx, packages/toolkit/src/view/recipe-editor/VscodeEditor.tsx, packages/toolkit/src/view/recipe-editor/flow/nodes/GeneralNode.tsx, packages/toolkit/src/view/recipe-editor/lib/tomorrowTheme.ts, packages/toolkit/src/view/recipe-editor/lib/useEditorCommandListener.ts
Because
- fix unable to copy recipe when version is not latest
This commit
- fix unable to copy recipe when version is not latest
=> fix(editor): fix unable to copy recipe when version is not latest

packages/sdk/package.json, packages/toolkit/package.json, packages/toolkit/src/constant/pipeline.ts, packages/toolkit/src/lib/use-instill-form/transform/transformInstillFormTreeToDefaultValue.ts, packages/toolkit/src/view/recipe-editor/RecipeEditorView.tsx, packages/toolkit/src/view/recipe-editor/VscodeEditor.tsx, packages/toolkit/src/view/recipe-editor/getting-started-view/codeTemplate.ts, packages/toolkit/src/view/recipe-editor/lib/schema.ts, packages/toolkit/src/view/recipe-editor/lib/validateVSCodeYaml.ts
Because
- fix can not correctly hint model key
- We should correctly hint input[key] when it has enum
This commit
- fix can not correctly hint model key
=> fix(editor): fix can not correctly hint model key

packages/toolkit/src/view/pipeline/view-pipeline/PipelineRunViews/Run.tsx
Slack discussion: https://instill-ai.slack.com/archives/C02DEV2BWRZ/p1724736903635759
=> feat: make the recipe code block to have max height

packages/design-system/src/new-ui/Popover/Popover.tsx, packages/toolkit/src/lib/use-instill-store/editorSlice.ts, packages/toolkit/src/lib/use-instill-store/types.ts, packages/toolkit/src/view/recipe-editor/EditorButtonTooltipWrapper.tsx, packages/toolkit/src/view/recipe-editor/EditorViewSectionBar.tsx, packages/toolkit/src/view/recipe-editor/RecipeEditorView.tsx, packages/toolkit/src/view/recipe-editor/RunButton.tsx, packages/toolkit/src/view/recipe-editor/VscodeEditor.tsx, packages/toolkit/src/view/recipe-editor/commands/ActionCmdk.tsx, packages/toolkit/src/view/recipe-editor/commands/ComponentCmdo.tsx, packages/toolkit/src/view/recipe-editor/dialogs/ImportRecipeDialog.tsx, packages/toolkit/src/view/recipe-editor/dialogs/PipelineToolkitDialog.tsx, packages/toolkit/src/view/recipe-editor/dialogs/share-pipeline-dialog/SharePipelineDialog.tsx, packages/toolkit/src/view/recipe-editor/flow/Flow.tsx, packages/toolkit/src/view/recipe-editor/flow/nodes/GeneralNode.tsx, packages/toolkit/src/view/recipe-editor/lib/useEditorCommandListener.ts, packages/toolkit/src/view/recipe-editor/popovers/PipelineNamePopover.tsx, packages/toolkit/src/view/recipe-editor/popovers/ReleasePopover.tsx
Because
- add tooltip information on interactive button
This commit
- add tooltip information on interactive button
=> feat(editor): add tooltip information on interactive button

packages/toolkit/src/lib/use-instill-form/transform/transformInstillFormTreeToDefaultValue.test.ts, packages/toolkit/src/lib/use-instill-store/types.ts, packages/toolkit/src/view/pipeline/view-pipeline/Head.tsx, packages/toolkit/src/view/pipeline/view-pipeline/PipelineContentViewer.tsx, packages/toolkit/src/view/recipe-editor/RecipeEditorView.tsx, packages/toolkit/src/view/recipe-editor/getting-started-view/GettingStartedView.tsx, packages/toolkit/src/view/recipe-editor/getting-started-view/index.ts, packages/toolkit/src/view/recipe-editor/sidebar/SupportLinks.tsx
Because
- remove preview tab from pipeline overview
This commit
- remove preview tab from pipeline overview
=> feat: remove preview tab from pipeline overview

apps/console/package.json, apps/instill-form-playground/package.json, package.json, packages/design-system/package.json, packages/design-tokens/package.json, packages/toolkit/package.json, pnpm-lock.yaml
Because
- fix ts version that cause build issue
This commit
- fix ts version that cause build issue
=> fix: fix ts version that cause build issue

packages/design-system/src/new-ui/Icons/Eyeoff.tsx, packages/design-system/src/new-ui/Icons/index.ts, packages/sdk/src/vdp/pipeline/types.ts, packages/toolkit/src/components/ClonePipelineDialog.tsx, packages/toolkit/src/components/EmptyView.tsx, packages/toolkit/src/constant/pipeline.ts, packages/toolkit/src/view/pipeline-builder/components/BackToLatestVersionTopBar.tsx, packages/toolkit/src/view/pipeline-builder/components/BottomBar.tsx, packages/toolkit/src/view/pipeline-builder/lib/hooks/usePipelineBuilderGraph.tsx, packages/toolkit/src/view/pipeline-builder/lib/hooks/useSavePipeline.tsx, packages/toolkit/src/view/pipeline/view-pipeline/PipelinePlayground.tsx, packages/toolkit/src/view/pipeline/view-pipelines/CreatePipelineDialog.tsx, packages/toolkit/src/view/recipe-editor/PreviewEmptyView.tsx, packages/toolkit/src/view/recipe-editor/RecipeEditorView.tsx, packages/toolkit/src/view/recipe-editor/VscodeEditor.tsx, packages/toolkit/src/view/recipe-editor/commands/ComponentCmdo.tsx, packages/toolkit/src/view/recipe-editor/lib/validateVSCodeYaml.ts
Because
- support saving non-valid recipe
This commit
- support saving non-valid recipe
=> feat(editor): support saving non-valid recipe

packages/toolkit/package.json, packages/toolkit/src/view/recipe-editor/commands/ComponentCmdo.tsx, packages/toolkit/src/view/recipe-editor/lib/schema.ts, packages/toolkit/src/view/recipe-editor/lib/validateVSCodeYaml.ts
Because
- When add the component into the recipe, the indent is wrong, causing issue
This commit
- fix the wrong indent when adding the component into recipe
=> fix(editor): fix the wrong indent when adding the component into recipe

packages/toolkit/src/components/ModelStateLabel.tsx, packages/toolkit/src/view/model/view-model/ModelPlayground.tsx, packages/toolkit/src/view/pipeline/view-pipeline/PipelinePlayground.tsx
Because
- Change loading spinner colors to accent in Playgrounds
=> fix(model): fix loading spinner colours 

packages/toolkit/src/view/model/view-model/ModelPlayground.tsx, packages/toolkit/src/view/pipeline/view-pipeline/PipelinePlayground.tsx
Because
- Position of LoadingSpin should be static
=> fix(model): fix LoadingSpin position 

packages/sdk/package.json, packages/sdk/src/helper/getInstillAdditionalHeaders.ts, packages/sdk/src/model/ModelClient.ts, packages/sdk/src/model/types.ts, packages/sdk/src/vdp/trigger/TriggerClient.ts, packages/sdk/src/vdp/trigger/types.ts, packages/toolkit/package.json, packages/toolkit/src/constant/pipeline.ts, packages/toolkit/src/lib/react-query-service/model/useTriggerUserModelVersionAsync.ts, packages/toolkit/src/lib/react-query-service/pipeline/index.ts, packages/toolkit/src/lib/react-query-service/pipeline/useStreamingTriggerUserPipelineRelease.tsx, packages/toolkit/src/lib/react-query-service/pipeline/useTriggerNamespacePipeline.tsx, packages/toolkit/src/lib/react-query-service/pipeline/useTriggerNamespacePipelineRelease.tsx, packages/toolkit/src/lib/use-instill-form/transform/transformInstillFormTreeToDefaultValue.ts, packages/toolkit/src/lib/use-instill-form/useInstillForm.tsx, packages/toolkit/src/lib/use-instill-store/editorSlice.ts, packages/toolkit/src/lib/use-instill-store/types.ts, packages/toolkit/src/view/model/view-model/ModelPlayground.tsx, packages/toolkit/src/view/model/view-model/ModelRunViews/Run.tsx, packages/toolkit/src/view/pipeline-builder/components/dialogs/publish-pipeline-dialog/PublishPipelineDialog.tsx, packages/toolkit/src/view/pipeline-builder/components/top-control-menu/TopControlMenu.tsx, packages/toolkit/src/view/pipeline/view-pipeline/Menu.tsx, packages/toolkit/src/view/pipeline/view-pipeline/PipelinePlayground.tsx, packages/toolkit/src/view/recipe-editor/RecipeEditorView.tsx, packages/toolkit/src/view/recipe-editor/VscodeEditor.tsx, packages/toolkit/src/view/recipe-editor/commands/ComponentCmdo.tsx, packages/toolkit/src/view/recipe-editor/flow/nodes/GeneralNode.tsx, packages/toolkit/src/view/recipe-editor/input/Input.tsx, packages/toolkit/src/view/recipe-editor/popovers/ReleasedVersionPopover.tsx
Because
- fix can not trigger release pipeline in editor
This commit
- fix can not trigger release pipeline in editor
=> fix: fix can not trigger release pipeline in editor

packages/toolkit/src/view/model/view-model/ModelPlayground.tsx
Because
- adjust margin for model run output
This commit
-adjust margin for model run output
=> fix: adjust margin for model run output

packages/toolkit/src/view/recipe-editor/dialogs/ImportRecipeDialog.tsx
Because
- resolve import file issue related to file extension
This commit
- resolve import file issue related to file extension
=> fix: resolve import file issue related to file extension

packages/sdk/src/vdp/types.ts, packages/toolkit/src/constant/pipeline.ts, packages/toolkit/src/lib/use-smart-hint/transformPipelineTriggerRequestFieldsToSmartHints.ts, packages/toolkit/src/view/pipeline-builder/components/nodes/response-node/ResponseNode.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/variable-node/VariableNode.tsx, packages/toolkit/src/view/pipeline/view-pipeline/PipelinePlayground.tsx, packages/toolkit/src/view/recipe-editor/VscodeEditor.tsx, packages/toolkit/src/view/recipe-editor/input/Input.tsx, packages/toolkit/src/view/recipe-editor/sidebar/OutputSection.tsx, packages/toolkit/src/view/recipe-editor/sidebar/VariableSection.tsx
Because
- adapt the possibility that BE might return a null variable
This commit
- adapt the possibility that BE might return a null variable
=> fix: adapt the possibility that BE might return a null variable

packages/toolkit/src/view/recipe-editor/commands/ComponentCmdo.tsx
Because
- fix add component dialog result wrong pre-filled error
This commit
- correct rendering of add component placeholder value
=> fix: fix add component dialog result wrong pre-filled error

packages/toolkit/src/view/recipe-editor/RecipeEditorView.tsx
Because
- allow restoring history after formatting the code
This commit
- allow restoring history after formatting the code
=> feat(editor): allow restoring history after formatting the code

packages/toolkit/src/view/settings/api-tokens/SelectOrganization.tsx
=> fix(settings): fix incorrect Requester-Uid header

packages/toolkit/src/constant/pipeline.ts
Because
- [Slack message](https://instill-ai.slack.com/archives/C07BKQKUW1X/p1725455445171839)
This commit
- adds a case for any file for the pipeline payload generator
=> fix: update payload generator for any files

packages/toolkit/src/view/pipeline/view-pipeline/PipelinePlayground.tsx
Because
- use title to display output on pipeline playground
This commit
- use title to display output on pipeline playground
=> feat: use title to display output on pipeline playground

packages/toolkit/src/view/recipe-editor/input/Input.tsx
Because
- replace asyncIterator with ReadableStream to enable streaming in Safari
This commit
- replace asyncIterator with ReadableStream to enable streaming in Safari
=> feat(editor): replace asyncIterator with ReadableStream to enable streaming in Safari

packages/toolkit/src/view/pipeline/view-pipelines/CreatePipelineDialog.tsx, packages/toolkit/src/view/recipe-editor/input/Input.tsx
Because
- auto focus pipelineId field create pipeline dialog on open
This commit
- auto focus pipelineId field create pipeline dialog on open
=> feat(QoL): auto focus pipelineId field create pipeline dialog on open

packages/toolkit/src/lib/use-instill-form/components/regular/ObjectArrayForm.tsx, packages/toolkit/src/lib/use-instill-form/transform/transformInstillFormTreeToDefaultValue.ts, packages/toolkit/src/lib/use-instill-form/useInstillForm.tsx, packages/toolkit/src/lib/use-instill-store/editorSlice.ts, packages/toolkit/src/lib/use-instill-store/types.ts, packages/toolkit/src/view/recipe-editor/VscodeEditor.tsx, packages/toolkit/src/view/recipe-editor/input/Input.tsx, packages/toolkit/src/view/recipe-editor/lib/index.ts, packages/toolkit/src/view/recipe-editor/lib/useAutonomousEditorRecipeUpdater.ts, packages/toolkit/src/view/recipe-editor/lib/useDebouncedRecipeUpdater.ts, packages/toolkit/src/view/recipe-editor/lib/useEditorCommandListener.ts
Because
- enable force update shortcut on editor
This commit
-  enable force update shortcut on editor
=> feat(editor): enable force update shortcut on editor

packages/toolkit/src/lib/use-instill-form/components/regular/ObjectArrayForm.tsx, packages/toolkit/src/lib/use-instill-form/pick/pickRegularFieldsFromInstillFormTree.tsx, packages/toolkit/src/lib/use-instill-form/transform/transformInstillFormTreeToInitialSelectedCondition.ts, packages/toolkit/src/view/model/view-model/ModelPlayground.tsx
Because
- There are some issue around the objectArray 
- Add method to deal with append scenario
- Adapt method for remove scenario from @orangecoloured's solution and extends it
This commit
- fix model auto-gen-form array issue with @orangecoloured's solution
=> fix: fix model auto-gen-form array issue with @orangecoloured's solution

packages/toolkit/src/lib/use-instill-form/components/trigger-request-form-fields/TextareasField.tsx, packages/toolkit/src/lib/use-instill-form/components/trigger-request-form-fields/index.ts, packages/toolkit/src/lib/use-instill-form/pick/pickPipelineTriggerRequestFormFields.tsx, packages/toolkit/src/lib/use-instill-form/usePipelineTriggerRequestForm.tsx, packages/toolkit/src/view/pipeline/view-pipeline/PipelinePlayground.tsx, packages/toolkit/src/view/pipeline/view-pipeline/PipelineRunViews/Run.tsx, packages/toolkit/src/view/recipe-editor/input/Input.tsx
Because
- force pipeline related string input to be multiline to make input experience better
This commit
- force pipeline related string input to be multiline to make input experience better
=> feat: force pipeline related string input to be multiline to make input experience better

packages/design-system/package.json, packages/sdk/package.json, packages/toolkit/package.json, packages/toolkit/src/lib/use-instill-form/components/component-output/NoOutput.tsx, packages/toolkit/src/lib/use-instill-form/components/trigger-request-form-fields/TextareasField.tsx, packages/toolkit/src/lib/use-instill-store/editorSlice.ts, packages/toolkit/src/lib/use-instill-store/types.ts, packages/toolkit/src/view/pipeline/view-pipeline/Head.tsx, packages/toolkit/src/view/pipeline/view-pipeline/PipelineContentViewer.tsx, packages/toolkit/src/view/pipeline/view-pipeline/PipelinePreview.tsx, packages/toolkit/src/view/recipe-editor/RecipeEditorView.tsx, packages/toolkit/src/view/recipe-editor/flow/Flow.tsx, packages/toolkit/src/view/recipe-editor/flow/nodes/GeneralNode.tsx, packages/toolkit/src/view/recipe-editor/flow/nodes/IteratorNode.tsx, packages/toolkit/src/view/recipe-editor/flow/nodes/NodeBase.tsx
Because
- use the preview in the editor as the pipeline preview tab
This commit
- use the preview in the editor as the pipeline preview tab
=> feat: use the preview in the editor as the pipeline preview tab

packages/toolkit/src/components/ClonePipelineDialog.tsx
Because
- fix clone pipeline dialog will expand when cloning
This commit
- fix clone pipeline dialog will expand when cloning
=> fix: fix clone pipeline dialog will expand when cloning

packages/toolkit/package.json, packages/toolkit/src/view/settings/integrations/AvailableIntegration.tsx, packages/toolkit/src/view/settings/integrations/ConnectionForm.tsx, packages/toolkit/src/view/settings/integrations/ExistingConnection.tsx
Because
- fix multiple integration form issue
This commit
- fix multiple integration form issue
=> fix: fix multiple integration form issue

packages/toolkit/package.json, packages/toolkit/src/view/model/view-model/ModelPlayground.tsx, packages/toolkit/src/view/recipe-editor/flow/nodes/NodeBase.tsx, packages/toolkit/src/view/recipe-editor/input/Input.tsx, packages/toolkit/src/view/recipe-editor/input/parseEventReadableStream.ts
Because
- fix streaming output image cannot display on the editor output
This commit
- fix streaming output image cannot display on the editor output
=> fix(editor): fix streaming output image cannot display on the editor output

packages/toolkit/src/lib/use-instill-form/components/regular/ObjectArrayForm.tsx, packages/toolkit/src/lib/use-instill-form/pick/pickRegularFieldsFromInstillFormTree.tsx
Because
- update object array style
This commit
- update object array style
=> feat: update object array style

packages/toolkit/package.json, packages/toolkit/src/lib/react-query-service/mgmt/use-user/server.ts
Because
- fix user profile is not public available
This commit
- fix user profile is not public available
=> fix: fix user profile is not public available

packages/design-system/package.json, packages/design-system/src/ui-helpers/getModelInstanceTaskToolkit.tsx, packages/sdk/package.json, packages/toolkit/package.json, packages/toolkit/src/lib/use-instill-form/components/component-output/MDTextViewer.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output/TextField.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output/TextsField.tsx, packages/toolkit/src/lib/use-instill-form/pick/pickComponentOutputFieldsFromInstillFormTree.tsx, packages/toolkit/src/lib/use-instill-form/useComponentOutputFields.tsx, packages/toolkit/src/lib/use-instill-form/useInstillForm.tsx, packages/toolkit/src/view/model/view-model/ModelPlayground.tsx, packages/toolkit/src/view/model/view-model/ModelRunViews/Run.tsx, packages/toolkit/src/view/pipeline-builder/components/ComponentOutputs.tsx, packages/toolkit/src/view/pipeline/view-pipeline/PipelinePlayground.tsx, packages/toolkit/src/view/pipeline/view-pipeline/PipelineRunViews/Run.tsx, packages/toolkit/src/view/recipe-editor/Output.tsx
Because
- fix model output issue
This commit
- fix model output issue
=> fix: fix model output issue

packages/toolkit/package.json, packages/toolkit/src/lib/use-instill-form/transform/transformInstillFormTreeToInitialSelectedCondition.ts, packages/toolkit/src/lib/use-instill-form/useInstillForm.tsx, packages/toolkit/src/view/model/view-model/ModelPlayground.tsx
Because
- fix form condition not correctly get selected condition
This commit
- fix form condition not correctly get selected condition
=> fix: fix form condition not correctly get selected condition

packages/sdk/src/model/ModelClient.ts, packages/sdk/src/model/types.ts, packages/toolkit/src/lib/react-query-service/model/usePaginatedModelRuns.ts, packages/toolkit/src/view/model/view-model/ModelRunViews/List.tsx, packages/toolkit/src/view/model/view-model/ModelRunViews/Run.tsx
Because
- Jeremy asked to add the requester id header to the model runs request
This commit
- done
=> fix: add requester id header to model runs request

packages/design-system/src/new-ui/Toast/Toast.tsx, packages/design-system/src/new-ui/Toast/Toaster.tsx, packages/toolkit/src/view/model/view-model/ModelPlayground.tsx
=> fix: show operation error in model playground

packages/toolkit/src/view/recipe-editor/RecipeEditorView.tsx
Because
- make left sidebar width adjustable
This commit
- make left sidebar width adjustable
=> feat(editor): make left sidebar width adjustable

packages/toolkit/src/view/recipe-editor/flow/nodes/NodeBase.tsx
Because
- Make the node easier to read
This commit
- update node border radius and id style
=> feat(editor): update node border radius and id style

apps/console/src/app/[entity]/models/[id]/page.tsx, apps/console/src/app/[entity]/pipelines/[id]/page.tsx, packages/toolkit/package.json, packages/toolkit/src/view/recipe-editor/RunButton.tsx, packages/toolkit/src/view/recipe-editor/lib/schema.ts, packages/toolkit/src/view/recipe-editor/lib/useIsMac.ts, packages/toolkit/src/view/recipe-editor/sidebar/Sidebar.tsx
Because
- fix recipe didn't allow asana component
This commit
- fix recipe didn't allow asana component
=> fix(editor): fix recipe didn't allow asana component

packages/toolkit/src/lib/use-instill-form/useInstillForm.tsx, packages/toolkit/src/view/recipe-editor/VscodeEditor.tsx, packages/toolkit/src/view/recipe-editor/commands/ComponentCmdo.tsx
Because
- fix can not activate hint for variable
This commit
- fix can not activate hint for variable
=> fix(editor): fix can not activate hint for variable

packages/toolkit/src/view/recipe-editor/commands/ComponentCmdo.tsx
Because
- fix broken CMDO when user added component once
This commit
- fix broken CMDO when user added component once
=> fix(editor): fix broken CMDO when user added component once

packages/toolkit/src/view/recipe-editor/flow/nodes/ComponentOutputView.tsx, packages/toolkit/src/view/recipe-editor/flow/nodes/GeneralNode.tsx, packages/toolkit/src/view/recipe-editor/flow/nodes/IteratorNode.tsx, packages/toolkit/src/view/recipe-editor/flow/nodes/NodeBase.tsx
Because
- add view for per component output
This commit
- add view for per component output
=> feat(editor): add view for per component output

packages/toolkit/src/lib/use-instill-store/editorSlice.ts, packages/toolkit/src/lib/use-instill-store/types.ts, packages/toolkit/src/view/catalog/components/lib/helpers.tsx, packages/toolkit/src/view/recipe-editor/RecipeEditorView.tsx, packages/toolkit/src/view/recipe-editor/popovers/ReleasedVersionPopover.tsx
Because
- fix editor height not responsive issue
This commit
- fix editor height not responsive issue
=> fix(editor): fix editor height not responsive issue

packages/toolkit/src/constant/index.ts, packages/toolkit/src/constant/resourceIdPrefix.ts, packages/toolkit/src/server/utility/formatResourceId.ts, packages/toolkit/src/server/utility/index.ts, packages/toolkit/src/view/catalog/components/CreateCatalogDialog.tsx, packages/toolkit/src/view/model/CreateModelForm.tsx, packages/toolkit/src/view/pipeline/view-pipelines/CreatePipelineDialog.tsx, packages/toolkit/src/view/recipe-editor/popovers/PipelineNamePopover.tsx
Because
- hint transformed id on model and pipeline creation
This commit
- hint transformed id on model and pipeline creation
=> feat: hint transformed id on model and pipeline creation

packages/design-system/package.json, packages/sdk/package.json, packages/toolkit/package.json, packages/toolkit/src/view/recipe-editor/commands/ComponentCmdo.tsx
Because
- fix CMDO not correctly initialized searchCode issue
This commit
- fix CMDO not correctly initialized searchCode issue
=> fix(editor): fix CMDO not correctly initialized searchCode issue

packages/toolkit/src/components/card-model/Tags.tsx, packages/toolkit/src/components/card-pipeline/CardPipeline.tsx, packages/toolkit/src/components/card-pipeline/Stats.tsx, packages/toolkit/src/components/card-pipeline/Tags.tsx
Because
- Capitalise Featured tag and Private/Public label 
- Change Triggered to runs
- Change Runs icon in models
=> fix(explore): fix capitalise some tags

packages/toolkit/src/view/recipe-editor/lib/PipelineFlowFactory/edgeHelpers/getConnectableReferencePathsFromRecipe.ts, packages/toolkit/src/view/recipe-editor/lib/PipelineFlowFactory/edgeHelpers/getUserDefinedReferencesFromRecipe.ts
Because
- fix iterator connection is missing
This commit
- fix iterator connection is missing
=> fix(recipe-editor): fix iterator connection is missing

packages/toolkit/src/view/recipe-editor/VscodeEditor.tsx, packages/toolkit/src/view/recipe-editor/input/Input.tsx, packages/toolkit/src/view/recipe-editor/lib/useAutonomousEditorRecipeUpdater.ts, packages/toolkit/src/view/recipe-editor/lib/useDebouncedRecipeUpdater.ts
Because
- save unsaved pipeline when user run before auto-save
This commit
- save unsaved pipeline when user run before auto-save
=> feat(editor): save unsaved pipeline when user run before auto-save

packages/toolkit/src/view/recipe-editor/VscodeEditor.tsx
Because
- fix recipe editor's autocomplete gives duplicated suggestion
This commit
- fix recipe editor's autocomplete gives duplicated suggestion
=> fix(vdp): fix recipe editor's autocomplete gives duplicated suggestion

packages/sdk/src/vdp/pipeline/types.ts, packages/toolkit/src/components/ClonePipelineDialog.tsx
Because
- update and adapt clone namespace pipeline endpoint
This commit
- update and adapt clone namespace pipeline endpoint
=> feat(vdp): update and adapt clone namespace pipeline endpoint

apps/console/src/app/api/nextauth/redirect-error-page/route.ts, apps/console/src/app/api/nextauth/redirect-signin-page/route.ts, packages/toolkit/package.json, packages/toolkit/src/lib/integrations/core.ts, packages/toolkit/src/view/recipe-editor/VscodeEditor.tsx
Because
- the getInstillClient on the sdk has wrongly cache issue on Vercel SSR
This commit
- the getInstillClient on the sdk has wrongly cache issue on Vercel SSR
=> fix: the getInstillClient on the sdk has wrongly cache issue on Vercel SSR

packages/sdk/package.json, packages/sdk/src/application/ApplicationClient.ts, packages/sdk/src/application/index.ts, packages/sdk/src/application/types.ts, packages/sdk/src/catalog/CatalogClient.ts, packages/sdk/src/catalog/index.ts, packages/sdk/src/catalog/types.ts, packages/sdk/src/index.ts, packages/sdk/src/main/index.ts, packages/toolkit/src/lib/vdp-sdk/index.ts, packages/toolkit/src/view/catalog/components/lib/index.ts, turbo.json
=> feat(application): feat add sdk

packages/toolkit/src/view/catalog/components/lib/helpers.tsx
Because
- Migrate additional functions to helpers
=> feat(application): feat export functions to helpers 

packages/toolkit/package.json, packages/toolkit/src/view/settings/integrations/Integrations.tsx
Because
- fix integration org page not correctly use selected namespace
This commit
- fix integration org page not correctly use selected namespace
=> fix: fix integration org page not correctly use selected namespace

apps/console/src/app/(providers)/root-provider.tsx, apps/console/src/components/OnboardingForm.tsx, packages/toolkit/src/components/top-bar/CETopbarDropdown.tsx
Because
- refactor onboarding form and align topdown and profile page with cloud
This commit
- refactor onboarding form and align topdown and profile page with cloud
=> fix: refactor onboarding form and align topdown and profile page with cloud

packages/sdk/src/application/ApplicationClient.ts, packages/sdk/src/application/types.ts, packages/sdk/src/catalog/types.ts, packages/toolkit/src/lib/dashboard/formatDateTime.ts
Because
- Add streaming to chat
=> fix(application): fix streaming

apps/console/integration-test/data-testid.ts, apps/console/integration-test/helpers/actions/pipeline.ts, apps/console/integration-test/pages/onboarding.page.ts, apps/console/integration-test/tests/should-change-component-id.test.ts, apps/console/src/components/OnboardingForm.tsx, packages/toolkit/src/constant/data-testid.ts
Because
- fix onboarding form e2e
This commit
- fix onboarding form e2e
=> fix: fix onboarding form e2e

apps/console/public/icons/instill-app.svg, apps/console/src/app/api/integration/[...nextauth]/route.ts, packages/toolkit/package.json, packages/toolkit/src/lib/integrations/core.ts, packages/toolkit/src/view/settings/integrations/connectable-integration/ConnectableIntegration.tsx
Because
- support Slack OAuth integration
This commit
- support Slack OAuth integration
=> feat: support Slack OAuth integration

README.md, docs/integration-connection.md
Because
- add contribution guideline about the integration connection
This commit
- add contribution guideline about the integration connection
=> feat: add contribution guideline about the integration connection

packages/sdk/package.json, packages/sdk/src/application/ApplicationClient.ts, packages/sdk/src/application/types.ts, packages/toolkit/package.json
Because
- add optional ifAll to the SDK endpoint
=> feat(application): add ifAll to listMessages

packages/toolkit/package.json, packages/toolkit/src/view/recipe-editor/lib/schema.ts
Because
- enable instill-app component in recipe validation
This commit
- enable instill-app component in recipe validation
=> feat: enable instill-app component in recipe validation

packages/toolkit/src/view/pipeline/view-pipeline/PipelinePlayground.tsx, packages/toolkit/src/view/recipe-editor/input/Input.tsx
Because
- fix console wrongly parse the JSON object
This commit
- fix console wrongly parse the JSON object
=> fix: fix console wrongly parse the JSON object

apps/console/src/lib/use-app-access-token/client.ts, packages/toolkit/src/lib/vdp-sdk/index.ts, packages/toolkit/src/view/recipe-editor/lib/schema.ts
Because
- We now have a `variable.default` field
This commit
- support default value for variable
=> feat: support default value for variable

packages/design-system/package.json, packages/design-system/src/new-ui/Slider/Slider.stories.tsx, packages/design-system/src/new-ui/Slider/Slider.tsx, packages/design-system/src/new-ui/Slider/index.ts, packages/design-system/src/new-ui/index.ts, pnpm-lock.yaml
Because
- Add slider 
This commit
=> feat(design-system): feat add slider 

packages/toolkit/src/view/catalog/components/CreateCatalogCard.tsx
Because
- Align with Application card and remove floating tooltip from card
=> fix(catalog): fix remove floating tooltip from card

apps/console/src/app/[entity]/page.tsx, packages/sdk/generate-mocks/generate.ts, packages/sdk/generate-mocks/transform.ts, packages/sdk/src/core/membership/MembershipClient.test.ts, packages/sdk/src/core/user/UserClient.test.ts, packages/sdk/src/core/user/UserClient.ts, packages/sdk/src/core/user/types.ts, packages/sdk/src/helper/getQueryString.ts, packages/sdk/src/vdp/pipeline/PipelineClient.test.ts, packages/sdk/src/vdp/pipeline/PipelineClient.ts, packages/toolkit/src/lib/react-query-service/mgmt/use-user/client.ts, packages/toolkit/src/lib/react-query-service/mgmt/use-user/server.ts, packages/toolkit/src/lib/react-query-service/queryKeyStore.ts, packages/toolkit/src/view/profile/user-profile-view/UserProfileView.tsx
Because
- We have many endpoints which have many queryParam, these need to be tested with integration-test. So this ticket will make all the endpoint's integration test check whether the implementation of sdk obey protobuf
https://openapi.instill.tech/reference/pipelinepublicservice_listpipelines
This commit
- make the sdk e2e test mark every queryParam as required
=> feat: make the sdk e2e test mark every queryParam as required

packages/sdk/package.json, packages/sdk/src/core/credit/CreditClient.test.ts, packages/sdk/src/core/credit/CreditClient.ts, packages/sdk/src/core/credit/types.ts, packages/toolkit/package.json, packages/toolkit/src/components/top-bar/NamespaceSwitch.tsx, packages/toolkit/src/components/top-bar/RemainingCredit.tsx, packages/toolkit/src/lib/react-query-service/catalog/useGetNamespaceCatalogSingleSourceOfTruthFile.ts, packages/toolkit/src/lib/react-query-service/mgmt/index.ts, packages/toolkit/src/lib/react-query-service/mgmt/onTriggerInvalidateCredits.ts, packages/toolkit/src/lib/react-query-service/mgmt/useGetNamespaceRemainingInstillCredit.ts, packages/toolkit/src/lib/react-query-service/mgmt/useListNamespacesRemainingInstillCredit.ts, packages/toolkit/src/lib/react-query-service/queryKeyStore.ts, packages/toolkit/src/view/catalog/components/tabs/UploadExploreTab.tsx, packages/toolkit/src/view/model/view-model/ModelPlayground.tsx, packages/toolkit/src/view/pipeline-builder/components/RemainingCreditCTA.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/variable-node/VariableNode.tsx, packages/toolkit/src/view/pipeline/view-pipeline/PipelinePlayground.tsx, packages/toolkit/src/view/recipe-editor/sidebar/RemainingCredit.tsx
Because
- retire name parameter on credit related endpoint
This commit
- retire name parameter on credit related endpoint
=> feat: retire name parameter on credit related endpoint

packages/toolkit/package.json, packages/toolkit/src/view/recipe-editor/RecipeEditorView.tsx
Because
- fix pipeline is new flag not present issue
This commit
- fix pipeline is new flag not present issue
=> fix: fix pipeline is new flag not present issue

packages/toolkit/src/view/catalog/components/DragAndDropUpload.tsx, packages/toolkit/src/view/catalog/components/lib/helpers.tsx, packages/toolkit/src/view/catalog/components/notifications/FileIsBeingDeletedNotification.tsx, packages/toolkit/src/view/catalog/components/notifications/index.ts, packages/toolkit/src/view/catalog/components/tabs/CatalogFilesTab.tsx, packages/toolkit/src/view/catalog/components/tabs/UploadExploreTab.tsx
Because
- Add bottom notification while file is being deleted 
- Remove file upload limit in CE
=> feat(catalog): add notification while file is being deleted 

packages/sdk/package.json, packages/sdk/src/helper/getQueryString.ts, packages/sdk/src/vdp/pipeline/PipelineClient.ts, packages/toolkit/package.json, packages/toolkit/src/lib/react-query-service/pipeline/use-namespace-pipeline/client.ts, packages/toolkit/src/lib/react-query-service/pipeline/use-namespace-pipeline/server.ts, packages/toolkit/src/lib/react-query-service/pipeline/useDeleteNamespacePipeline.ts, packages/toolkit/src/lib/react-query-service/pipeline/useRenameNamespacePipeline.tsx, packages/toolkit/src/lib/react-query-service/pipeline/useUpdateNamespacePipeline.ts, packages/toolkit/src/lib/react-query-service/queryKeyStore.ts
Because
- fix list pipeline's query key is not present, and catalog fileUid issue
This commit
- fix list pipeline's query key is not present, and catalog fileUid issue
=> fix: fix list pipeline's query key is not present, and catalog fileUid issue

packages/sdk/src/helper/getQueryString.ts, packages/toolkit/package.json, packages/toolkit/src/lib/integrations/core.ts, packages/toolkit/src/view/recipe-editor/flow/Flow.tsx, packages/toolkit/src/view/recipe-editor/lib/PipelineFlowFactory/edgeHelpers/matchReference.ts, packages/toolkit/src/view/settings/integrations/existing-connection/ExistingConnection.tsx
Because
- fix pipeline preview is wrong when reference the component in the same iterator
This commit
- fix pipeline preview is wrong when reference the component in the same iterator
=> fix: fix pipeline preview is wrong when reference the component in the same iterator

packages/toolkit/src/lib/use-instill-form/components/trigger-request-form-fields/FileAndStringUploadField.tsx, packages/toolkit/src/view/recipe-editor/flow/nodes/StartNode.tsx, packages/toolkit/src/view/recipe-editor/lib/PipelineFlowFactory/PipelineFlowFactory.ts, packages/toolkit/src/view/recipe-editor/lib/PipelineFlowFactory/edgeHelpers/composeEdgesForReference.ts, packages/toolkit/src/view/recipe-editor/lib/PipelineFlowFactory/nodeHelpers/createNodesFromRunOnEvent.ts
Because
- fix event description example
This commit
- fix event description example
=> fix: fix event description example

packages/toolkit/src/view/pipeline/view-pipeline/PipelinePlayground.tsx, packages/toolkit/src/view/recipe-editor/input/Input.tsx
Because
- upload to blob based on the user selected namespace
This commit
- upload to blob based on the user selected namespace
=> feat: upload to blob based on the user selected namespace

packages/toolkit/src/view/pipeline/view-pipeline/PipelinePlayground.tsx, packages/toolkit/src/view/recipe-editor/input/Input.tsx
Because
- disable auth when use the downloadedBlob URL
This commit
- The security is now controlled by the expiration time of the link
=> feat: disable auth when use the downloadedBlob URL

apps/console/src/app/(providers)/root-provider.tsx, apps/console/src/app/layout.tsx, packages/toolkit/src/components/top-bar/AppTopbar.tsx, packages/toolkit/src/components/top-bar/NavLinks.tsx, packages/toolkit/src/lib/use-instill-store/featureFlagSlice.ts, packages/toolkit/src/lib/use-instill-store/types.ts, packages/toolkit/src/view/recipe-editor/flow/nodes/RunOnEventNode.tsx
Because
- add feature flag for chat
This commit
- add feature flag for chat
=> feat: add feature flag for chat

package.json, pnpm-lock.yaml
Because
- fix low deps issues
This commit
- fix low deps issues
=> fix: fix low priority deps issues

apps/console/public/icons/scheduler.svg, packages/toolkit/src/view/recipe-editor/lib/schema.ts
This commit
- adds `schedule` component into component list
- adds icon
=> chore(component): add `scheduler` component

package.json, pnpm-lock.yaml
Because
- fix nanoid deps
This commit
- fix nanoid deps
=> fix: fix nanoid deps

apps/instill-form-playground/src/pages/index.tsx
Because
- improve auto-gen form playground
This commit
- improve auto-gen form playground
=> feat: improve auto-gen form playground

.github/workflows/nextjs-bundle-analysis.yml
Because
- upgrade upload artifact ci
This commit
- upgrade upload artifact ci
=> fix: upgrade upload artifact ci

apps/console/package.json, apps/instill-form-playground/package.json, packages/toolkit/package.json, pnpm-lock.yaml
=> chore(deps): bump up next js version

apps/console/package.json, apps/instill-form-playground/package.json, packages/toolkit/package.json, pnpm-lock.yaml
Because
- update nextjs version to cope with vulnerability
This commit
- update nextjs version to cope with vulnerability
=> fix: update nextjs version to cope with vulnerability

.github/workflows/integration-test.yml, packages/toolkit/src/constant/pipeline.ts, packages/toolkit/src/view/recipe-editor/lib/schema.ts
Because
- We are going to rename Instill Format to Instill Type.
This commit
- Renames `format` to `type` in variable section.
=> feat(pipeline): rename `format` to `type`

packages/design-system/package.json, packages/design-system/src/new-ui/ContextMenu/ContextMenu.stories.tsx, packages/design-system/src/new-ui/ContextMenu/ContextMenu.tsx, packages/design-system/src/new-ui/ContextMenu/index.ts, packages/design-system/src/new-ui/index.ts, pnpm-lock.yaml
Because
- Add react context menu into design-system
This commit
- Add react context menu into design-system
=> feat: Add react context menu into design-system

packages/toolkit/package.json, packages/toolkit/src/lib/react-query-service/index.ts, packages/toolkit/src/lib/react-query-service/table/useCreateNamespaceTable.ts, packages/toolkit/src/lib/react-query-service/table/useCreateNamespaceTableRow.ts, packages/toolkit/src/lib/react-query-service/table/useDeleteNamespaceTable.ts, packages/toolkit/src/lib/react-query-service/table/useDeleteNamespaceTableRow.ts, packages/toolkit/src/lib/react-query-service/table/useMoveNamespaceTableRow.ts, packages/toolkit/src/lib/react-query-service/table/useUpdateNamespaceTable.ts, packages/toolkit/src/lib/react-query-service/table/useUpdateNamespaceTableColumnDefinitions.ts, packages/toolkit/src/lib/react-query-service/table/useUpdateNamespaceTableRow.ts
Because
- Add disable invalidate flag in table query
This commit
- Add disable invalidate flag in table query
=> feat: Add disable invalidate flag in table query

packages/design-system/package.json, packages/design-system/src/new-ui/Icons/PlusSquare.tsx, packages/design-system/src/new-ui/Icons/index.ts, packages/design-system/src/new-ui/Switch/Switch.tsx, packages/sdk/src/table/TableClient.ts, packages/sdk/src/table/types.ts, packages/toolkit/package.json, packages/toolkit/src/lib/react-query-service/table/index.ts, packages/toolkit/src/lib/react-query-service/table/useExportNamespaceTable.ts
Because
- add export table sdk & react-query
This commit
- add export table sdk & react-query
=> feat: add export table sdk & react-query

packages/sdk/package.json, packages/sdk/src/table/types.ts, packages/toolkit/package.json, packages/toolkit/src/lib/use-instill-store/chatSlice.ts, packages/toolkit/src/lib/use-instill-store/tableSlice.ts, packages/toolkit/src/lib/use-instill-store/types.ts, packages/toolkit/src/lib/use-instill-store/useInstillStore.ts
Because
- add table preview 
This commit
- add table preview
=> feat: add table preview

package.json, packages/design-system/package.json, packages/design-tokens/package.json, packages/toolkit/package.json, pnpm-lock.yaml
Because
- fix several deps vulnerability (vite, vitest)
This commit
- fix several deps vulnerability (vite, vitest)
=> fix: fix several deps vulnerability (vite, vitest)

packages/sdk/src/catalog/types.ts
Because
- update catalog api to make it more flexible
This commit
- update catalog api to make it more flexible
=> feat: update catalog api to make it more flexible

packages/sdk/package.json, packages/sdk/src/chat/ChatClient.ts, packages/sdk/src/chat/types.ts, packages/sdk/src/index.ts, packages/toolkit/package.json, packages/toolkit/src/lib/react-query-service/catalog/useProcessCatalogFiles.ts, packages/toolkit/src/lib/react-query-service/chats/index.ts, packages/toolkit/src/lib/react-query-service/chats/useListNamespaceChatTables.ts, packages/toolkit/src/lib/react-query-service/index.ts, packages/toolkit/src/lib/react-query-service/queryKeyStore.ts
Because
- Add list chat's tables endpoint
This commit
- Add list chat's tables endpoint
=> feat: Add list chat's tables endpoint

packages/design-system/package.json, packages/design-system/src/new-ui/Popover/Popover.tsx
Because
- export Popover portal
This commit
- export Popover portal
=> feat: export Popover portal

packages/sdk/package.json, packages/sdk/src/table/TableClient.ts, packages/sdk/src/table/types.ts, packages/toolkit/package.json, packages/toolkit/src/lib/use-instill-store/tableSlice.ts, packages/toolkit/src/lib/use-instill-store/types.ts
Because
- update types and store for batch operate table's row
This commit
- update types and store for batch operate table's row
=> feat: update types and store for batch operate table's row

packages/toolkit/package.json, packages/toolkit/src/lib/sdk-helper/getInstillAPIClient.ts, packages/toolkit/src/lib/sdk-helper/getInstillApplicationAPIClient.ts, packages/toolkit/src/lib/sdk-helper/getInstillArtifactAPIClient.ts, packages/toolkit/src/lib/sdk-helper/getInstillCatalogAPIClient.ts, packages/toolkit/src/lib/sdk-helper/getInstillModelAPIClient.ts
Because
- further fix CF token issue
This commit
- further fix CF token issue
=> fix: further fix CF token issue

apps/console/package.json, apps/instill-form-playground/package.json, package.json, packages/toolkit/package.json, pnpm-lock.yaml
Because
- update more deps vuln fixes
This commit
- update more deps vuln fixes
=> feat: update more deps vuln fixes

package.json, pnpm-lock.yaml
Because
- fix tar-fs-vuln
This commit
- fix tar-fs-vuln
=> fix: fix tar-fs-vuln

packages/sdk/package.json, packages/sdk/src/table/types.ts, packages/toolkit/package.json
Because
- adapt BE new cell value
This commit
- adapt BE new cell value
=> feat: adapt BE new cell value

packages/toolkit/package.json, packages/toolkit/src/lib/use-instill-store/types.ts
Because
- adapt new upload file flow
This commit
- adapt new upload file flow
=> feat: adapt new upload file flow

packages/sdk/package.json, packages/sdk/src/chat/ChatClient.ts, packages/sdk/src/chat/types.ts, packages/toolkit/package.json
Because
- fix chat with agent types
This commit
- fix chat with agent types
=> fix: fix chat with agent types

packages/sdk/package.json, packages/sdk/src/table/types.ts, packages/toolkit/package.json
Because
- add draftMode for table
This commit
- add draftMode for table
=> feat: add draftMode for table

packages/sdk/package.json, packages/sdk/src/table/types.ts, packages/toolkit/package.json
Because
- add selection type in table
This commit
- add selection type in table
=> feat: add selection type in table

packages/sdk/package.json, packages/sdk/src/table/types.ts, packages/toolkit/package.json
Because
- update table cell type to make fileUid in the fileCell optional
This commit
- update table cell type to make fileUid in the fileCell optional
=> feat: update table cell type to make fileUid in the fileCell optional

packages/design-system/package.json, packages/design-system/src/new-ui/Icons/Hash2.tsx
The hash02 icon has wrong path, this PR fixed this issue
=> fix: fix hash02 icon

packages/toolkit/package.json
Our release-please PR has conflict on the toolkit's package.json. This PR try to manually solve the conflict.
=> fix: fix toolkit version number

packages/toolkit/package.json, packages/toolkit/src/view/catalog/components/DragAndDropUpload.tsx, packages/toolkit/src/view/catalog/components/tabs/CatalogMainTab.tsx, packages/toolkit/src/view/catalog/components/tabs/UploadExploreTab.tsx
Addressing this: https://linear.app/instill-ai/issue/INS-7814/bug-catalog-count-and-storage-limit-should-not-be-shown#comment-7d0356ae
=> fix: more file limits removed

packages/design-system/package.json, packages/design-system/src/new-ui/Icons/CheckSquare.tsx, packages/design-system/src/new-ui/Icons/index.ts
We need check-square icon, This PR add it
=> feat: add check-square icon

packages/toolkit/package.json, packages/toolkit/src/lib/use-instill-store/tableSlice.ts, packages/toolkit/src/lib/use-instill-store/types.ts
We need this state to correctly handle the loading of the file uploading in the table.
=> feat: add UploadingFileCells for table file uploading management

apps/console/.gitignore
This PR is purely a trick to make release-please bump up console version
=> feat: bump console version

packages/sdk/package.json, packages/sdk/src/core/subscription/types.ts, packages/toolkit/package.json, packages/toolkit/src/view/catalog/components/lib/helpers.tsx, packages/toolkit/src/view/catalog/components/notifications/InsufficientStorageBanner.tsx, packages/toolkit/src/view/catalog/components/notifications/UpgradePlanLink.tsx
rollback PLAN_STARTER to PLAN_PRO
=> fix: rollback PLAN_STARTER to PLAN_PRO

packages/toolkit/src/view/settings/SettingSidebar.tsx, packages/toolkit/src/view/settings/SettingTab.tsx, packages/toolkit/src/view/settings/user/UserIntegrationsTab.tsx
The privacy link position is changed to increase the clarity
=> fix: fix console integration setting page privacy link

packages/sdk/package.json, packages/sdk/src/core/subscription/types.ts, packages/toolkit/package.json, packages/toolkit/src/view/catalog/components/lib/helpers.tsx, packages/toolkit/src/view/catalog/components/notifications/InsufficientStorageBanner.tsx, packages/toolkit/src/view/catalog/components/notifications/UpgradePlanLink.tsx
We are renaming PLAN_PRO to PLAN_STARTER
=> feat: migrate PLAN_PRO to PLAN_STARTER

.github/workflows/images.yml, .github/workflows/integration-test.yml
Because
- We have updated the login credentials from drop@instill.tech to drop@instill-ai.com in dockerhub.
This commit
-  update the dockerhub credentials  and docker version in ga workflow.
=> ci(workflow): update the dockerhub credentials and docker version in ga workflow

packages/toolkit/src/constant/model.ts, packages/toolkit/src/view/model/CreateModelForm.tsx
This model API page is using the wrong BE api path, this PR fixes this issue
=> fix: fix model api page

release-please/manifest.json
Manually remove console version's beta tag
=> feat: update console release version

packages/toolkit/src/lib/toastInstillError.tsx, packages/toolkit/src/lib/toastInstillSuccess.tsx
=> fix: fix toast duration

packages/toolkit/src/constant/model.ts
The model api page's wording is wrong
=> fix: fix model api path

package.json, pnpm-lock.yaml
The prettier in the root is missing essential package
=> fix: further fix prettier in the root

packages/toolkit/src/components/top-bar/CloudTopbarDropdown.tsx, packages/toolkit/src/components/top-bar/NamespaceSwitch.tsx, packages/toolkit/src/components/top-bar/RemainingCredit.tsx, packages/toolkit/src/view/catalog/CatalogMainView.tsx, packages/toolkit/src/view/catalog/components/CloneCatalogDialog.tsx, packages/toolkit/src/view/catalog/components/tabs/CatalogFilesTab.tsx, packages/toolkit/src/view/recipe-editor/sidebar/SubscribeCTA.tsx
The catalog file tab under some condition will keep fetching non-stop, and it will form an infinte loop and eventually become fire dozens of request per second. This PR fix this issue by replacing the refetching logic with react-query refetchInterval
=> fix: fix catalog file tab refetch interval

packages/sdk/package.json, packages/toolkit/package.json
Bump rc version for toolkit and sdk
=> fix: bump rc version for toolkit and sdk

packages/sdk/package.json, packages/sdk/src/core/organization/types.ts, packages/sdk/src/core/subscription/types.ts, packages/toolkit/package.json, packages/toolkit/src/lib/use-instill-store/generalSlice.ts, packages/toolkit/src/lib/use-instill-store/tableSlice.ts, packages/toolkit/src/lib/use-instill-store/types.ts, packages/toolkit/src/lib/useUserNamespaces.ts
add trial end readonly type and other sdk change
=> feat: add trial end readonly type and other sdk change

.github/workflows/integration-test.yml, packages/sdk/src/folder/FolderClient.ts, packages/sdk/src/folder/types.ts
Because
- we want to integrate new folder files API
This commit
- supports new folder files API.
- updates integration-test workflow.
=> feat: support new folder files API

packages/toolkit/src/lib/react-query-service/queryKeyStore.ts
This commit
- adds missing query key for folder files
=> chore: add query key for folder files

packages/design-system/package.json, packages/design-system/src/new-ui/Icons/Calendar.tsx, packages/design-system/src/new-ui/Icons/index.ts, packages/sdk/package.json, packages/sdk/src/core/organization/types.ts, packages/sdk/src/core/user/types.ts, packages/toolkit/package.json, packages/toolkit/src/components/top-bar/CloudTopbarDropdown.tsx, packages/toolkit/src/lib/react-query-service/organization/use-organization/server.ts, packages/toolkit/src/lib/react-query-service/organization/useOrganizationSubscription.ts, packages/toolkit/src/view/profile/user-profile-view/UserProfileView.tsx
=> fix: fix org sub react-query key

.github/workflows/images.yml, .github/workflows/release-latest-image.yml
Because
- We have to update dockerhub username and password
This commit
- update dockerhub username and password
=> ci(workflows): update dockerhub username and password

.gitignore, Dockerfile, Dockerfile.playwright
This commit
- updates misleading comment and typos in Dockerfiles.
=> ci(Dockerfile): update comment and env syntax
