instill-ai/console

package.json, src/components/forms/OnboardingForm/OnboardingForm.tsx, src/lib/instill/mgmt/mocks.ts, src/lib/instill/mgmt/mutations.ts, src/pages/_app.tsx, src/pages/api/get-user-cookie.ts, src/pages/api/set-user-cookie.ts, src/services/mgmt/useTrackingToken.ts, src/types/general.ts
Because
- We want to persist user tracking token in current session but when user `make down` all data exist in local backend will lose, so we need to persist user tracking token inside session cookie
This commit
- Store user tracking token inside the cookie
=> Use token within cookie to track

src/components/forms/CreatePipelineForm/SetupModelStep/CreateNewModelFlow.tsx, src/components/forms/CreatePipelineForm/SetupModelStep/UseExistingModelFlow.tsx
Because
- When create pipeline, upon the creation of model, backend will return 404.
This commit
=> fix(pipeline): fix 404 not found when create model in the process of creating pipeline

.env, jest.config.js, jest.setup.ts, src/mocks/README.md, src/mocks/handlers/connector/source/getSource.ts, src/mocks/handlers/connector/source/index.ts, src/mocks/handlers/index.ts, src/mocks/server/index.ts, tsconfig.json
Because
- We need unit-test for services
This commit
- add mock source service handler
- setup the correct jest config
=> feat: add mock source service handler

src/components/forms/CreatePipelineForm/SetupPipelineModeStep/SetupPipelineModeStep.tsx
Because
- SetupPipelineModeStep not correctly display pre-selected value
This commit
=> fix: fix selected option issue at SetupPipelineModeStep

.github/workflows/release.yml
Because
- We need to test release please behavior
This commit
- Log release please output
=> chore: log github action output

.github/workflows/release.yml
Because
- Right now release-please use our package.json.name as prefix, need to remove it
This commit
- try to solve above issue with empty package-name config
=> feat: add empty package_name

Dockerfile, docker-compose.app.yml, entrypoint.sh
Because
- We need to let user input disable_usage_collection with env variable
This commit
- refactor docker-compose and implement entrypoint script
=> refactor: refactor docker-compose from args to env

src/components/forms/CreateModelForm/CreateModelForm.tsx, src/components/forms/CreatePipelineForm/SetupModelStep/CreateNewModelInstanceFlow.tsx, src/components/forms/CreatePipelineForm/SetupPipelineDetailsStep/SetupPipelineDetailsStep.tsx
Because
- Some field is optional, but on the console they are still required.
This commit
- Fix this issue
- close #48
=> refactor: remove unnecessary field requirement

src/components/forms/model/CreateModelForm/CreateModelForm.tsx, src/pages/models/[id].tsx
Because
- Missing title at model instance page
- There has a typo when deploy model instance
This commit
=> fix: fix missing title and typo when deploy model instance

src/components/ui/ModelInstanceReadmeCard/ModelInstanceReadmeCard.tsx, src/components/ui/ModelInstanceReadmeCard/index.ts, src/components/ui/index.ts, src/pages/models/[id].tsx
Because
- The model instance's readme card is missing
This commit
- add ModelInstanceReadmeCard
- close #70
=> feat: add model instance's readme card

.github/workflows/images.yml
Because
- Image action had not correctly set up deps
This commit
- Setup deps and node env
=> feat: setup node and install deps

src/pages/models/[id].tsx
Because
- When toggle model instance, it will cause re-ordering the model instance dropdown
This commit
=> fix: fix toggle model instance will cause re-order model instance dropdown issue

src/components/ui/TableCells/NameCell/NameCell.tsx, src/components/ui/TableHeads/ModelTableHead/ModelTableHead.tsx, src/components/ui/TableHeads/index.ts, src/components/ui/Tables/DestinationsTable/DestinationsTable.tsx, src/components/ui/Tables/ModelsTable/ModelsTable.tsx, src/components/ui/Tables/PipelinesTable/PipelinesTable.tsx, src/components/ui/Tables/SourcesTable/SourcesTable.tsx
Because
- It's confusing that model has state
This commit
- Remove model state indicator at models table
=> refactor: remove model state indicator

src/components/ui/TableCells/ModelDefinitionCell/ModelDefinitionCell.tsx
Because
- Model icon is not correctly displayed
- https://github.com/instill-ai/model-backend/issues/116
This commit
- Fix model icon issue
- close #90
=> fix: fix model icon is not correctly displayed issue

.github/workflows/playwright.yml, src/lib/dot/README.md, src/lib/dot/index.test.ts, src/lib/dot/index.ts
Because
- Formik use this kind of path notation to set proper object, we need this kind of function too.
- `dot.setter(obj, "path.to.value", "hi")` will construct `{ path: { to: { value: "hi" }}}`
This commit
- Implement dot.setter and dot.getter
=> feat: add dot notation path setter and getter

src/lib/instill/model/types.ts, src/services/model/useModelInstanceReadme.ts
Because
- #129 
This commit
- Adapt new model readme data structure
- close #129
=> refactor: adapt new model readme data structure

src/components/ui/ModelInstanceReadmeCard/ModelInstanceReadmeCard.tsx
Because
- #136 
This commit
- Make sure readme will correctly render `content=""`
- close #136
=> refactor: make sure readme is correct

src/pages/_document.tsx
Because
- We need ga for tracking traffic on demo.instill.tech
This commit
- add ga code
=> feat: add ga code

src/components/forms/model/CreateModelForm/CreateModelForm.tsx, src/components/forms/pipeline/CreatePipelineForm/SetupModelStep/CreateNewModelInstanceFlow.tsx, src/lib/instill/model/mutations.ts
Because
- #145 
- Before this commit, description stay in the configuration field. After the refactoring of backend, it becomes a field just like id but optional
This commit
- make description field be a universal optional field when create model
- close #145
=> feat: make description field be a universal optional field when create model

src/components/ui/TableCells/ModelDefinitionCell/ModelDefinitionCell.tsx
Because
- We need to display hugging face icon at model table
This commit
- add hugging face icon at model table
=> feat: add hugging face icon at model table

src/components/forms/connector/destination/ConfigureDestinationForm/ConfigureDestinationForm.tsx, src/components/forms/connector/source/ConfigureSourceForm/ConfigureSourceForm.tsx, src/components/forms/model/ConfigureModelForm/ConfigureModelForm.tsx, src/components/forms/pipeline/ConfigurePipelineForm/ConfigurePipelineForm.tsx
Because
- We should stop visitors from deleting resources on demo website, but it didn't
This commit
=> fix: fix delete resource issue

src/components/forms/connector/destination/ConfigureDestinationForm/ConfigureDestinationForm.tsx, src/components/forms/connector/source/ConfigureSourceForm/ConfigureSourceForm.tsx, src/components/forms/model/ConfigureModelForm/ConfigureModelForm.tsx, src/components/forms/pipeline/ConfigurePipelineForm/ConfigurePipelineForm.tsx, src/hooks/useDeleteResourceGuard.ts, src/pages/_document.tsx
Because
- When evaluating the env like
```
if (process.env.NEXT_PUBLIC_CONSOLE_BASE_URL === "hi"){}
```
it will affect by the webpack dead code elimination
This commit
- Use window.location.href to cope with this evaluation
=> fix: fix env variables issue 

e2e/integration/pipeline.spec.ts, src/components/forms/connector/destination/ConfigureDestinationForm/ConfigureDestinationForm.tsx, src/components/forms/connector/destination/CreateDestinationForm/CreateDestinationForm.tsx, src/components/forms/connector/source/ConfigureSourceForm/ConfigureSourceForm.tsx, src/components/ui/TablePlaceholders/DestinationTablePlaceholder/DestinationTablePlaceholder.tsx, src/components/ui/TablePlaceholders/SourceTablePlaceholder/SourceTablePlaceholder.tsx, src/pages/destinations/[id].tsx, src/pages/destinations/create.tsx, src/pages/destinations/index.tsx, src/pages/pipelines/create.tsx, src/pages/sources/[id].tsx, src/pages/sources/create.tsx, src/pages/sources/index.tsx
Because
- Data sources -> Sources
This commit
- Remove all the data prefix before sources and destination
=> refactor: remove all the data prefix before sources and destination

src/components/pipeline/CreatePipelineForm/SetupDestinationStep/UseExistingDestinationFlow.tsx, src/components/pipeline/CreatePipelineForm/SetupSourceStep/UseExistingSourceFlow.tsx
Because
- #259 
This commit
- Fix "Select a existing" -> Select an existing" (close #259)
=> fix: fix typos

src/pages/pipelines/[id].tsx
Because
- #274
This commit
- use env var in pipeline snippet (close #274)
=> feat: use env var in pipeline snippet

integration-test/README.md, integration-test/common/model.ts, integration-test/common/pipeline.ts, integration-test/pipeline.spec.ts, integration-test/source.spec.ts
Because
- The pipeline e2e test is not stable
This commit
- Utilize playwright auto-wait feature and don't manually wait the element become actionable
=> fix: fix pipeline e2e not stable

src/pages/api/set-user-cookie.ts
Currently, our cookie only exists for 2 days. In order to make the onboarding process much more consistent. We want to extend the time span of our user cookie to 30 days.
=> feat: extend the time span of our user cookie

playwright.config.ts
This commit makes playwright test output dot result on CI. If we outpu HTML on CI it will block the workflow.
=> feat: make playwright output dot on CI

integration-test/async-destination.spec.ts, integration-test/helper/global-setup.ts, integration-test/helper/index.ts, integration-test/pipeline.spec.ts, integration-test/source.spec.ts, integration-test/sync-destination.spec.ts
This commit cleans up the source and destination connector after every test.
=> feat: cleanup connector after test

playwright.config.ts
In order to not block other CI tests, we disable HTML report of the playwright.
=> chore: disable html report

integration-test/common/model.ts, integration-test/model-huggingface.spec.ts, src/components/model/ConfigureModelInstanceForm.tsx
This commit add HuggingFace model ID field at model_instance page to help user better navigate the model details (close #299)
=> feat: add hg model id field at model_instance page

.github/workflows/unit-test.yml
Because
- Make the naming of the github workflow consistent
This commit
- Rename the workflow name of this repo
=> refactor: rename workflow name

integration-test/common/model.ts, integration-test/model-artivc.spec.ts, integration-test/model-github.spec.ts, integration-test/model-huggingface.spec.ts, integration-test/model-local.spec.ts
Because
- We need to adapt model-backend long run operation
This commit
- update how we test model detail page
- Make sure we select the right model instance
=> feat: update how we test model detail page

README.md, src/components/ui/PageHead.tsx, src/lib/instill/mgmt/mocks.ts
Because
- instead of Visual Data Preparation, VDP is Versatile Data Pipeline now. We realise that as a general ETL infrastructure, VDP is capable of processing all kinds of unstructured data, and we should not limit its usage to only visual data. That's why we replace the word Visual with Versatile. Besides, the term Data Preparation is a bit misleading, users often think it has something to do with data labelling or cleaning. The term Data Pipeline is definitely more precise to capture the core concept of VDP.
This commit
- update to Versatile Data Pipeline
=> chore: rename Visual Data Preparation to Versatile Data Pipeline

integration-test/common/model.ts
Because
- The model e2e test is still flaky
This commit
- This PR stabilize async model deploying test further
=> feat: stabilize async model deploying test

Dockerfile.playwright, README.md
Because
- We want to provide more flexibility toward our maintainers
This commit
- maintainers can switch the user of test container for DEBUG
=> feat: let maintainer switch playwright container user

integration-test/common/mgmt.ts, integration-test/common/model.ts
Because
- #321
This commit
- Disable test around cookies
=> feat: suspend the test related to cookie

README.md, playwright.config.ts
Because
- Make sure test is more stable
This commit
- We prolong the timeout of console integration test
=> feat: prolong test timeout

src/components/ui/ModelInstanceTaskLabel.tsx
Because
- instance segmentation icon is missing in model label
This commit
- add InstanceSegmentationIcon into label
- close #325
=> feat: add InstanceSegmentationIcon into label

src/components/ui/ModelInstanceTaskLabel.tsx
Because
- The console should support SemanticSegmentationIcon
This commit
- Support SemanticSegmentationIcon in model label
- close #325
=> feat: add SemanticSegmentationIcon to model label

.github/workflows/pr-semantic.yml
Because
- We want to do the semantic title check for PR
This commit
- add pr-semantic workflow
- close #330
=> feat: add pr-semantic workflow

tsconfig.json
Because
- ts-config has typo
This commit
- fix ts config typo
=> fix: fix ts config typo

integration-test/common/model.ts
Because
- model details page is not stable
This commit
-  extend the delay when test model details page to stabilize it
=> feat: extend the delay when test model details page

.github/workflows/unit-test.yml
Because
- We want to test whether the whole app can build
This commit
- run build when test in the workflow
=> feat: run build when test in the workflow

src/pages/api/health.tsx
Because
- We need /health endpoint to facilitate production
This commit
- add health endpoint
=> feat: add health endpoint

Dockerfile, src/components/ui/PageHead.tsx
Because
- We want to have more flexibility toward our environment
This commit
- expose node env as build args
=> feat: expose node env as build args

integration-test/destination-async.spec.ts, integration-test/destination-sync.spec.ts, integration-test/model-artivc.spec.ts, integration-test/model-github.spec.ts, integration-test/model-huggingface.spec.ts, integration-test/model-local.spec.ts, integration-test/pipeline-async.spec.ts, integration-test/pipeline-sync.spec.ts, integration-test/source.spec.ts, playwright.config.ts
Because
- Console is the last to test in make file and we test console separately in CI so we don't need to clean up the resource after test 
This commit
- further stabilize e2e test by removing the clean up function
=> feat: further stabilize e2e test by removing the clean up function

src/components/ui/Tables/PipelinesTable.tsx
Because
- pipeline table's margin bottom is wrong
This commit
- fix pipelines table margin bottom issue
=> fix: fix pipelines table margin bottom issue

src/components/ui/ChangeResourceStateButton.tsx
Because
- when NEXT_PUBLIC_DISABLE_CREATE_UPDATE_DELETE_RESOURCE=true we need to disable all related action
This commit
- fix change resource button is not disabled when we need to
=> fix: fix change resource button is not disabled when we need to

src/pages/api/set-user-cookie.ts
Because
- cookie domain setting is troublesome
This commit
- don't specific domain when set cookie
=> fix: don't specific domain when set cookie

integration-test/helper/login.setup.ts
Because
- the onboarded cookie can not set on http://console:3000 when in the integration-test
This commit
- mock onboarded cookie
=> feat: [INS-267] mock onboarded cookie

Dockerfile.playwright, integration-test/helper/login.setup.ts
Because
- the env import path is wrong
This commit
- fix import path in test
- Add vim into playwright container
=> fix: fix import path in test

package.json, pnpm-lock.yaml
Because
- PipelinesTable has typo
This commit
- fix PipelinesTable typo
=> fix: fix PipelinesTable typo

integration-test/README.md, integration-test/onboarding.spec.ts, package.json
Because
- The onboarding test - `should display error label, if email input format is not correct` is flaky
This commit
- stabilize the onboarding test
=> fix: stabilize the onboarding test

integration-test/destination-async.spec.ts, integration-test/destination-sync.spec.ts, integration-test/pipeline-async.spec.ts, integration-test/pipeline-sync.spec.ts, playwright.config.ts
Because
- helm test on linux is flaky, try to fix it
This commit
- further fix test flakiness
=> fix: further fix test flakiness

integration-test/common/pipeline.ts
Because
- pipeline details page is relatively slow due to the nature of SSR, we need extra timeout here
This commit
- stabilize test related to the pipeline details page
=> feat: stabilize test related to the pipeline details page

src/components/Sidebar/Sidebar.tsx
Because
- the docs link at sidebar is out of date
This commit
- update docs link at sidebar
=> feat: update docs link at sidebar

.env, LICENSE, README.md, integration-test/model-github.spec.ts, package.json, src/components/OnboardingForm.tsx, src/components/PageHead.tsx
Because
- our mission is to make AI accessible to everyone. The best way to achieve this is to make VDP free to use and source available to everyone, while ensuring we safely create a sustainable business. Therefore, we chose ELv2 since it is very permissive. On the one hand, this allows us to provide users with free access to our source code, the permission to modify it. On the other hand, we've released Instill Cloud, a fully-managed public cloud service built upon VDP that offers additional features. With the license, we don't have to worry about our project being taken by some other companies for monetization.
This commit
- add LICENSE
- update integration test GitHub repository
=> chore(license): update VDP license to ELv2 and MIT

.env, src/pages/_app.tsx
Because
- We want to unify the naming rule of the configuration
This commit
- update env name NEXT_PUBLIC_DISABLE_USAGE_COLLECTION to NEXT_PUBLIC_USAGE_COLLECTION_ENABLED
=> chore(env): update env name NEXT_PUBLIC_DISABLE_USAGE_COLLECTION

src/lib/pipeline-builder/constructPipelineRecipe.tsx, src/lib/pipeline-builder/parseDependencyComponents.ts
Because
- The structured_data and metadata syntax should not be wrapped by `[]`
This commit
-  fix pipeline deps wrong syntax
=> fix: fix pipeline deps wrong syntax 

.github/workflows/integration-test.yml
Because
- workflow didn't cover different structure's backend
This commit
- add different structure backend workflow
=> feat: add different structure backend workflow

.github/workflows/integration-test.yml
Because
- Console image not correctly build
This commit
-  build console image before pull on CI
=> chore: build console image before pull on CI

integration-test/integration-test.list.ts
Because
- fix integration-test not correctly import expect
This commit
- fix integration-test not correctly import expect
=> fix: fix integration-test not correctly import expect

package.json, pnpm-lock.yaml, src/pages/[entity]/model-hub/[id].tsx
Because
- model namespace is wrong in instill-core's /models/<model_id> page
This commit
- fix model namespace is wrong in instill-core's /models/<model_id> page
=> fix(model-hub): fix model namespace is wrong in instill-core's /models/<model_id> page

.github/workflows/integration-test.yml, .github/workflows/labeler.yml
Because
- e2e disk size is not enough
This commit
- fix e2e disk size is not enough issue
=> chore: fix e2e disk size is not enough issue

.github/workflows/integration-test.yml
Because
- We have to clean github action hosted runner so can run console image
This commit
- make disk free of GA hosted runner
=> ci(workflow): make disk free of GA hosted runner

package.json, pnpm-lock.yaml
Because
- Improve UX
This commit
- User can have autoresize input when edit node and pipeline name
=> feat(pipeline-builder): User can have autoresize input when edit node and pipeline name

package.json, pnpm-lock.yaml
Because
- operator wrongly delete input when you edit without saving then create a new field
This commit
- fix start operator wrongly delete input when you edit without saving then create a new field
=> fix(pipeline-builder): fix start operator wrongly delete input when you edit without saving then create a new field

package.json, pnpm-lock.yaml
Because
- Backend has new component input structure
This commit
- adapt new component input structure
=> feat(pipeline-builder): adapt new component input structure 

package.json, pnpm-lock.yaml
Because
- Improve UX
This commit
- Make the array fields on start node start with only one field
=> feat(pipeline-builder): make the array fields on start node start with only one field

packages/toolkit/src/lib/use-instill-form/components/BooleanField.tsx, packages/toolkit/src/lib/use-instill-form/components/OneOfConditionField.tsx, packages/toolkit/src/lib/use-instill-form/components/SingleSelectField.tsx, packages/toolkit/src/lib/use-instill-form/components/TextAreaField.tsx, packages/toolkit/src/lib/use-instill-form/components/TextField.tsx, packages/toolkit/src/lib/use-instill-form/pick/pickFieldComponentFromInstillFormTree.tsx, packages/toolkit/src/lib/use-instill-form/useInstillForm.tsx, packages/toolkit/src/lib/useResourceAdditionalForm.tsx
Because
- expose disabledAll props on use-instill-form
This commit
- expose disabledAll props on use-instill-form
=> feat(auto-form-generation): expose disabledAll props on use-instill-form

.github/workflows/integration-test.yml
Because
- we need to remove docker hub login.
This commit
- remove docker hub login
=> ci(workflow): remove docker hub login

apps/instill-form-playground/src/pages/index.tsx, packages/toolkit/src/lib/use-instill-form/components/OneOfConditionField.tsx, packages/toolkit/src/lib/use-instill-form/pick/pickFieldComponentFromInstillFormTree.tsx, packages/toolkit/src/lib/use-instill-form/transform/transformInstillJSONSchemaToFormTree.test.ts, packages/toolkit/src/lib/use-instill-form/transform/transformInstillJSONSchemaToFormTree.ts, packages/toolkit/src/lib/use-instill-form/useInstillForm.tsx, packages/toolkit/src/view/resource/ResourceComponentForm.tsx, packages/toolkit/src/view/resource/ResourceResourceForm.tsx
Because
- User can view the readable title in resource form instead of the key used by backend
This commit
- User can view the readable title in resource form instead of the key used by backend
=> feat(auto-gen-form): User can view the readable title in resource form instead of the key used by backend

packages/toolkit/src/lib/use-instill-form/components/smart-hint/SmartHintList.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/TextArea.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/TextField.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/onClickSmartHint.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/onInputKeydown.tsx, packages/toolkit/src/lib/use-instill-form/pick/pickComponentOutputFieldsFromInstillFormTree.tsx, packages/toolkit/src/lib/use-instill-form/transform/transformInstillJSONSchemaToZod.ts, packages/toolkit/src/lib/use-instill-form/useComponentOutputFields.tsx
Because
- fix smart hint can't correctly handle empty string
This commit
- fix smart hint can't correctly handle empty string
=> fix(smart-hint): fix smart hint can't correctly handle empty string

packages/toolkit/src/view/pipeline-builder/lib/getImageTypeFromBase64.ts
Because
- support webp image type in auto-gen-form
This commit
- support webp image type in auto-gen-form
=> feat(auto-gen-form): support webp image type in auto-gen-form

packages/toolkit/src/lib/use-instill-form/pick/pickComponentOutputFieldsFromInstillFormTree.tsx, packages/toolkit/src/lib/use-instill-form/useComponentOutputFields.tsx
Because
- fix auto-gen-form not correctly handle object array
This commit
- fix auto-gen-form not correctly handle object array
=> fix(auto-gen-form): fix auto-gen-form not correctly handle object array

packages/toolkit/src/lib/use-instill-form/components/smart-hint/TextArea.tsx, packages/toolkit/src/lib/use-instill-form/transform/transformInstillJSONSchemaToFormTree.ts, packages/toolkit/src/lib/use-instill-form/transform/transformInstillJSONSchemaToZod.ts, packages/toolkit/src/lib/use-instill-form/type.ts, packages/toolkit/src/view/pipeline-builder/components/EndNode.tsx
Because
- fix end component didn't correctly handle the key naming rule
This commit
- fix end component didn't correctly handle the key naming rule
=> fix(auto-gen-form): fix end component didn't correctly handle the key naming rule

packages/toolkit/src/lib/use-instill-form/components/smart-hint/TextArea.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/TextField.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/useFilteredHints.tsx, packages/toolkit/src/lib/use-instill-form/pick/pickRegularFieldsFromInstillFormTree.tsx, packages/toolkit/src/lib/use-instill-form/useInstillForm.tsx, packages/toolkit/src/lib/useResourceAdditionalForm.tsx, packages/toolkit/src/view/ai/AIComponentAutoForm.tsx, packages/toolkit/src/view/blockchain/BlockchainComponentAutoForm.tsx, packages/toolkit/src/view/data/DataComponentAutoForm.tsx, packages/toolkit/src/view/pipeline-builder/RightPanel.tsx, packages/toolkit/src/view/resource/ResourceComponentForm.tsx
Because
-  Fix smart hint wrongly hint user to use the same component's output
This commit
-  Fix smart hint wrongly hint user to use the same component's output
=> fix(smart-hint): Fix smart hint wrongly hint user to use the same component's output

packages/toolkit/src/view/pipeline-builder/components/start-node/StartNodeInputForm.tsx
Because
- Fix start component not throw error when user input the incorrect key
This commit
- Fix start component not throw error when user input the incorrect key
=> fix(pipeline-builder): Fix start component not throw error when user input the incorrect key

packages/toolkit/src/components/ObjectViewer.tsx, packages/toolkit/src/view/pipeline-builder/components/ComponentOutputs.tsx, packages/toolkit/src/view/pipeline-builder/components/connector-node/ConnectorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/operator-node/OperatorNode.tsx
Because
- fix output object viewer not correctly open when it's empty
This commit
- fix output object viewer not correctly open when it's empty
=> fix(pipeline-builder): fix output object viewer not correctly open when it's empty

packages/toolkit/src/view/pipeline-builder/components/connector-node/ConnectorNode.tsx
Because
- fix pipeline builder not correctly hide data connector's free form
This commit
- fix pipeline builder not correctly hide data connector's free form
=> fix: fix pipeline builder not correctly hide data connector's free form

packages/toolkit/src/view/pipeline-builder/lib/templates.ts
Because
- fix the start operator's title of our templates too long and break the pipeline
This commit
- fix the start operator's title of our templates too long and break the pipeline
=> fix: fix the start operator's title of our templates too long and break the pipeline

packages/toolkit/src/view/pipeline-builder/components/OpenAdvancedConfigurationButton.tsx
Because
- replace advanced configurations with more in pipeline-builder's node
This commit
- replace advanced configurations with more in pipeline-builder's node
=> chore: replace advanced configurations with more in pipeline-builder's node

packages/design-system/src/ui-helpers/getModelInstanceTaskToolkit.tsx
Because
- fix TASK_VISUAL_QUESTION_ANSWERING model task typo
This commit
- fix TASK_VISUAL_QUESTION_ANSWERING model task typo
=> fix: fix TASK_VISUAL_QUESTION_ANSWERING model task typo

packages/toolkit/src/view/pipeline/view-pipeline/Readme.tsx, packages/toolkit/src/view/pipeline/view-pipeline/ViewPipeline.tsx
Because
- replace pipeline readme with pipeline description on /pipelines/pid page
This commit
- replace pipeline readme with pipeline description on /pipelines/pid page
=> chore: replace pipeline readme with pipeline description on /pipelines/pid page

.github/workflows/integration-test.yml
Because
- we've retired the connector-backend
This commit
- remove outdated connector-backend test
=> ci(integration-test): remove outdated connector-backend test

packages/toolkit/src/view/pipeline/view-pipeline/InOutPut.tsx
Because
- fix run button on /pipelines/pid page not correctly align
This commit
- fix run button on /pipelines/pid page not correctly align
=> fix: fix run button on /pipelines/pid page not correctly align

apps/console/src/components/README.md
Because
- Found typos in the README.
This commit
- Fix those typos.
=> chore: fix typos in `components/README.md`

apps/console/src/pages/404.tsx
Because
- `PageBase` is not used.
This commit
- Remove the usage of `PageBase` in `404.tsx`
=> chore: unused import `PageBase`

packages/toolkit/src/lib/toastInstillError.ts
Because
- We have ts with strict mode on (`strict: true`), which enables [useUnknownInCatchVariables](https://www.typescriptlang.org/tsconfig#useUnknownInCatchVariables).`useUnknownInCatchVariables` makes `error`'s default type = `unknown`. Therefore, we do not need to allow `toastInstillError` accept `any` so it will be (mis)-used in somewhere else then the `catch` block.
This commit
- Change `error:any` to `error:unkown`, narrow the type to prevent misuse. Also remove `/* eslint-disable-next-line @typescript-eslint/no-explicit-any */`
=> chore: remove unnecessary `error:any`, narrow to `unknown`

packages/toolkit/src/components/UserProfileCard.tsx
Because
-  fix wrongly display organization link when user doesnt belong to any org
This commit
-  fix wrongly display organization link when user doesnt belong to any org
=> fix: fix wrongly display organization link when user doesnt belong to any org

packages/toolkit/src/view/pipeline-builder/components/dialogs/share-pipeline-dialog/TabShare.tsx
Because
- fix pipeline-builder share tab not correctly display owner profile avatar
This commit
- fix pipeline-builder share tab not correctly display owner profile avatar
=> fix(pipeline-builder): fix pipeline-builder share tab not correctly display owner profile avatar

packages/toolkit/src/view/pipeline-builder/Flow.tsx, packages/toolkit/src/view/pipeline-builder/components/ReadOnlyPipelineBuilder.tsx
Because
- user can now use the pipeline-builder control on preview
This commit
- user can now use the pipeline-builder control on preview
=> feat(pipeline-builder): user can now use the pipeline-builder control on preview

packages/toolkit/src/view/pipeline-builder/lib/createInitialGraphData.tsx
Because
- fix pipeline-builder configuration transformation pollute to the react-query data. And this cause the pipeline can not be properly cloned
This commit
- fix pipeline-builder configuration transformation pollute to the react-query data
=> fix: fix pipeline-builder configuration transformation pollute to the react-query data

packages/toolkit/src/view/pipeline-builder/Flow.tsx
Because
- disabled delete nodes and edges by clicking backspace
This commit
- disabled delete nodes and edges by clicking backspace
=> fix(pipeline-builder): disabled delete nodes and edges by clicking backspace

apps/console/src/styles/global.css, packages/toolkit/package.json, packages/toolkit/src/view/pipeline-builder/Flow.tsx, packages/toolkit/src/view/pipeline/PipelineBuilderMainView.tsx
Because
- make right-panel float on top of canvas to have bigger working space
This commit
- make right-panel float on top of canvas to have bigger working space
=> feat(pipeline-builder): make right-panel float on top of canvas to have bigger working space

packages/toolkit/src/view/pipeline-builder/FlowControl.tsx, packages/toolkit/src/view/pipeline/view-pipeline/EditMetadataDialog.tsx, packages/toolkit/src/view/pipeline/view-pipeline/Readme.tsx
Because
- There are places where `Promise`(s) are not awaited. Probably not intended?
This commit
- Add missing `await`, so the message shown in the toasts is reflecting the correct state of the system.
You might want to add <https://typescript-eslint.io/rules/no-floating-promises/> to avoid this error in the future.
=> fix: `async` function(s) should be awaited

packages/toolkit/src/view/pipeline/view-pipeline/InOutPut.tsx
Because
- Unnecessary state `isTriggering` which overlapping `mutation.isLoading`.
This commit
- This PR replaces the manually tracked state with `mutation.isLoading` by `react-query`, see https://tanstack.com/query/v4/docs/react/guides/mutations
=> chore: use `mutation.isLoading` instead of tracking loading state manually

packages/toolkit/src/constant/errors.ts, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/AudiosField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/FilesField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/ImageField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/ImagesField.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/end-operator-node/EndOperatorNode.tsx
Because
- We need to have different component output field style between demo pages like /pipeline/pid and the builder page
This commit
- fix output fields not correctly style on /pipelines/pid page
=> fix: fix output fields not correctly style on /pipelines/pid page

packages/toolkit/src/components/ClonePipelineDialog.tsx, packages/toolkit/src/view/pipeline-builder/lib/getRawPipelineRecipeFromPipelineRecipe.ts
Because
- We don't want users to be able to clone others connectors
This commit
- support blocking user from cloning others connectors
=> feat: support blocking user from cloning others connectors

packages/toolkit/src/view/profile/user-profile/UserProfile.tsx
Because
- fix user profile wrongly use org_name as user_name
This commit
- fix user profile wrongly use org_name as user_name
=> fix: fix user profile wrongly use org_name as user_name

packages/toolkit/src/view/pipeline-builder/lib/composeEdgesFromReferences.tsx
Because
- fix pipeline builder not correctly handle deep nested object referenced link
This commit
- fix pipeline builder not correctly handle deep nested object referenced link
=> fix(pipeline-builder): fix pipeline builder not correctly handle deep nested object referenced link

packages/toolkit/src/components/ClonePipelineDialog.tsx, packages/toolkit/src/view/pipeline/view-pipelines/CreatePipelineDialog.tsx
Because
- fix wrongly wrapped line of namespace in create and clone pipeline dialog
This commit
- fix wrongly wrapped line of namespace in create and clone pipeline dialog
=> fix: fix wrongly wrapped line of namespace in create and clone pipeline dialog

packages/toolkit/src/view/settings/api-tokens/APITokenTable.tsx
Because
- remove the expire data in the API token table
This commit
- remove the expire data in the API token table
=> chore: remove the expire data in the API token table

packages/toolkit/src/components/GeneralDeleteResourceDialog.tsx, packages/toolkit/src/components/card-pipeline/Menu.tsx, packages/toolkit/src/components/index.ts, packages/toolkit/src/lib/index.ts, packages/toolkit/src/lib/use-callback-ref/index.ts, packages/toolkit/src/lib/use-callback-ref/useCallbackRef.tsx, packages/toolkit/src/lib/use-controllable-state/index.ts, packages/toolkit/src/lib/use-controllable-state/useControllableState.tsx, packages/toolkit/src/view/resource/ResourcesTable.tsx
Because
- We wrongly use the [isOpen, setIsOpen] state outside of the component working area and cause all the delete dialog in the resource table to share a single isOpen state instance. So every time users click delete on a specific resource, they are opening the dialog that belong to the last item on the table
This commit
- fix the wrong state in ResourceTable causes the wrong behavior of the delete resource dialog
=> fix: fix the wrong state in ResourceTable cause the wrong behavior of delete resource dialog

apps/console/src/styles/github-markdown.css, packages/toolkit/src/view/pipeline-builder/lib/recursive-helpers/recursiveRemoveUndefinedAndNullFromArray.test.ts
Because
- markdown editor of pipeline description can not show ol and ul
This commit
- fix markdown editor of pipeline description can not show ol and ul
=> fix: fix markdown editor of pipeline description can not show ol and ul

packages/toolkit/src/lib/toastInstillError.ts
Because
- increase the duration of error toast notification
This commit
- increase the duration of error toast notification
=> chore: increase the duration of error toast notification

packages/toolkit/src/view/pipeline-builder/Flow.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/operator-node/OperatorNode.tsx
Because
- operator component node icon path is not correct
This commit
- fix operator component node icon path is not correct
=> fix: fix operator component node icon path is not correct

packages/design-system/src/new-ui/Separator/Separator.stories.tsx, packages/toolkit/src/view/pipeline-builder/RightPanel.tsx
Because
- Component panel shows "configration" (typo)
This commit
- Fixes the typo
Found while polishing public pipelines:
=> fix: Typo in component configuration

packages/toolkit/src/view/pipeline/view-pipeline/InOutPut.tsx
Because
- fix empty input setup button is not working in /pipelines/pid page
This commit
- fix empty input setup button is not working in /pipelines/pid page
=> fix: fix empty input setup button is not working in /pipelines/pid page

apps/console/src/components/top-bar/Topbar.tsx, apps/console/src/components/top-bar/topBarData.tsx, apps/console/src/pages/_app.tsx, apps/console/src/pages/index.tsx, packages/toolkit/src/lib/amplitude/AmplitudeContext.ts, packages/toolkit/src/lib/react-query-service/index.ts
This commit
- Adds default options in `tanstack/react-query` config to prevent re-fetch on window focus. (I don't know if this is the required behavior for this app, but it's a good practice to have defaults and override it when required)
- Refactors Top Bar menu to use loop for menu items/links
=> chore: refactor top bar navigation to make it dry, add default query options for react-query

apps/console/src/pages/login.tsx, packages/toolkit/src/components/ReferenceHintTag.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output-reference-hints/GroupByFormatField.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output-reference-hints/ListField.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output-reference-hints/index.ts, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/FieldHead.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/UploadFileInput.tsx, packages/toolkit/src/lib/use-instill-form/pick/pickComponentsFromReferenceHints.tsx, packages/toolkit/src/lib/use-instill-form/useComponentOutputReferenceHintFields.tsx, packages/toolkit/src/view/pipeline-builder/components/ComponentOutputReferenceHints.tsx
Because
- support group by format for component output reference hints
This commit
- support group by format for component output reference hints
=> feat(pipeline-builder): support group by format for component output reference hints

packages/toolkit/src/view/pipeline-builder/lib/getConnectorInputOutputSchema.ts, packages/toolkit/src/view/pipeline-builder/lib/getOperatorInputOutputSchema.ts
Because
- Backend may change the task of connector. But the migration may not catch up so it will have deviation. For example, if the task is `TASK_NOT_FOUND`,  but the backend provided definition already remove this definition. Console will break. We need to support this kind of breaking change
This commit
- support the potential breaking changes of connector task
=> fix(pipeline-builder): support the potential breaking changes of connector task

apps/console/src/components/OnboardingForm.tsx, packages/toolkit/src/view/data/DataResourceForm.tsx, packages/toolkit/src/view/model/ChangeModelStateToggle.tsx, packages/toolkit/src/view/model/ConfigureModelForm.tsx, packages/toolkit/src/view/model/CreateModelForm.tsx, packages/toolkit/src/view/settings/api-tokens/CreateAPITokenDialog.tsx, packages/toolkit/src/view/settings/api-tokens/DeleteAPITokenDialog.tsx
Because
According to the open issue, the maintenance of the code is reduced when react query is using callbacks instead of async functions
This commit
- Fixes it by migrating all `.mutate` to `.mutateAsync` and does the necessary adaptations
- Also, whenever I had a chance to improve readability, I did. For example, a piece of code was being repeated 5 times, so I created a function for it
- I let just one `.mutate` as it doesnt have any callback
closes https://github.com/instill-ai/community/issues/455
=> refactor: deprecate the usage of some callbacks on ReactQuery mutation

packages/toolkit/src/lib/vdp-sdk/metric/pipeline/types.ts
Because
- Dashboard numbers don't add up
This commit
- updated pipeline chart `status` types
=> fix(dashboard): update pipeline chart status type

packages/toolkit/src/components/card-pipeline/Footer.tsx
Because
- As an non auth user, I should see `Log in to clone`, instead of `Build`
This commit
- fix pipeline card wrongly put build button for user without permission
=> fix: fix pipeline card wrongly put build button for user without permission

packages/toolkit/src/lib/dashboard/generateChartData.ts, packages/toolkit/src/lib/vdp-sdk/metric/pipeline/types.ts
Because
currently the triggered count was getting overwritten by next value.
```
yAxis[pipelineIndex]["data"][xAxisIndex] = pipeline.trigger_counts[bucketIndex];
```
This commit
it should be, if their is already a value, to the index, it should add up to the previous value
```
if (yAxis[pipelineIndex]["data"][xAxisIndex]) {
yAxis[pipelineIndex]["data"][xAxisIndex] += pipeline.trigger_counts[bucketIndex];
} else {
yAxis[pipelineIndex]["data"][xAxisIndex] += pipeline.trigger_counts[bucketIndex];
}
```
=> fix(dashboard): chart yAxis calculation

packages/toolkit/src/lib/use-instill-form/pick/pickComponentsFromReferenceHints.tsx, packages/toolkit/src/lib/use-instill-form/pick/pickRegularFieldsFromInstillFormTree.tsx, packages/toolkit/src/view/pipeline-builder/FlowControl.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/connector-node/ConnectorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/end-operator-node/UserDefinedFieldItem.tsx
Because
- We have a nested flow, 
- user select connector definition
- user select existing connector
- We didn't put in the updated connector definition
- close https://github.com/instill-ai/community/issues/549
This commit
- fix connector definition not correctly update after user picking up the existing connector
=> fix: fix connector definition not correctly update after user picking up the existing connector

packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/FieldHead.tsx, packages/toolkit/src/lib/use-instill-form/transform/transformInstillFormatToHumanReadableFormat.tsx
Because
- The delete and edit icon on start and end operator is inconsistent
- close https://github.com/instill-ai/community/issues/548
This commit
- unify the onEdit and onDelete item on both start and end operator
=> feat(pipeline-builder): unify the onEdit and onDelete item on both start and end operator

packages/toolkit/src/lib/use-instill-form/components/common/FieldDescriptionTooltip.tsx, packages/toolkit/src/lib/use-instill-form/components/common/index.ts, packages/toolkit/src/lib/use-instill-form/components/regular/BooleanField.tsx, packages/toolkit/src/lib/use-instill-form/components/regular/CredentialTextField.tsx, packages/toolkit/src/lib/use-instill-form/components/regular/OneOfConditionField.tsx, packages/toolkit/src/lib/use-instill-form/components/regular/SingleSelectField.tsx, packages/toolkit/src/lib/use-instill-form/components/regular/TextAreaField.tsx, packages/toolkit/src/lib/use-instill-form/components/regular/TextField.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/SmartHintInfoCard.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/TextArea.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/TextField.tsx
Because
- The fields of useInstillForm are using the same tooltip to show complicated description, there break-words rule is not correct
- close https://github.com/instill-ai/community/issues/533
This commit
- fix useInstillForm field's description tooltip break words issue
=> fix: fix useInstillForm field's description tooltip break words issue

packages/toolkit/src/lib/use-instill-form/components/smart-hint/SmartHintList.tsx
Because
- fix smart-hint list not align to left when the key is too long
This commit
- fix smart-hint list not align to left when the key is too long
=> fix(pipeline-builder): fix smart-hint list not align to left when the key is too long

packages/toolkit/src/view/pipeline-builder/Flow.tsx, packages/toolkit/src/view/pipeline-builder/FlowControl.tsx
Because
- fix newly added nodes is behind old nodes
This commit
- fix newly added nodes is behind old nodes
=> fix(pipeline-builder): fix newly added nodes is behind old nodes

packages/toolkit/src/components/breadcrumb-with-link/BreadcrumbWithLink.tsx
Because
- update `BreadcrumbWithLink`
This commit
- update `BreadcrumbWithLink`
=> chore: add the missing return button in the subscription form (They are already in the design handover)

packages/toolkit/package.json, packages/toolkit/src/components/card-pipeline/Head.tsx, packages/toolkit/src/lib/vdp-sdk/mgmt/types.ts, packages/toolkit/src/lib/vdp-sdk/organization/mutations.ts, packages/toolkit/src/lib/vdp-sdk/organization/types.ts, packages/toolkit/src/view/pipeline-builder/components/dialogs/share-pipeline-dialog/TabShare.tsx, packages/toolkit/src/view/pipeline/view-pipeline/Head.tsx, packages/toolkit/src/view/profile/user-profile-view/Bio.tsx, packages/toolkit/src/view/profile/user-profile-view/UserProfileView.tsx, packages/toolkit/src/view/settings/user/UserProfileTab.tsx
Because
- fix the wrong organization profile object
This commit
- fix the wrong organization profile object
=> fix: fix the wrong organization profile object

packages/toolkit/src/lib/use-instill-form/transform/transformInstillJSONSchemaToZod.ts
Because
- console wrongly warn field not supporting multiple references (We don't support this before, but since we change our reference syntax and support auto converting the reference to target type right now, so we support multiple references out of the box)
This commit
- fix console wrongly warn field not supporting multiple references
=> fix: fix console wrongly warn field not supporting multiple references

packages/toolkit/src/lib/use-instill-form/components/smart-hint/TextArea.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/TextField.tsx, packages/toolkit/src/lib/use-instill-form/pick/pickRegularFieldsFromInstillFormTree.tsx, packages/toolkit/src/lib/use-smart-hint/pickSmartHintsFromAcceptFormats.test.ts, packages/toolkit/src/lib/use-smart-hint/pickSmartHintsFromAcceptFormats.ts
Because
- support hinting other types that can be stringified
```
// These are the value that can be stringified
// bool
// number
// integer
// string
// object
// semi-structured/*
// structured/*
// These are the value that can't be stringified
// image/*
// audio/*
// video/*
```
This commit
- support hinting other types that can be stringified
=> feat(pipeline-builder): support hinting other type that can be stringified

packages/toolkit/src/lib/useEntity.ts
Because
- We should return user to 404 when checkNamespace endpoint return `NAMESPACE_RESERVED` and `NAMESPACE_AVAILABLE` This means they are not exist in our db
This commit
-  fix not correctly redirect user to 404 page when the entity is not found
=> fix: fix not correctly redirect user to 404 page when the entity is not found

packages/design-system/package.json, packages/design-system/src/new-ui/Color/Color.stories.tsx, packages/design-system/src/new-ui/Color/Color.tsx, packages/design-system/src/new-ui/Color/index.ts, packages/design-system/src/new-ui/index.ts
Because
- add design-token color class to design-token
This commit
- add design-token color class to design-token
=> chore(design-system): add storybook stories for colors

packages/toolkit/src/lib/use-instill-form/transform/transformInstillJSONSchemaToZod.test.ts, packages/toolkit/src/view/pipeline/view-pipelines/CreatePipelineDialog.tsx
Because
- fix create pipeline dialog use the wrong entity as query param
This commit
- fix create pipeline dialog use the wrong entity as query param
=> fix: fix create pipeline dialog use the wrong entity as query param

packages/toolkit/src/lib/react-query-service/organization/useDeleteOrganization.ts, packages/toolkit/src/lib/vdp-sdk/organization/mutations.ts
Because
- The delete organization function parameter naming is wronf
This commit
- fix the wrong delete organization function parameter
=> fix: fix the wrong delete organization function parameter

packages/toolkit/package.json, packages/toolkit/src/components/UploadAvatarFieldWithCrop.tsx, packages/toolkit/src/components/index.ts, packages/toolkit/src/view/settings/user/UserProfileTab.tsx
Because
- We will use UploadAvatarFieldWithCrop for user/organization avatar uploader, this component need to be unified
This commit
- componentize the UploadAvatarFieldWithCrop
=> feat: componentize the UploadAvatarFieldWithCrop

packages/toolkit/src/lib/use-instill-form/pick/pickStartOperatorFreeFormFields.tsx, packages/toolkit/src/lib/use-instill-form/transform/transformStartOperatorMetadataToZod.ts, packages/toolkit/src/lib/use-smart-hint/pickSmartHintsFromAcceptFormats.ts, packages/toolkit/src/lib/vdp-sdk/pipeline/types.ts, packages/toolkit/src/view/pipeline-builder/components/nodes/start-operator-node/StartNodeInputType.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/start-operator-node/StartOperatorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/start-operator-node/StartOperatorNodeFreeForm.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/start-operator-node/pickSelectedTypeFromInstillFormat.ts, packages/toolkit/src/view/pipeline/view-pipeline/InOutPut.tsx
Because
- We need to replace semi-structured/object with semi-structured/json on start operator to better support backend
This commit
- replace semi-structured/object with semi-structured/json on start operator
=> feat(pipeline-builder): replace semi-structured/object with semi-structured/json on start operator

packages/toolkit/src/components/ReferenceHintTag.tsx, packages/toolkit/src/view/pipeline-builder/components/ComponentOutputReferenceHints.tsx
Because
- fix the reference header title have tooltip and is able to copy
This commit
- fix the reference header title have tooltip and is able to copy
=> fix(pipeline-builder): fix the reference header title have tooltip and is able to copy

packages/toolkit/src/components/ReferenceHintDataTypeTag.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output-reference-hints/GroupByFormatField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/FieldHead.tsx
Because
Something like `video/*` is not readable. We need to change it to `video`
This commit
- fix reference data type tags are not human readable issue
=> fix: fix reference data type tags are not human readable issue

packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/VideosField.tsx
Because
- typo
This commit
- fix the button title for multiple videos uploader at start operator
=> fix: fix the button title for multiple videos uploader at start operator

packages/toolkit/src/lib/vdp-sdk/pipeline/types.ts, packages/toolkit/src/view/pipeline-builder/components/nodes/start-operator-node/StartNodeInputType.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/start-operator-node/StartOperatorNode.tsx
Because
When using semi-structured/json, the type in the metadata of start operator need to be removed.
```
{
"type": "object",
"instillFormat": "semi-structured/json",
"title": "www"
}
```
to
```
{
"instillFormat": "semi-structured/json",
"title": "www"
} 
```
This commit
- fix semi-structured/json at start operator not obey the protocol
=> fix(pipeline-builder): fix semi-structured/json at start operator not obey the protocol

packages/toolkit/package.json, packages/toolkit/src/view/pipeline-builder/components/nodes/end-operator-node/EndOperatorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/start-operator-node/StartOperatorNode.tsx
Because
- relates issue https://github.com/instill-ai/community/issues/559
This commit
- prevent user create duplicated field on start and end operator
=> fix(pipeline-builder): prevent user create duplicated field on start and end operator

packages/toolkit/package.json, packages/toolkit/src/lib/vdp-sdk/types.ts
Because
- Backend provide stripe.trial_end field
This commit
- add trial_end field into StripeSubscriptionDetail
=> feat: add trial_end field into StripeSubscriptionDetail

packages/toolkit/package.json, packages/toolkit/src/lib/vdp-sdk/mgmt/types.ts, packages/toolkit/src/lib/vdp-sdk/organization/types.ts
Because
- stripe subscription detail should be nullable
This commit
- fix stripe subscription detail is not nullable issue
=> fix: fix stripe subscription detail is not nullable issue

packages/toolkit/package.json, packages/toolkit/src/components/ReferenceHintTag.tsx
Because
- copy & paste full reference with ${} instead of path only
This commit
- copy & paste full reference with ${} instead of path only
=> feat(pipeline-builder): copy & paste full reference with ${} instead of path only

apps/console/public/icons/pinecone.svg
Because
- fix pinecone svg padding is too small issue
This commit
- fix pinecone svg padding is too small issue
=> fix: fix pinecone svg padding is too small issue

packages/toolkit/src/view/dashboard/PipelineTriggerCountsLineChart.tsx
Because
- no pipeline message text center 
This commit
- no pipeline message text center
=> chore(dashbaord): no pipeline message text center 

packages/toolkit/src/components/UserProfileCard.tsx
Because
- fix user profile card bio not left-align
This commit
- fix user profile card bio not left-align
=> fix: fix user profile card bio not left-align

packages/toolkit/src/lib/use-smart-hint/pickSmartHintsFromAcceptFormats.test.ts, packages/toolkit/src/lib/use-smart-hint/pickSmartHintsFromAcceptFormats.ts, packages/toolkit/src/lib/use-smart-hint/useSmartHint.ts
Because
- There are multiple scenario smart hint doesn't correctly filter hints
- The hints will duplicated 
- It can not correctly filter array types
- The logic is messy
- The unit tests are not complete
This commit
- Fix above filter issue
- Add more unit tests to guard this feature
=> fix: fix smart hint didn't correctly filter hints

packages/toolkit/src/lib/use-instill-form/components/component-output/MDTextViewer.tsx, packages/toolkit/src/lib/use-instill-form/components/regular/CredentialTextField.tsx, packages/toolkit/src/lib/use-instill-form/components/regular/TextAreaField.tsx, packages/toolkit/src/lib/use-instill-form/components/regular/TextField.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/TextArea.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/TextField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/LongTextField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/NumberField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/NumbersField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/ObjectField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/TextField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/TextareaField.tsx, packages/toolkit/src/lib/use-instill-form/components/start-operator-free-form-fields/TextsField.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/common/NodeSortableFieldWrapper.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/end-operator-node/UserDefinedFieldItem.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/start-operator-node/StartOperatorNode.tsx
Because
- User can not wheel scroll up and down on the TextArea input in the pipeline-builder right now
This commit
- fix user can not wheel scroll up and down on TextArea
=> fix: fix user can not wheel scroll up and down on TextArea

packages/toolkit/src/lib/use-instill-form/components/smart-hint/onInputKeydown.tsx
Because
- User can not press enter and add an new line on TextArea field in pipeline-builder
This commit
- fix can not keydown enter on the TextArea field in pipeline builder
=> fix: fix can not keydown enter on the TextArea field in pipeline builder

packages/toolkit/src/components/card-pipeline/Head.tsx, packages/toolkit/src/lib/vdp-sdk/connector/types.ts, packages/toolkit/src/lib/vdp-sdk/pipeline/types.ts, packages/toolkit/src/lib/vdp-sdk/types.ts, packages/toolkit/src/view/pipeline-builder/components/dialogs/share-pipeline-dialog/TabShare.tsx
Because
- The old owner field is a struct, which is not type-safe. In this sprint, backend adapt new protobuf to make this field has more type safety
This commit
- adapt new pipeline.owner and connector.owner data format
=> chore: adapt new pipeline.owner and connector.owner data format

.github/workflows/integration-test.yml
Because
- `Ray` image tag has a format change
This commit
- update `Ray` image tag variable
=> ci(workflows): update model ray image tag

packages/toolkit/src/lib/use-smart-hint/useSmartHint.ts
Because
- When display the `component.output`, we display its type as null. Which is not correct, it should be `semi-structured/json`
This commit
- fix component output hint type is not correct
=> fix(pipeline-builder): fix component output hint's type is not correct

packages/toolkit/src/view/pipeline-builder/components/iterator-editor/iterator-output/IteratorOutput.tsx, packages/toolkit/src/view/pipeline-builder/components/iterator-editor/iterator-output/OutputValueSelect.tsx, packages/toolkit/src/view/pipeline-builder/lib/hooks/useConstructNodeFromDefinition.tsx
Because
- In the previous implementation, user can only select array type in the iterator's output_element, this is not correct. User can select any data to put into output_element
This commit
- fix iterator not correctly hint the output user can select
=> fix: fix iterator not correctly hint the output user can select

packages/toolkit/src/lib/use-smart-hint/pickSmartHintsFromNodes.ts
Because
- Previously we iterator's element in the iterator's component just by referenced it as `element`. But for backend protocol, it should be `iterator_id.element`
This commit
- fix how we hint the iterator element
=> fix: fix how we hint the iterator element

packages/toolkit/src/view/pipeline-builder/components/iterator-editor/iterator-input/IteratorInput.tsx
Because
- iterator's input can also accept semi-structured/* type
This commit
- hint semi-structured as input on iterator
=> fix: hint semi-structured as input on iterator

packages/toolkit/src/lib/use-instill-form/components/component-output/TextsField.tsx, packages/toolkit/src/lib/use-instill-form/pick/pickComponentOutputFieldsFromInstillFormTree.tsx, packages/toolkit/src/lib/use-instill-form/useComponentOutputFields.tsx
Because
- fix render bug caused by mis-align of smart hint and output rendering
This commit
- fix render bug caused by mis-align of smart hint and output rendering
=> fix(pipeline-builder): fix render bug caused by mis-align of smart hint and output rendering

packages/toolkit/src/lib/use-smart-hint/output-reference-hint/pickOutputReferenceHintsFromComponent.tsx, packages/toolkit/src/lib/vdp-sdk/pipeline/types.ts, packages/toolkit/src/lib/vdp-sdk/types.ts, packages/toolkit/src/view/pipeline-builder/PipelineBuilderMainView.tsx, packages/toolkit/src/view/pipeline-builder/lib/composeEdgesFromComponents.ts, packages/toolkit/src/view/pipeline-builder/lib/getConnectorInputOutputSchema.ts, packages/toolkit/src/view/pipeline-builder/lib/getOperatorInputOutputSchema.ts, packages/toolkit/src/view/pipeline/view-pipeline/InOutPut.tsx
Because
- adapt backend return data_specification can be null
This commit
- adapt backend return data_specification can be null
=> fix(pipeline-builder): adapt backend return data_specification can be null

packages/toolkit/src/view/pipeline-builder/components/nodes/common/NodeWrapper.tsx
Because
- The node's handlers are missing under ReadOnlyPipelineBuilder
This commit
- fix not correctly generate node handler on ReadOnlyPipelineBuilder
=> fix(pipeline-builder): fix not correctly generate node handler on ReadOnlyPipelineBuilder

.github/workflows/integration-test.yml
Because
- There are old workflow from old VDP repo being triggered. We should trigger the new workflow instead
This commit
- fix workflow that trigger e2e in instill-core
=> fix(ci): fix workflow that trigger e2e in instill-core

.github/workflows/integration-test.yml, docs/test-coverage-list.md, packages/toolkit/src/view/pipeline-builder/lib/composeEdgesFromComponents.test.ts, packages/toolkit/src/view/pipeline-builder/lib/composeEdgesFromComponents.ts, packages/toolkit/src/view/pipeline-builder/lib/getReferencesFromString.test.ts, packages/toolkit/src/view/pipeline-builder/lib/getReferencesFromString.ts
Because
- We are going to support connecting references like `start["texts"]`, `st_0.output["foo"]`
This commit
- support connecting edges for reference with square brace
=> feat(pipeline-builder): support connecting edges for reference with square brace

packages/toolkit/src/view/pipeline-builder/PipelineBuilderMainView.tsx
Because
- fix unsaved guard of pipeline-builder didnt navigate user to the page they want to go
This commit
- fix unsaved guard of pipeline-builder didnt navigate user to the page they want to go
=> fix: fix unsaved guard of pipeline-builder didnt navigate user to the page they want to go

apps/console/integration-test/helpers/actions/pipeline.ts, apps/console/integration-test/main.test.ts, apps/console/integration-test/tests/should-edit-create-start-end-field.test.ts, apps/console/src/app/layout.tsx, packages/toolkit/src/view/pipeline-builder/components/ComponentOutputs.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/end-operator-node/EndOperatorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/end-operator-node/EndOperatorNodeFreeForm.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/start-operator-node/StartOperatorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/start-operator-node/StartOperatorNodeFreeForm.tsx
Because
- stop automatically generating key when editing start/end field
This commit
- stop automatically generating key when editing start/end field
=> feat(pipeline-builder QoL): stop automatically generating key when editing start/end field

packages/toolkit/src/components/card-pipeline/Footer.tsx, packages/toolkit/src/view/pipeline/view-pipeline/Head.tsx, packages/toolkit/src/view/pipeline/view-pipeline/RunButton.tsx
Because
- Run button on pipeline overview page is not correctly displayed when user is not logged in
This commit
- fix the missing/wrong run button when user is not logged in on pipeline overview page
=> fix(pipeline-builder): fix the missing/wrong run button when user is not logged in on pipeline overview page

packages/toolkit/src/lib/use-instill-form/components/component-output/MDTextViewer.tsx
Because
- Formatted output will overflow when there has paragraph, code and anchor
This commit
- fix incorrect overflow issue in formatter output
=> fix(pipeline-builder): fix incorrect overflow issue in formatter output

packages/toolkit/src/view/pipeline/view-pipelines/CreatePipelineDialog.tsx, packages/toolkit/src/view/pipeline/view-pipelines/ViewPipelines.tsx
Because
- This is a pre-caution, for example in helm environment, every request is slow so the entity may be missing, this will cause the test to fall
This commit
- fix not correctly block create pipeline action when entity is missing
=> fix: fix not correctly block create pipeline action when entity is missing

packages/toolkit/src/view/pipeline-builder/components/nodes/start-operator-node/StartOperatorNode.tsx
Because
- the user create a long_text start operator field, when they edit it, the initialization of the type is text, which is not correct
This commit
- fix the wrong initialization of start operator type select
=> fix: fix the wrong initialization of start operator type select

packages/toolkit/src/view/pipeline-builder/components/ReadOnlyPipelineBuilder.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/common/NodeDropdownMenu.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/control-panel/ConnectorOperatorControlPanel.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/control-panel/ControlPanel.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/control-panel/StartEndOperatorControlPanel.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/end-operator-node/EndOperatorNode.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/iterator-node/IteratorNode.tsx, packages/toolkit/src/view/pipeline-builder/lib/createGraphLayout.tsx
Because
- make the pipeline overview cleaner by collapse and auto-arrange nodes
This commit
- make the pipeline overview cleaner by collapse and auto-arrange nodes
=> feat: make the pipeline overview cleaner by collapsing and auto-arranging nodes

packages/toolkit/src/lib/react-query-service/pipeline/use-user-pipelines/client.ts, packages/toolkit/src/lib/react-query-service/pipeline/use-user-pipelines/server.ts, packages/toolkit/src/lib/vdp-sdk/pipeline/queries.ts, packages/toolkit/src/view/hub/hub-view/Body.tsx, packages/toolkit/src/view/pipeline/view-pipelines/ViewPipelines.tsx
Because
- Try to reduce the response payload to speed up request
This commit
- using none complete pipeline request to compose user active pipeline counts
=> feat: using none complete pipeline request to compose user active pipeline counts

packages/toolkit/package.json, packages/toolkit/src/view/pipeline-builder/components/PipelineBuilderCanvas.tsx, packages/toolkit/src/view/pipeline-builder/components/ReadOnlyPipelineBuilder.tsx
Because
- adapt figma-like zoom-in-out experience and enable multi-selection of nodes
This commit
- adapt figma-like zoom-in-out experience and enable multi-selection of nodes
=> feat(pipeline-builder): adapt figma-like zoom-in-out experience and enable multi-selection of nodes

packages/toolkit/src/view/pipeline-builder/PipelineBuilderMainView.tsx
Because
- fix save pipeline in the warn unsaved change dialog not clean up state, this cause the state "isEditingIterator" not correctly clean up
This commit
- fix save pipeline in the warn unsaved change dialog not clean up state
=>  fix(pipeline-builder): fix save pipeline in the warn unsaved change dialog not clean up state

packages/toolkit/package.json, packages/toolkit/src/view/pipeline/view-pipeline/Readme.tsx, packages/toolkit/src/view/pipeline/view-pipeline/ViewPipeline.tsx
Because
- fix owner and member can not edit their org's pipeline readme
This commit
- fix owner and member can not edit their org's pipeline readme
=> fix: fix owner and member can not edit their org's pipeline readme

packages/toolkit/src/view/pipeline-builder/lib/hooks/useUpdaterOnNode.tsx, packages/toolkit/src/view/pipeline-builder/lib/hooks/useUpdaterOnRightPanel.tsx
Because
- fix wrongly update the recipe when pipeline is readonly
This commit
- fix wrongly update the recipe when pipeline is readonly
=> fix(pipeline-builder): fix wrongly update the recipe when pipeline is readonly

packages/toolkit/src/view/pipeline-builder/components/PipelineBuilderCanvas.tsx, packages/toolkit/src/view/pipeline-builder/components/ReadOnlyPipelineBuilder.tsx, packages/toolkit/src/view/pipeline-builder/components/canvasPanOnDrag.ts
Because
- User should be able to hold and drag the canvas with mouse click
This commit
- fix read-only canvas pan on drag issue
=> fix(pipeline-builder): fix read-only canvas pan on drag issue

apps/console/src/app/(providers)/root-provider.tsx
Because
- Whenever user leave the pipelien-builder page we need to re-init the builder state
This commit
- fix wrongly initiate pipeline builder
=> fix: fix wrongly initiate pipeline builder

packages/toolkit/src/lib/vdp-sdk/pipeline/types.ts, packages/toolkit/src/view/pipeline-builder/lib/constructPipelineRecipeFromNodes.tsx
Because
- fix toolkit wrongly display null definition cause confusion
This commit
- fix toolkit wrongly display null definition cause confusion
=> fix(pipeline-builder): fix toolkit wrongly display null definition cause confusion

packages/toolkit/src/lib/use-instill-form/components/regular/BooleanField.tsx, packages/toolkit/src/lib/use-instill-form/components/regular/CredentialTextField.tsx, packages/toolkit/src/lib/use-instill-form/components/regular/OneOfConditionField.tsx, packages/toolkit/src/lib/use-instill-form/components/regular/SingleSelectField.tsx, packages/toolkit/src/lib/use-instill-form/components/regular/TextAreaField.tsx, packages/toolkit/src/lib/use-instill-form/components/regular/TextField.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/TextArea.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/TextField.tsx, packages/toolkit/src/lib/use-instill-form/components/trigger-request-form-fields/AudioField.tsx, packages/toolkit/src/lib/use-instill-form/components/trigger-request-form-fields/AudiosField.tsx, packages/toolkit/src/lib/use-instill-form/components/trigger-request-form-fields/BooleanField.tsx, packages/toolkit/src/lib/use-instill-form/components/trigger-request-form-fields/FileField.tsx, packages/toolkit/src/lib/use-instill-form/components/trigger-request-form-fields/FilesField.tsx, packages/toolkit/src/lib/use-instill-form/components/trigger-request-form-fields/ImageField.tsx, packages/toolkit/src/lib/use-instill-form/components/trigger-request-form-fields/ImagesField.tsx, packages/toolkit/src/lib/use-instill-form/components/trigger-request-form-fields/LongTextField.tsx, packages/toolkit/src/lib/use-instill-form/components/trigger-request-form-fields/NumberField.tsx, packages/toolkit/src/lib/use-instill-form/components/trigger-request-form-fields/NumbersField.tsx, packages/toolkit/src/lib/use-instill-form/components/trigger-request-form-fields/ObjectField.tsx, packages/toolkit/src/lib/use-instill-form/components/trigger-request-form-fields/TextField.tsx, packages/toolkit/src/lib/use-instill-form/components/trigger-request-form-fields/TextareaField.tsx, packages/toolkit/src/lib/use-instill-form/components/trigger-request-form-fields/TextsField.tsx, packages/toolkit/src/lib/use-instill-form/components/trigger-request-form-fields/VideoField.tsx, packages/toolkit/src/lib/use-instill-form/components/trigger-request-form-fields/VideosField.tsx
Because
- make description on node selectable. In this way, user can better copy description as they wish
This commit
- make description on node selectable
=> feat(pipeline-builder): make description on node selectable

packages/toolkit/src/view/pipeline-builder/components/PipelineBuilderCanvas.tsx, packages/toolkit/src/view/pipeline-builder/lib/hooks/useUpdaterOnNode.tsx, packages/toolkit/src/view/pipeline-builder/lib/hooks/useUpdaterOnRightPanel.tsx
Because
- fix wrongly roll back position when update node config
This commit
- fix wrongly roll back position when update node config
=> fix(pipeline-builder): fix wrongly roll back position when update node config

packages/toolkit/src/view/pipeline/view-pipeline/Head.tsx
Because
- Login user can clone the pipeline no matter he is the owner or not
This commit
- Login user can clone the pipeline no matter he is the owner or not
=> fix: pipeline view head section clone button permission

apps/console/src/app/render.tsx, packages/toolkit/src/lib/vdp-sdk/connector/queries.ts, packages/toolkit/src/lib/vdp-sdk/helper/createInstillAxiosClient.ts, packages/toolkit/src/lib/vdp-sdk/metric/pipeline/queries.ts, packages/toolkit/src/lib/vdp-sdk/mgmt/actions.ts, packages/toolkit/src/lib/vdp-sdk/mgmt/mutations.ts, packages/toolkit/src/lib/vdp-sdk/mgmt/queries.ts, packages/toolkit/src/lib/vdp-sdk/model/actions.ts, packages/toolkit/src/lib/vdp-sdk/model/mutations.ts, packages/toolkit/src/lib/vdp-sdk/model/queries.ts, packages/toolkit/src/lib/vdp-sdk/operation/queries.ts, packages/toolkit/src/lib/vdp-sdk/organization/mutations.ts, packages/toolkit/src/lib/vdp-sdk/organization/queries.ts, packages/toolkit/src/lib/vdp-sdk/pipeline/actions.ts, packages/toolkit/src/lib/vdp-sdk/pipeline/mutations.ts, packages/toolkit/src/lib/vdp-sdk/pipeline/queries.ts
Because
- Previously we have prefix in our API path like `/vdp/v1beta...`, now we are planning to retire this kind of structure
This commit
- adapt the retirement of api prefix
=> feat: adapt the retirement of api prefix

packages/toolkit/src/view/pipeline-builder/components/nodes/connector-node/ConnectorNode.tsx
Because
- stop user from opening more options when requirement not met
This commit
- stop user from opening more options when requirement not met
=> fix(pipeline-builder): stop user from opening more options when requirement not met

packages/design-system/src/new-ui/Select/Select.stories.tsx, packages/design-system/src/new-ui/Select/Select.tsx, packages/toolkit/src/components/ClonePipelineDialog.tsx, packages/toolkit/src/lib/use-instill-form/components/regular/OneOfConditionField.tsx, packages/toolkit/src/lib/use-instill-form/components/regular/SingleSelectField.tsx, packages/toolkit/src/view/airbyte/OneOfConditionSection.tsx, packages/toolkit/src/view/airbyte/useBuildAirbyteFields.tsx, packages/toolkit/src/view/pipeline-builder/components/iterator-editor/iterator-input/IteratorInput.tsx, packages/toolkit/src/view/pipeline-builder/components/iterator-editor/iterator-output/OutputValueSelect.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/trigger-node/TriggerNodeTypeSelect.tsx, packages/toolkit/src/view/pipeline/view-pipelines/CreatePipelineDialog.tsx, packages/toolkit/src/view/pipeline/view-pipelines/ViewPipelines.tsx
Because
To properly support the complex pattern mentioned in [Radix-UI](https://www.radix-ui.com/primitives/docs/components/select#with-complex-items)
We will have two patterns in our Select component
- Using label props -> This will have default Select.ItemText component inside the default Select.Item
- Using children -> You need to manually wrap the whole select component into Select.ItemText
```typescript
<Select.ItemText>
Adolfo Hess
</Select.ItemText>
```
This commit
- improve Select component to let it cover more use cases
=> feat(design-system): improve Select component to let it cover more use cases

packages/toolkit/src/view/pipeline-builder/components/dialogs/select-component-dialog/SelectComponentDialog.tsx
Because
- Typo
This commit
- Fix typo
=> fix(pipeline-builder): "connectors" to "components" typo 

packages/design-system/package.json, pnpm-lock.yaml
Because
- dependabot alerts
- https://github.com/instill-ai/instill.tech/security/dependabot/36
- https://github.com/instill-ai/instill.tech/security/dependabot/41
This commit
- dependabot alerts
=> fix: dependabot alerts

.github/workflows/images.yml, .github/workflows/nextjs-bundle-analysis.yml, .github/workflows/release.yml, .github/workflows/unit-test.yml, Dockerfile, Dockerfile.playwright, apps/console/package.json, packages/design-system/package.json
Because
- Console now demand to use node 20, this PR updates the relative configuration in the GitHub CI and the docker
This commit
- fix ci and docker node version
=> fix: fix ci and docker node version to adapt node20

packages/toolkit/src/lib/use-instill-form/components/regular/SingleSelectField.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/TextArea.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/TextField.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/onInputChange.tsx, packages/toolkit/src/lib/use-instill-form/pick/pickRegularFieldsFromInstillFormTree.tsx, packages/toolkit/src/lib/use-instill-form/useInstillForm.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/common/node-bottom-bar/NodeBottomBarMenu.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/connector-node/ConnectorNode.tsx
Because
- We want to make sure the user understand when and how they are using Instill Credit, so we dynamically generate field description for field that support Instill Credit
- We hint connector is using Instill Credit
This commit
- dynamic switch smart-hint description for instill credit, and hint connector is using Instill Credit
=> feat(pipeline-builder): dynamic switch smart-hint description for instill credit, and hint connector is using Instill Credit

packages/toolkit/src/lib/use-instill-form/components/smart-hint/TextArea.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/TextField.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/onInputKeydown.tsx
Because
- Previously user can not press enter in TextArea and if we wrongly preventDefault, the enter in TextField will cause page refresh
This commit
- better handle the enter experience in smart hint field
=> fix(pipeline-builder): better handle the enter experience in smart hint field

apps/console/integration-test/tests/should-change-component-id.test.ts, packages/toolkit/package.json, packages/toolkit/src/components/top-bar/RemainingCredit.tsx, packages/toolkit/src/lib/use-instill-form/components/regular/SingleSelectField.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/TextArea.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/TextField.tsx, packages/toolkit/src/lib/use-instill-form/pick/pickRegularFieldsFromInstillFormTree.tsx, packages/toolkit/src/view/pipeline-builder/components/RemainingCreditCTA.tsx
Because
- When we first render the component, especially when user select text-generation, we should by default add instill-credit into api_key field
This commit
- fix initial instill credit hint issue and remaining credit text
=> fix: fix initial instill credit hint issue and remaining credit text

packages/toolkit/package.json, packages/toolkit/src/view/pipeline-builder/components/nodes/control-panel/ConnectorOperatorControlPanel.tsx
Because
- fix a bug when user duplicate component, the configuration will be wrongly synced
This commit
- fix a bug when user duplicate component, the configuration will be wrongly synced
=> fix(pipeline-builder): fix a bug when user duplicate component, the configuration will be wrongly synced

packages/toolkit/package.json, packages/toolkit/src/lib/use-instill-form/components/regular/SingleSelectField.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/onInputChange.tsx
Because
- fix when select a model not support instill credit the api_key keep flushed away
This commit
- fix when select a model not support instill credit the api_key keep flushed away
=> fix(pipeline-builder): fix when select a model not support instill credit the api_key keep flushed away

packages/toolkit/src/lib/use-instill-form/components/smart-hint/SmartHintList.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/TextArea.tsx, packages/toolkit/src/lib/use-instill-form/components/smart-hint/TextField.tsx, packages/toolkit/src/view/pipeline-builder/components/nodes/common/node-bottom-bar/NodeBottomBarMenu.tsx
Because
- fix typo in the instill credit hint
This commit
- fix typo in the instill credit hint
=> fix: fix typo in the instill credit hint

packages/toolkit/src/view/settings/secrets/DeleteSecretDialog.tsx
Because
- When typing during deleting secret, the modal UI disappears from time to time. - **Could not replicate** 
- Change "Please type users/user-id/secrets/secret-id" to "Please type secret-id to confirm."
This commit
- Change "Please type users/user-id/secrets/secret-id" to "Please type secret-id to confirm."
=> fix(delete_secret_modal): secret deletion glitch

packages/toolkit/src/view/pipeline-builder/Flow.tsx
Because
- fix credit not show up in pipeline-builder
This commit
- fix credit not show up in pipeline-builder
=> fix(instill-credit): fix credit not show up in pipeline-builder

packages/toolkit/src/lib/use-instill-form/components/common/FieldDescriptionTooltip.tsx, packages/toolkit/src/lib/use-instill-form/components/regular/ImageField.tsx, packages/toolkit/src/lib/use-instill-form/components/regular/index.ts, packages/toolkit/src/lib/use-instill-form/pick/pickRegularFieldsFromInstillFormTree.tsx
Because
- accept image field in the auto-gen-form
This commit
- accept image field in the auto-gen-form
=> feat(auto-gen-form): accept image field in the auto-gen-form

packages/toolkit/src/lib/react-query-service/pipeline/useInfinitePipelines.ts, packages/toolkit/src/view/hub/hub-view/Body.tsx
Because
- Remove name sort option
- Choosing Ascending sends Descending to the backend and vice versa. This is a workaround to be discussed
=> feat: remove name sorting option and fix asc/desc in sorting 

packages/toolkit/src/view/settings/api-tokens/CreateAPITokenDialog.tsx, packages/toolkit/src/view/settings/api-tokens/DeleteAPITokenDialog.tsx
Because
- fix missing notification title when delete api token
This commit
- fix missing notification title when delete api token
=> fix: fix missing notification title when delete api token

packages/toolkit/src/components/top-bar/CloudTopbarDropdown.tsx
Because
- fix wording of upgrade to starter plan button
This commit
- fix wording of upgrade to starter plan button
=> fix: fix wording of upgrade to starter plan button

packages/toolkit/src/view/pipeline-builder/components/triggerPipelineSnippets.ts
Because
- fix the outdated trigger api path in the builder's toolkit
This commit
- fix the outdated trigger api path in the builder's toolkit
=> fix(pipeline-builder): fix the outdated trigger api path in the builder's toolkit

packages/toolkit/src/view/model/CreateModelForm.tsx, packages/toolkit/src/view/model/view-model/ModelSettingsEditForm.tsx
Because
- the model create and edit forms had wrong input description font size
This commit
- fixes create and edit forms input description font size
=> fix(model-forms): fix model forms input descriptions font size

packages/toolkit/src/lib/react-query-service/model/useInfiniteModels.ts, packages/toolkit/src/lib/react-query-service/pipeline/useInfinitePipelines.ts, packages/toolkit/src/lib/vdp-sdk/model/queries.ts, packages/toolkit/src/lib/vdp-sdk/pipeline/queries.ts, packages/toolkit/src/view/hub/hub-view/Body.tsx
Because
- use non view_full query on hub to speed up request
This commit
- use non view_full query on hub to speed up request
=> fix: use non view_full query on hub to speed up request

packages/toolkit/src/view/hub/hub-view/Body.tsx
Because
- enable view-full of model request on hub since BE didn't support this option with returning full owner object
This commit
- enable view-full of model request on hub
=> fix: enable view-full of model request on hub

packages/toolkit/package.json, packages/toolkit/src/components/UserProfileCard.tsx
Because
- fix user profile card org navigation didnt change namespace anchor
This commit
- fix user profile card org navigation didnt change namespace anchor
=> fix(namespace-switch): fix user profile card org navigation didnt change namespace anchor

packages/design-system/package.json, packages/design-system/src/new-ui/Tag/Tag.tsx
Because
- fix Tag border style
This commit
- fix Tag border style
=> fix: fix Tag border style

packages/toolkit/src/view/pipeline-builder/lib/generateNewComponentIndex.test.ts
Because
- fix generateNewComponentIndex unit test
This commit
- fix generateNewComponentIndex unit test
=> fix: fix generateNewComponentIndex unit test

apps/console/src/app/(providers)/root-provider.tsx, packages/toolkit/src/constant/model.ts, packages/toolkit/src/lib/convertSentenceToCamelCase.ts, packages/toolkit/src/lib/index.ts, packages/toolkit/src/view/model/view-model/ModelOverview.tsx
Because
- The model page still had `snake_case` strings
This commit
- fix `snake_case` to `camelCase`
=> fix: some props of the model trigger payload had snake_case, fixed them to camelCase

packages/toolkit/src/view/model/view-model/ModelHead.tsx, packages/toolkit/src/view/pipeline/view-pipeline/Head.tsx
Because
- the styles of the tag were different
This commit
- unified the styles and updated the logic to show only "Private" tag
=> fix: fixed private tag in the pipeline/model header

packages/toolkit/package.json, packages/toolkit/src/lib/react-query-service/metric/useCreditConsumptionChartRecords.ts
Because
- fix credit consumption react-query key not included owner issue
This commit
- fix credit consumption react-query key not included owner issue
=> fix(dashbiard): fix credit consumption react-query key not included owner issue

packages/toolkit/src/view/model/view-model/ModelVersions.tsx
Because
- Previously we removed the digest column from the versions table for technical reasons. New those reasons are irrelevant, so we can add it back.
This commit
- Added back the Digest column. Updated the styles of the table to properly render long strings.
=> fix: add digest back to versions table

packages/design-system/src/new-ui/Breadcrumb/Breadcrumb.tsx, packages/design-system/src/ui/Buttons/CollapseSidebarButton/CollapseSidebarButton.tsx, packages/design-system/src/ui/Buttons/OutlineButton/OutlineButton.tsx, packages/design-system/src/ui/Buttons/SolidButton/SolidButton.tsx, packages/design-system/src/ui/Buttons/TextButton/TextButton.tsx, packages/design-system/src/ui/InputDescriptions/BasicInputDescription/BasicInputDescription.tsx, packages/design-system/src/ui/InputLabels/BasicInputLabel/BasicInputLabel.tsx, packages/design-system/src/ui/InputLabels/TextAreaInputLabel/TextAreaInputLabel.tsx, packages/design-system/src/ui/Progress/DarkBgSquareProgress/DarkBgSquareProgress.tsx, packages/design-system/src/ui/Progress/NoBgSquareProgress/NoBgSquareProgress.tsx, packages/design-system/src/ui/Progress/SquareProgressBase/SquareProgressBase.tsx, packages/design-system/src/ui/Progress/WhiteBgSquareProgress/WhiteBgSquareProgress.tsx, packages/design-system/src/ui/ProgressMessageBoxs/BasicProgressMessageBox/BasicProgressMessageBox.tsx, packages/design-system/src/ui/SingleSelects/BasicSingleSelect/BasicSingleSelect.tsx, packages/design-system/src/ui/TextAreas/BasicTextArea/BasicTextArea.tsx, packages/design-system/src/ui/TextFields/BasicTextField/BasicTextField.tsx, packages/design-system/src/ui/TextFields/ProtectedBasicTextField/ProtectedBasicTextField.tsx, packages/design-system/src/ui/ToggleFields/BasicToggleField/BasicToggleField.tsx, packages/design-system/src/ui/ToggleFields/StatefulToggleField/StatefulToggleField.tsx, packages/design-system/src/ui/UploadFileFields/BasicUploadFileField/BasicUploadFileField.tsx, tsconfig.base.json
Because
We are enforcing more strict Typescript rule to the codebase
```json
"noUnusedLocals": true,
"noUnusedParameters": true
```
This commit
- enforce more strict Typescript rule among codebase
=> chore: enforce more strict Typescript rule among codebase

apps/console/src/app/(providers)/amplitude-client-provider.tsx, packages/toolkit/src/view/pipeline/view-pipeline/PipelineSettings.tsx
Because
- we could save empty tags updating pipeline
This commit
- now empty tags are being filtered out
=> fix: remove empty tags on pipeline update

packages/toolkit/package.json, packages/toolkit/src/lib/use-instill-form/transform/transformInstillFormatToHumanReadableFormat.tsx, packages/toolkit/src/lib/use-smart-hint/pickSmartHintsFromNodes.ts, packages/toolkit/src/view/pipeline-builder/components/iterator-editor/IteratorEditor.tsx, packages/toolkit/src/view/pipeline-builder/components/iterator-editor/iterator-input/IterateElementHint.tsx, packages/toolkit/src/view/pipeline-builder/components/iterator-editor/iterator-input/IteratorInput.tsx, packages/toolkit/src/view/pipeline-builder/components/iterator-editor/iterator-output/OutputValueSelect.tsx
Because
- Iterator should be able to consume objectArray as input
This commit
- fix iterator not correct take in objectArray and use it as a hint in iterator editor
=> fix(pipeline-editor): fix iterator not correct take in objectArray and use it as a hint in iterator editor

packages/toolkit/src/view/pipeline-builder/components/iterator-editor/iterator-output/AddOutputButton.tsx
Because
- fix iterator can not add additional output
This commit
- fix iterator can not add additional output
=> fix: fix iterator can not add additional output

packages/design-system/src/ui-helpers/getModelHardwareToolkit.ts, packages/toolkit/src/components/ReadmeEditor.tsx, packages/toolkit/src/view/model/view-model/ModelApi.tsx, packages/toolkit/src/view/pipeline/view-pipeline/Head.tsx, packages/toolkit/src/view/pipeline/view-pipeline/PipelineApi.tsx, packages/toolkit/src/view/pipeline/view-pipeline/PipelineSettings.tsx
Because
- there are minor bugs and an issue with the readme editor
This commit
- in a way fixes INS-5366
- API wording update
- removed GitHub and License fields from the pipeline
=> fix: readme editor html fix, wording updates, remove GitHub and License from pipeline

packages/toolkit/src/view/pipeline-builder/components/nodes/common/NodeWrapper.tsx
Because
- fix user can not scroll in the node when it's overflow
This commit
- fix user can not scroll in the node when it's overflow
=> fix(pipeline-editor): fix user can not scroll in the node when it's overflow

packages/sdk/src/core/membership/MembershipClient.test.ts, packages/sdk/src/core/membership/MembershipClient.ts, packages/sdk/src/core/membership/types.ts, packages/sdk/src/main/index.ts
Because
- add get/list membership integration-test
This commit
- add get/list membership integration-test
=> chore(integration-test): add get/list membership integration-test

packages/toolkit/src/constant/pipeline.ts
Because
The endpoint from the Instill Cloud Toolkit should be:
https://api.instill.tech/v1beta/organizations/instill-ai/pipelines/ticket-triage-demo/trigger 
The endpoint from the Instill Cloud Toolkit is:
https://api.instill.tech/v1beta/organizations/instill-ai/pipelines/ticket-triage-demo/releases/latest/trigger
=> fix: incorrect endpoint to run pipeline

packages/toolkit/src/constant/model.ts, packages/toolkit/src/view/pipeline-builder/components/PipelineToolkitDialog.tsx, packages/toolkit/src/view/pipeline-builder/components/triggerPipelineSnippet.ts
Because
- fix model api snippet not correctly cast with double quote for authorization token
This commit
- fix model api snippet not correctly cast with double quote for authorization token
=> fix: fix model api snippet not correctly cast with double quote for authorization token

packages/toolkit/src/view/pipeline/view-pipeline/PipelineApi.tsx
Because
- fix typo in the pipeline api tab
This commit
-  fix typo in the pipeline api tab
=> fix: fix typo in the pipeline api tab

packages/toolkit/package.json, packages/toolkit/src/components/top-bar/ExploreLink.tsx, packages/toolkit/src/components/top-bar/NavLinks.tsx
Because
- fix navlink wrongly highlight when user is in /explore and /feature page
This commit
- fix navlink wrongly highlight when user is in /explore and /feature page
=> fix: fix navlink wrongly highlight when user is in /explore and /feature page

packages/toolkit/src/lib/use-instill-form/components/component-output/ImagesField.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output/VideosField.tsx, packages/toolkit/src/lib/use-instill-form/components/trigger-request-form-fields/ImagesField.tsx, packages/toolkit/src/lib/use-instill-form/components/trigger-request-form-fields/VideosField.tsx
Because
- multiple graphics elements inputs had white backgrounds , because of the `object-fit: contain` css prop
This commit
- made them use `object-fit: cover`
=> fix: make multiple graphics inputs use cover object fit instead of contain

packages/toolkit/src/view/model/view-model/ModelPlayground.tsx
Because
- replace log in to clone with log in to run button on the model page
This commit
- replace log in to clone with log in to run button on the model page
=> fix: replace log in to clone with log in to run button on the model page

packages/toolkit/src/lib/use-instill-form/components/common/VideoPreview.tsx
Because
- fix video input-output always show play icon after playing once
This commit
- fix video input-output always show play icon after playing once
=> fix(pipeline-editor): fix video input-output always show play icon after playing once

packages/toolkit/src/lib/use-instill-form/components/trigger-request-form-fields/VideoField.tsx
Because
- The video input looks like having wrong padding
This commit
- fix video input have the wrong width due to limited hight (Make it looks like having redundant padding)
=> fix(pipeline-editor): fix video input have the wrong width due to limited hight (Make it looks like having redundant padding)

packages/toolkit/src/lib/use-instill-form/pick/pickComponentOutputFieldsFromInstillFormTree.tsx
Because
- Even backend hint frontend that the response is array:semi-structured, we still need to handle the possibility that backend can return array of primitives type
This commit
- fix console not correctly handle array:semi-structured edge case
=> fix(pipeline-editor): fix console not correctly handle array:semi-structured edge case

packages/toolkit/package.json, packages/toolkit/src/components/top-bar/AppTopbar.tsx
Because
- We have duplicated indicator on featured/explore related pages
This commit
- fix duplicated page indicator on explore/featured related pages
=> fix: fix duplicated page indicator on explore/featured related pages

packages/toolkit/src/components/card-model/Tags.tsx, packages/toolkit/src/view/model/view-model/ModelHead.tsx
Because
- we need to show the private/public model status
This commit
- uncomment the labels code
=> feat: show private/public labels for model cards and on model page

packages/toolkit/src/view/recipe-editor/RecipeEditorView.tsx
Because
- fix focus tab will get changed when update the recipe
This commit
- fix focus tab will get changed when update the recipe
=> fix(editor): fix focus tab will get changed when update the recipe

packages/toolkit/src/view/recipe-editor/RecipeEditorView.tsx
Because
- Previously, we use .txt file extension for dowloaded recipe format. 
This commit
-  replace .txt with .yaml as download extension for low-code editor.
=> fix(editor): replace .txt with .yaml as download extension for low-code editor

packages/toolkit/src/lib/use-instill-store/editorSlice.ts, packages/toolkit/src/lib/use-instill-store/types.ts, packages/toolkit/src/view/recipe-editor/EditorViewBarItem.tsx, packages/toolkit/src/view/recipe-editor/EditorViewSectionBar.tsx, packages/toolkit/src/view/recipe-editor/RecipeEditorView.tsx, packages/toolkit/src/view/recipe-editor/VscodeEditor.tsx, packages/toolkit/src/view/recipe-editor/flow/Flow.tsx, packages/toolkit/src/view/recipe-editor/flow/nodes/GeneralNode.tsx, packages/toolkit/src/view/recipe-editor/getting-started-view/GettingStartedView.tsx, packages/toolkit/src/view/recipe-editor/input/Input.tsx, packages/toolkit/src/view/recipe-editor/sidebar/SupportLinks.tsx
Because
- When user expand the top-right panel, the main preview canvas will lose its focus and behave weirdly
This commit
- fix maximize and minimize view will cause preview not focus
=> fix(editor): fix maximize and minimize view will cause preview not focus

packages/toolkit/src/view/recipe-editor/commands/ComponentCmdo.tsx
Because
- CMDO will always list iterator even though user's search code filter it out
This commit
- fix iterator not respect search code in CMDO
=> fix(editor): fix iterator not respect search code in CMDO

packages/toolkit/src/view/recipe-editor/flow/nodes/GeneralNode.tsx
Because
- the delete button on the editor's preview didn't work
This commit
- disable the delete button on node
=> fix(editor): disable the delete button on node

packages/toolkit/src/components/VersionDropdownSelector.tsx
Because
- fix version selector can't be scrolled on pipeline overview page
This commit
- fix version selector can't be scrolled on pipeline overview page
=> fix: fix version selector can't be scrolled on pipeline overview page

packages/toolkit/src/view/pipeline/view-pipeline/PipelinePlayground.tsx, packages/toolkit/src/view/recipe-editor/Output.tsx
Because
- We want to make the user understand that they need to run the pipeline before viewing the result
This commit
- add the pipeline run output placeholder view
=> feat(editor): add the pipeline run output placeholder view 

packages/design-system/package.json, packages/sdk/package.json, packages/toolkit/package.json, packages/toolkit/src/view/pipeline/view-pipeline/ViewPipeline.tsx
Because
- fix pipeline overview share-by-link is not working
This commit
- fix pipeline overview share-by-link is not working
=> fix: fix pipeline overview share-by-link is not working

packages/toolkit/src/view/recipe-editor/VscodeEditor.tsx, packages/toolkit/src/view/recipe-editor/flow/nodes/NodeBase.tsx
Because
- reduce the low-code editor font-size to 12px
This commit
- reduce the low-code editor font-size to 12px
=> feat: reduce the low-code editor font-size to 12px

packages/toolkit/package.json, packages/toolkit/src/view/recipe-editor/flow/nodes/GeneralNode.tsx
Because
- fix the broken documentation link of instill-model component
This commit
- fix the broken documentation link of instill-model component
=> fix(editor): fix the broken documentation link of instill-model component

packages/toolkit/src/view/model/CreateModelForm.tsx
Because
- hide the TASK_CUSTOM model type
This commit
- hide the TASK_CUSTOM model type
=> feat: hide the TASK_CUSTOM model type

packages/toolkit/src/components/top-bar/CloudTopbarDropdown.tsx, packages/toolkit/src/view/recipe-editor/VscodeEditor.tsx
Because
- For some enum fields like openAI's model or component's task, we want to hint user full list to enhance UX
This commit
- import smart hint that user can directly input space to trigger hint window
=> feat: import smart hint that user can directly input space to trigger hint window

packages/toolkit/src/view/recipe-editor/commands/ComponentCmdo.tsx
Because
-  We use the wrong calculation to append component's default value with `executeEdit`
- This commit utilize native range collapse to correctly add the component's default value
This commit
- fix the wrong indent when adding the component placeholder
=> fix(editor): fix the wrong indent when adding the component placeholder

packages/toolkit/src/lib/use-instill-form/transform/transformInstillFormTreeToDefaultValue.ts, packages/toolkit/src/view/recipe-editor/commands/ComponentCmdo.tsx
When adding a new component, the default behavior is to add the full component recipe along with a null value. 
This can be confusing for users, as they might mistakenly believe that the null value is intended to be used for that field. Additionally, the full component recipe is quite lengthy and may overwhelm users.
Instead of displaying null, we will show an unset value (empty), making it clearer that the field is not yet assigned. 
Please view the change example below:
From
```
// Current
openai-0:
type: openai
input:
model: gpt-4o
prompt: null
system-message: You are a helpful assistant.
images: null
chat-history: null
temperature: 1
n: 1
max-tokens: null
response-format:
type: text
top-p: 1
presence-penalty: null
frequency-penalty: null
condition: null
setup:
organization: null
task: …
```
=> feat(editor): replace null with empty string when add the component

packages/toolkit/src/view/recipe-editor/flow/nodes/GeneralNode.tsx, packages/toolkit/src/view/recipe-editor/flow/nodes/IteratorNode.tsx
Because
- When a user clicks on a component in the preview, the cursor in the left editor panel will not only move to the corresponding code, but the screen will also automatically center the relevant line.
This commit
- scroll to target component line when click the node
=> feat(editor): scroll to target component line when click the node

packages/toolkit/src/view/recipe-editor/input/Input.tsx
Because
- Sometime pipeline is completed but component is still not received the complete status
This commit
- close all imcomplete status of components when pipeline is completed
=> feat(editor): close all imcomplete status of components when pipeline is completed

apps/console/src/app/[entity]/models/[id]/page.tsx, apps/console/src/app/[entity]/pipelines/[id]/page.tsx, packages/toolkit/src/view/model/ModelHubListPageMainView.tsx, packages/toolkit/src/view/model/view-model/ModelContentViewer.tsx, packages/toolkit/src/view/pipeline/view-pipeline/PipelineContentViewer.tsx, packages/toolkit/src/view/pipeline/view-pipeline/ViewPipeline.tsx
Because
[https://instill.tech/ownerID/pipeline/pipelineID/settings ](https://instill.tech/ownerID/pipeline/pipelineID/playground) tab should be redirected to playground if not owner of pipeline
[https://instill.tech/ownerID/models/modelId/settings ](https://instill.tech/ownerID/pipeline/pipelineID/playground) tab should be redirected to playground if not owner of model
https://instill.tech/ownerID/models/modelIDshould redirect to playground (if exists)
https://instill.tech/ownerID/models/modelIDshould redirect to 404 (if not exists)
https://instill.tech/ownerID/models/modelID/{tab} (if non existent model) should redirect to 404. 
https://instill.tech/ownerID/pipeline/pipelineID should redirect to playground (if exists)
https://instill.tech/ownerID/pipeline/pipelineID should redirect to …
=> fix(pipeline/models): fix add redirections

packages/toolkit/src/view/recipe-editor/VscodeEditor.tsx
Because
- stop editor from displaying undefined hover hint
This commit
- stop editor from displaying undefined hover hint
=> fix(editor): stop editor from displaying undefined hover hint

packages/toolkit/src/view/recipe-editor/EditorViewSectionBar.tsx, packages/toolkit/src/view/recipe-editor/RecipeEditorView.tsx, packages/toolkit/src/view/recipe-editor/RunButton.tsx, packages/toolkit/src/view/recipe-editor/commands/ActionCmdk.tsx, packages/toolkit/src/view/recipe-editor/commands/ComponentCmdo.tsx, packages/toolkit/src/view/recipe-editor/dialogs/ImportRecipeDialog.tsx, packages/toolkit/src/view/recipe-editor/lib/index.ts, packages/toolkit/src/view/recipe-editor/lib/useIsMac.ts
Because
- use CMD and ctrl instead of ⌘ to hint shortcut
This commit
- use CMD and ctrl instead of ⌘ to hint shortcut
=> feat: use CMD and ctrl instead of ⌘ to hint shortcut

packages/toolkit/package.json, packages/toolkit/src/view/recipe-editor/RecipeEditorView.tsx
Because
- redirect user to 404 if they are on editor and pipeline is not exist
This commit
- redirect user to 404 if they are on editor and pipeline is not exist
=> fix: redirect user to 404 if they are on editor and pipeline is not exist

packages/sdk/src/model/ModelClient.ts, packages/toolkit/src/lib/react-query-service/model/useLastModelTriggerResult.ts, packages/toolkit/src/lib/react-query-service/model/useModelVersionTriggerResult.ts, packages/toolkit/src/lib/vdp-sdk/operation/queries.ts, packages/toolkit/src/view/model/view-model/ModelPlayground.tsx
The model operation endpoint required the Instill requester id to be present in headers.
=> fix: add requester ID to the model operation request

Dockerfile.playwright, apps/console/next-env.d.ts, apps/console/package.json, apps/instill-form-playground/package.json, packages/design-system/package.json, packages/toolkit/package.json, pnpm-lock.yaml
Because
- Mitigate Nextjs cache poisoning attack
- https://github.com/instill-ai/console/security/dependabot/51
This commit
- update nextjs version to 14.2.10, clean up playwright deps
=> chore: update nextjs version to 14.2.10, clean up playwright deps

packages/toolkit/src/lib/use-instill-form/components/component-output/ObjectField.tsx, packages/toolkit/src/lib/use-instill-form/pick/pickComponentOutputFieldsFromInstillFormTree.tsx, packages/toolkit/src/view/catalog/components/lib/helpers.tsx, packages/toolkit/src/view/pipeline/view-pipeline/PipelinePlayground.tsx
Because
- For example, when output a is semi-structured, it's value should be `{"foo": 123}`, but sometime when BE can't recognize the correct type, it might directly send 123, which is a primitive type, we need to deal with this
This commit
- fix object output is wrong when BE response semi-structure result type but the result is actually string
=> fix: fix object output is wrong when BE response semi-structure result type but the result is actually string

packages/toolkit/src/view/recipe-editor/lib/PipelineFlowFactory/edgeHelpers/composeEdgesForReference.ts
Because
- fix wrongly handle reference prefix cause connecting is missing
This commit
- fix wrongly handle reference prefix cause connecting is missing
=> fix: fix wrongly handle reference prefix cause connecting is missing

packages/toolkit/src/view/recipe-editor/RecipeEditorView.tsx
Because
- fix recipe editor sidebar tooltip not respond to whether the sidebar is open or not
This commit
- fix recipe editor sidebar tooltip not respond to whether the sidebar is open or not
=> fix(vdp): fix recipe editor sidebar tooltip not respond to whether the sidebar is open or not

packages/toolkit/package.json, packages/toolkit/src/view/model/view-model/ModelPlayground.tsx
To test this this toolkit version could be used for cloud `0.107.0-rc.15`
Because
- changing namespace on model playground did not reset the i/o forms data
This commit
- now it do reset it
https://github.com/user-attachments/assets/f058e1ed-804f-4d53-bcf9-03286eea226a
=> fix: reset playground i/o data on namespace change

apps/console/src/app/(providers)/root-provider.tsx, packages/toolkit/src/view/pipeline-builder/lib/getReferencesFromAny.ts
Because
- For example, if I want to connect a to b,c,d. The factory we have right now only form the first edge
This commit
- fix can't construct multiple edges to multiple components from single component
=> fix(editor): fix can't construct multiple edges to multiple components from single component

packages/sdk/package.json, packages/sdk/src/core/integration/IntegrationClient.ts, packages/sdk/src/core/integration/type.ts, packages/toolkit/package.json, packages/toolkit/src/lib/integrations/core.ts
Because
- fix sdk didn't add oAuthAccessDetails and scopes into the payload
This commit
- fix sdk didn't add oAuthAccessDetails and scopes into the payload
=> fix: fix sdk didn't add oAuthAccessDetails and scopes into the payload

apps/console/download-component-icons.ts
Because
- fix download component icon script to fallback invalid version
This commit
- fix download component icon script to fallback invalid version
=> fix: fix download component icon script to fallback invalid version

packages/sdk/src/vdp/pipeline/PipelineClient.ts, packages/sdk/src/vdp/pipeline/types.ts, packages/toolkit/src/components/ClonePipelineDialog.tsx, packages/toolkit/src/lib/react-query-service/pipeline/useCloneNamespacePipeline.ts
Because
- console wrongly handle namespaceId and resourceId when clone the pipeline on pipeline list page
This commit
-  fix cant clone pipeline from pipeline list page
=> fix: fix cant clone pipeline from pipeline list page

packages/sdk/generate-mocks/main.ts, packages/sdk/generate-mocks/transform.ts, packages/sdk/generate_mocks.sh, packages/sdk/setupTests.ts
Because
- In https://github.com/instill-ai/protobufs/commit/9d69b5c4ad755c613fdf0d0da47e9a4f03ab4461, we merge multiple openapi swagger into the single one, which cause the sdk's gen-mocks script failed. 
This commit
- fix sdk integration-test caused by the new revamp of instill-ai protobuf
=> fix: fix sdk integration-test caused by the new revamp of instill-ai protobuf

packages/toolkit/src/view/catalog/CatalogMainView.tsx, packages/toolkit/src/view/catalog/components/tabs/AskQuestionTab.tsx, packages/toolkit/src/view/catalog/components/tabs/RetrieveTestTab.tsx
Because
- if user is an organization show requester UID in example code blocks
=> feat(catalog): add Requester UID to example code in Ask and Retrieve pages 

packages/toolkit/src/constant/pipeline.ts, packages/toolkit/src/lib/use-instill-form/components/component-output/DownloadableFileField.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output/DownloadableFilesField.tsx, packages/toolkit/src/lib/use-instill-form/components/component-output/index.ts, packages/toolkit/src/lib/use-instill-form/components/trigger-request-form-fields/FileField.tsx, packages/toolkit/src/lib/use-instill-form/components/trigger-request-form-fields/FilesField.tsx, packages/toolkit/src/lib/use-instill-form/pick/pickComponentOutputFieldsFromInstillFormTree.tsx, packages/toolkit/src/lib/use-instill-form/pick/pickPipelineTriggerRequestFormFields.tsx, packages/toolkit/src/lib/use-instill-form/transform/transformPipelineTriggerRequestFieldsToZod.ts, packages/toolkit/src/view/recipe-editor/VscodeEditor.tsx
Because
- support document format for pipeline input and output
- We introduce a way for user to download the file
This commit
- support document format for pipeline input and output
=> feat: support document format for pipeline input and output

packages/toolkit/src/view/catalog/components/lib/uploadFileWithProgress.ts, packages/toolkit/src/view/catalog/components/tabs/UploadExploreTab.tsx
Because
- Start progress bar immediately after clicking process files
=> fix(catalog): start file upload progress tracking immediately after uploading files 

packages/toolkit/src/view/catalog/components/CloneCatalogDialog.tsx
=> fix(catalog): disable clone button if namespace is full

packages/design-system/src/new-ui/DataTable/DataTable.stories.tsx, packages/design-system/src/new-ui/Table/Table.stories.tsx, packages/toolkit/src/view/dashboard/DashboardPipelineListPageMainView.tsx, packages/toolkit/src/view/dashboard/DashboardPipelinesTable.tsx, packages/toolkit/src/view/dashboard/PipelineTriggersTable.tsx, packages/toolkit/src/view/dashboard/TriggersTablePlaceholder.tsx, packages/toolkit/src/view/dashboard/activity/ModelTriggersSummary.tsx, packages/toolkit/src/view/dashboard/activity/ModelsTriggerCountsLineChart.tsx, packages/toolkit/src/view/dashboard/activity/PipelineTriggerCountsLineChart.tsx, packages/toolkit/src/view/dashboard/activity/PipelineTriggersSummary.tsx
Because
- rename pipeline/model triggers to runs
This commit
- rename pipeline/model triggers to runs
=> feat(dashboard): rename pipeline/model triggers to runs

packages/toolkit/src/lib/use-instill-form/components/trigger-request-form-fields/AudiosField.tsx, packages/toolkit/src/lib/use-instill-form/components/trigger-request-form-fields/FilesField.tsx, packages/toolkit/src/lib/use-instill-form/components/trigger-request-form-fields/ImagesField.tsx, packages/toolkit/src/lib/use-instill-form/components/trigger-request-form-fields/VideosField.tsx
Because
- For multiple file upload the user need to select all the file at once instead of upload file one by one
This commit
- fix array file wrong UX that will make user feel that can add more files step by step
=> fix: fix array file wrong UX that will make user feel that can add more files step by step

packages/toolkit/src/view/recipe-editor/lib/schema.ts
Because
- replace restapi with http on the schema validation 
This commit
- replace restapi with http on the schema validation
=> fix: replace restapi with http on the schema validation 

apps/console/src/styles/global.css
Because
- remove empty extra bottom space of recipe editor
This commit
- remove empty extra bottom space of recipe editor
=> fix: remove empty extra bottom space of recipe editor

packages/toolkit/package.json, packages/toolkit/src/view/recipe-editor/RecipeEditorView.tsx, packages/toolkit/src/view/recipe-editor/flow/nodes/EventMessage.tsx, packages/toolkit/src/view/recipe-editor/flow/nodes/RunOnEventNode.tsx, packages/toolkit/src/view/settings/integrations/connectable-integration/ConnectableIntegration.tsx
Because
- fix duplicated getting started tab and event message hint text on recipe editor
This commit
- fix duplicated getting started tab and event message hint text on recipe editor
=> fix: fix duplicated getting started tab and event message hint text on recipe editor

packages/toolkit/src/lib/use-instill-form/components/component-output/DownloadableFilesField.tsx, packages/toolkit/src/lib/use-instill-form/components/trigger-request-form-fields/FileAndStringUploadField.tsx, packages/toolkit/src/view/dashboard/cost/pipeline/DashboardListPipeline.tsx, packages/toolkit/src/view/recipe-editor/RecipeEditorView.tsx, packages/toolkit/src/view/recipe-editor/commands/ComponentCmdo.tsx, packages/toolkit/src/view/recipe-editor/flow/nodes/RunOnEventNode.tsx, packages/toolkit/src/view/recipe-editor/input/Input.tsx, packages/toolkit/src/view/recipe-editor/lib/PipelineFlowFactory/nodeHelpers/createNodesFromRunOnEvent.ts
Because
- clean up unused console log
This commit
- clean up unused console log
=> chore: clean up unused console log

packages/toolkit/src/lib/use-instill-form/components/trigger-request-form-fields/TextareasField.tsx, packages/toolkit/src/lib/use-instill-form/components/trigger-request-form-fields/TextsField.tsx
Because
- Pipeline trigger form field for multiple text input like TestAreas, TextFields will have duplicated error message
This commit
- fix duplicated error message for multiple texts input of pipeline trigger form
=> fix: fix duplicated error message for multiple texts input of pipeline trigger form

packages/sdk/src/core/integration/type.ts, packages/toolkit/src/view/settings/integrations/connectable-integration/ManualSettingDialog.tsx, packages/toolkit/src/view/settings/integrations/existing-connection/EditConnectionDialog.tsx
Because
- deprecate the usage of integration.schemas
This commit
- deprecate the usage of integration.schemas
=> feat: deprecate the usage of integration.schemas

packages/toolkit/src/lib/integrations/core.ts
Because
- we need `drive.file` scope to create/update/delete data in Google Drive
This commit
- adjusts OAuth scope for google-drive component
=> chore(integration): adjust OAuth scope for google-drive component

packages/sdk/src/model/types.ts, packages/sdk/src/vdp/trigger/types.ts, packages/toolkit/src/view/dashboard/cost/model/DashboardListModel.tsx, packages/toolkit/src/view/dashboard/cost/pipeline/DashboardListPipeline.tsx
Because
- The `PipelineRun` and `ModelRun` objects have confusing documentation for
the requester, runner and owner of a pipeline/model run.
This commit
- Adopts the changes in https://github.com/instill-ai/protobufs/pull/519
=> chore(run logging): clarify actors in Run objects

packages/sdk/package.json, packages/sdk/src/types.ts, packages/toolkit/package.json, packages/toolkit/src/view/recipe-editor/commands/ComponentCmdo.tsx
Because
- fix cmdo event title, to make it more human readable
This commit
- fix cmdo event title, to make it more human readable
=> fix: fix cmdo event title, to make it more human readable

packages/toolkit/src/view/recipe-editor/lib/schema.ts
Because
- we want users to explicitly define which variables are required.
This commit
- adds support for the required attribute in variables.
=> chore: support `required` attribute in variable section

packages/toolkit/src/lib/use-instill-form/components/regular/OneOfConditionField.tsx, packages/toolkit/src/lib/use-instill-form/pick/pickRegularFieldsFromInstillFormTree.tsx, packages/toolkit/src/lib/use-instill-form/useInstillForm.tsx, packages/toolkit/src/view/settings/integrations/ConnectionForm.tsx
Because
- In different phase we have different structure of component schema, previously we used the oneOf, const field's title field to determine what to display for the condition dropdown right now we move it to the root of the condition item itself
This commit
- fix integration item auto-gen-form issue
=> fix: fix integration item auto-gen-form issue

packages/toolkit/src/lib/integrations/core.ts
Because
- add drive.file scope into google sheet
This commit
- add drive.file scope into google sheet
=> feat(integration): add drive.file scope into google sheet

packages/toolkit/src/view/recipe-editor/lib/schema.ts
Because
- the default value in the variable section can represent various data types.
This commit
- expands support for additional data types in the variable default field. Since the default value can be of any data type, we remove the `type` limitation.
=> fix: allow more data types in the variable default field

packages/design-system/package.json, packages/design-tokens/package.json, packages/sdk/package.json, packages/toolkit/package.json, pnpm-lock.yaml
Because
- fully update vitest to 2.1.9
This commit
- fully update vitest to 2.1.9
=> feat: fully update vitest to 2.1.9

packages/sdk/package.json, packages/sdk/src/helper/cellHelper.ts, packages/sdk/src/table/types.ts, packages/toolkit/package.json, packages/toolkit/src/components/top-bar/ChatLink.tsx
Because
- The new table cell types are string/number/boolean/file
This commit
- The new table cell types are string/number/boolean/file
=> feat: update table cell type

packages/toolkit/src/lib/react-query-service/pipeline/useDeleteNamespacePipeline.ts, packages/toolkit/src/view/pipeline/view-pipeline/Head.tsx
Because
- fix not correctly invalidate query when delete pipeline
This commit
- fix not correctly invalidate query when delete pipeline
=> fix: fix not correctly invalidate query when delete pipeline

packages/sdk/package.json, packages/sdk/src/table/types.ts, packages/toolkit/package.json, packages/toolkit/src/lib/use-instill-store/tableSlice.ts, packages/toolkit/src/lib/use-instill-store/types.ts
Because
-  add editing table column state to be used in the cloud's Table.
=> feat: add editing table column state

packages/sdk/package.json, packages/sdk/src/table/types.ts, packages/toolkit/package.json
We need `catalogId` and `fileUrl` to enable some of the UI interaction in console. For example, the file overview and summary. So BE help us return this kind of information.
=> feat: add catalog related data into fileCell

packages/sdk/package.json, packages/sdk/src/table/types.ts, packages/toolkit/package.json, packages/toolkit/src/lib/use-instill-store/types.ts
We want to support different logic upon the cell preview. So we need a broader range of setting on cell preview state
=> feat: update store type to support broader range of cell preview

packages/toolkit/src/constant/model.ts
Because
- we've migrated the artifacts.instill.tech domain to artifacts.instill-ai.com
This commit
- update outdated artifact image URLs to reflect the new domain
=> fix: update outdated artifact image URLs

packages/sdk/package.json, packages/sdk/src/table/types.ts, packages/toolkit/package.json, packages/toolkit/src/lib/use-instill-store/tableSlice.ts, packages/toolkit/src/lib/use-instill-store/types.ts
We previously put the numberFormat in the cell object, but this is wrong, it should be in the column definition object, this PR fixes this issue
=> fix: fix number format key and object in column definition

packages/sdk/package.json, packages/sdk/src/table/types.ts, packages/toolkit/package.json
We will retire the value key in every cell type, let's take StringCell for example, previously it's structure is 
```
stringValue: {
value: "foo",
userInput: "foo",
computedValue: "bar"
}
```
From now on it will be
```
stringValue: {
userInput: "foo",
computedValue: "bar"
}
```
=> fix: remove value in table cell value

packages/toolkit/src/lib/use-instill-form/components/component-output/TextsField.tsx, packages/toolkit/src/lib/use-instill-form/pick/pickComponentOutputFieldsFromInstillFormTree.tsx
Because
- on pipeline triggering, the builder reports error `index.mjs:72394 Each child in a list should have a unique "key" prop.`
This commit
- fixes the issue by using index-based keys.
=> fix(toolkit): fix form key missing errors

packages/toolkit/src/view/recipe-editor/lib/schema.ts
Because
- the pipeline builder didn't recognize the component type `gemini`.
This commit
- adds Gemini connector (i.e., component) definition.
=> chore(toolkit): add gemini connector definition
